// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// Calls each activated plugin's bridge-class register() at startup, then
// hands the Activity to any bridge implementing MobActivityAware and records
// any bridge implementing MobPermissionProvider; invoked from
// MainActivity.onCreate as registerAll(this).
package io.mob.plugin

import android.app.Activity

object MobPluginBootstrap {
    private val permissionProviders = mutableListOf<MobPermissionProvider>()

    @JvmStatic
    fun registerAll(activity: Activity) {}

    // Returns the first plugin-supplied Android permission mapping for `cap`,
    // or null if no activated plugin provides this capability. Core
    // MobBridge.request_permission consults this in its `else` branch.
    @JvmStatic
    fun permissionsFor(cap: String): Array<String>? {
        for (provider in permissionProviders) {
            val perms = provider.permissionsFor(cap)
            if (perms != null) return perms
        }
        return null
    }
}
