defmodule Kati.Nifs.KatiSecureStore do
  @moduledoc """
  The statically-linked NIF that binds `Kati.SecureStore` to the Keystore.

  Scaffolded by `mix mob.add_nif kati_secure_store --type c`; the native body
  is `c_src/kati_secure_store.c`. `kati_secure_store_nif_init` is registered in
  `priv/generated/driver_tab_{android,ios}.zig` (regenerated by
  `mix mob.regen_driver_tab` from `mob.exs`'s `:static_nifs`), so at BEAM
  startup `load_nif/2` resolves against that table rather than opening a `.so`.

  ## Nobody should call this module

  `Kati.SecureStore` is the surface. This one is four marshalling functions
  with no validation and no policy — it will happily hand an empty key or a
  four-megabyte value to JNI. The four names and arities here are load-bearing:
  they must match `nif_funcs[]` in the C file exactly, or `load_nif/2` fails
  with `{:bad_lib, ...}` and every credential operation reports the store
  absent.

  ## The wire

  Values cross **base64-encoded** and replies are `"ok"`, `"ok:<payload>"` or
  `"error:<reason>"` — see `Kati.SecureStore`'s "bridge contract" section, and
  `android/app/src/main/java/com/example/kati/KatiSecureStore.kt` for the same
  protocol written from the other end.

  ## Why a failed load is swallowed

  `@on_load` returning an error makes the module fail to load, which is the
  usual and correct behaviour for a NIF stub — but here it turns every
  `Kati.SecureStore.available?/0` call on the host into a multi-line
  `[warning] The on_load function for module ... returned {:error, {:load_failed,
  ...}}`, because `Code.ensure_loaded?/1` retries the load each time. Kati asks
  that question from screens and from tests, on a host that will never have a
  NIF.

  So the load result is discarded and the *stubs* carry the failure instead:
  unbound, every function below raises `:erlang.nif_error(:nif_not_loaded)`,
  and `Kati.SecureStore` maps exactly that to `{:error, :no_native_store}`.
  Nothing is hidden — the store still reports itself absent, by the same
  route, and `Kati.SecureStoreTest` asserts it. What is avoided is a warning
  storm that says the same thing several hundred times per test run.
  """

  @on_load :load_nif

  @doc false
  def load_nif do
    # The second argument is ignored for a static NIF (there is no path to
    # read); 0 is the convention mob_dev's scaffold uses.
    _ = :erlang.load_nif(~c"kati_secure_store", 0)
    :ok
  end

  @doc "`\"ok:hardware\"` | `\"ok:software\"` | `\"error:<reason>\"`."
  @spec status() :: binary()
  def status, do: :erlang.nif_error(:nif_not_loaded)

  @doc "`key` and base64-encoded `value` in; `\"ok\"` or `\"error:<reason>\"` out."
  @spec put(binary(), binary()) :: binary()
  def put(_key, _value_base64), do: :erlang.nif_error(:nif_not_loaded)

  @doc "`\"ok:<base64>\"` or `\"error:<reason>\"`."
  @spec get(binary()) :: binary()
  def get(_key), do: :erlang.nif_error(:nif_not_loaded)

  @doc "`\"ok\"` or `\"error:<reason>\"`. Deleting nothing succeeds."
  @spec delete(binary()) :: binary()
  def delete(_key), do: :erlang.nif_error(:nif_not_loaded)
end
