defmodule Kati.SyncSchema do
  @moduledoc """
  Creates the two sync tables for the host test suite.

  ## Why this exists, and when it stops mattering

  `Kati.Sync.OutboxEntry` and `Kati.Sync.RejectedChange` are new Ash resources,
  and their migrations are generated by `mix ash.codegen` — which runs once,
  serially, after every resource in this round has landed. Until then there is
  no table, and a sync suite that cannot write a row is a sync suite that
  proves nothing.

  So this issues `CREATE TABLE IF NOT EXISTS` derived **from the resource
  itself** rather than from a hand-written column list. Two consequences, both
  deliberate:

    * it cannot drift — a column added to the resource is in the bridge the
      moment it exists, because the bridge reads `Ash.Resource.Info`;
    * once the generated migration lands, `IF NOT EXISTS` makes every statement
      here a no-op and the suite runs against the real schema.

  `Kati.SyncOutboxTest.test "the bridge schema matches the resource"` closes the
  loop from the other side: it reads `PRAGMA table_info` back and fails if the
  live table and the resource disagree. So if the generated migration ever
  differs from what the resource declares, the suite says so rather than
  passing against a table that is quietly wrong.
  """

  @resources [Kati.Sync.OutboxEntry, Kati.Sync.RejectedChange]

  @doc "Create the sync tables if the migration has not created them yet."
  @spec ensure!() :: :ok
  def ensure! do
    Enum.each(@resources, fn resource ->
      table = AshSqlite.DataLayer.Info.table(resource)
      Ecto.Adapters.SQL.query!(Kati.Repo, create_table(resource, table), [])
      Enum.each(indexes(resource, table), &Ecto.Adapters.SQL.query!(Kati.Repo, &1, []))
    end)

    :ok
  end

  @doc "The columns the resource declares, sorted."
  @spec declared_columns(module()) :: [String.t()]
  def declared_columns(resource) do
    resource
    |> Ash.Resource.Info.attributes()
    |> Enum.map(&to_string(&1.name))
    |> Enum.sort()
  end

  @doc "The columns the live table actually has, sorted."
  @spec live_columns(module()) :: [String.t()]
  def live_columns(resource) do
    table = AshSqlite.DataLayer.Info.table(resource)
    %{rows: rows} = Ecto.Adapters.SQL.query!(Kati.Repo, "PRAGMA table_info(#{table})", [])
    rows |> Enum.map(&Enum.at(&1, 1)) |> Enum.sort()
  end

  defp create_table(resource, table) do
    columns =
      resource
      |> Ash.Resource.Info.attributes()
      |> Enum.map_join(", ", fn attribute ->
        primary = if attribute.primary_key?, do: " PRIMARY KEY", else: ""
        null = if attribute.allow_nil? or attribute.primary_key?, do: "", else: " NOT NULL"
        "#{attribute.name} #{column_type(attribute.type)}#{primary}#{null}"
      end)

    "CREATE TABLE IF NOT EXISTS #{table} (#{columns})"
  end

  defp indexes(resource, table) do
    resource
    |> AshSqlite.DataLayer.Info.custom_indexes()
    |> Enum.map(fn index ->
      fields = Enum.map_join(index.fields, ", ", &to_string/1)
      name = "#{table}_" <> Enum.map_join(index.fields, "_", &to_string/1) <> "_bridge_index"
      unique = if index.unique, do: "UNIQUE ", else: ""
      "CREATE #{unique}INDEX IF NOT EXISTS #{name} ON #{table} (#{fields})"
    end)
  end

  # SQLite is dynamically typed and ecto_sqlite3 decides how to load a value
  # from the Ecto type rather than the column's declared one, so affinity is
  # all that matters here: TEXT for everything that is not a number.
  defp column_type(Ash.Type.Integer), do: "INTEGER"
  defp column_type(Ash.Type.Boolean), do: "INTEGER"
  defp column_type(_type), do: "TEXT"
end
