defmodule Mix.Tasks.Kati.Gen.Nowruz do
  @shortdoc "Generate the Nowruz lookup table for Kati.Calendar.Shamsi"

  @moduledoc """
  Emits Nowruz (1 Farvardin) as a Persian-year → Gregorian-ISO-day map.

  `ex_cldr_calendars_persian` is correct — observational, Tehran meridian — but
  costs **476 µs per conversion**, which is 7.9 ms for a single month grid
  before any formatting. The generated table is **1.26 µs**, roughly 380× faster,
  and identical over the generated range.

  Dev-only. `ex_cldr_calendars_persian` is `only: :dev, runtime: false` and is
  never shipped.

      mix kati.gen.nowruz

  Prints a mismatch count over the whole range, so a regeneration that drifts is
  loud rather than silent.
  """
  use Mix.Task

  @from 1300
  @to 1600
  @target "lib/kati/calendar/nowruz_table.ex"

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("app.start")

    unless Code.ensure_loaded?(Cldr.Calendar.Persian) do
      Mix.raise("ex_cldr_calendars_persian is not available — run in :dev")
    end

    entries =
      for year <- @from..@to do
        # 1 Farvardin of the Persian year, as an ISO days number.
        iso_days = Cldr.Calendar.Persian.date_to_iso_days(year, 1, 1)
        {year, iso_days}
      end

    mismatches = verify(entries)

    body = """
    defmodule Kati.Calendar.NowruzTable do
      @moduledoc \"\"\"
      Nowruz (1 Farvardin) per Persian year, as ISO day numbers.

      GENERATED by `mix kati.gen.nowruz` — do not edit by hand.

      Range #{@from}–#{@to} SH. Verified against `ex_cldr_calendars_persian`
      at generation time with #{mismatches} mismatches.

      Exists because the reference implementation costs ~476 µs per conversion,
      which is ~7.9 ms for one month grid before formatting. Lookup is ~1.26 µs.
      \"\"\"

      @first_year #{@from}
      @last_year #{@to}

      @nowruz %{
    #{Enum.map_join(entries, ",\n", fn {y, d} -> "    #{y} => #{d}" end)}
      }

      @doc "First and last Persian year covered by the table."
      def range, do: {@first_year, @last_year}

      @doc "ISO day number of 1 Farvardin for a Persian year, or nil if out of range."
      def nowruz(year), do: Map.get(@nowruz, year)
    end
    """

    File.mkdir_p!(Path.dirname(@target))
    File.write!(@target, body)

    Mix.shell().info([
      :green,
      "* generated ",
      :reset,
      "#{@target} — #{length(entries)} years, #{mismatches} mismatches"
    ])

    if mismatches > 0 do
      Mix.raise(
        "#{mismatches} mismatches against the reference implementation — do not ship this"
      )
    end
  end

  # Round-trip every year through the reference implementation: converting the
  # generated ISO day back must land on 1 Farvardin of the same year.
  defp verify(entries) do
    Enum.count(entries, fn {year, iso_days} ->
      case Cldr.Calendar.Persian.date_from_iso_days(iso_days) do
        {^year, 1, 1} -> false
        _ -> true
      end
    end)
  end
end
