defmodule Mix.Tasks.Kati.Gen.Icons do
  @shortdoc "Regenerates Kati.Icons from the design and the Material Symbols codepoints"

  @moduledoc """
  Generates `lib/kati/icons.ex` — every Material Symbols name the design uses,
  mapped to its codepoint.

      mix kati.gen.icons

  ## Why a generated map rather than ligatures

  Material Symbols is normally used by typing the icon's name and letting the
  `liga` feature fold it into one glyph. Kati renders the **codepoint**
  instead, because the shipped font is a 411 KB subset of a 15 MB original and
  subsetting by codepoint is exact: a name that survives here is a glyph that
  survives there, and this task fails if the two ever disagree.

  ## Why it reads the design

  The set of icons is whatever the 62 screens actually use — currently 143.
  Regenerating after a design change is how a new icon gets into the subset,
  and the task prints the pyftsubset invocation needed to rebuild the font.
  """

  use Mix.Task

  @screens ".scratch/design/screens"
  @codepoints ".scratch/design/material_symbols.codepoints"
  @target "lib/kati/icons.ex"

  @impl Mix.Task
  def run(_args) do
    codepoints = load_codepoints()
    used = scan_design()

    {known, unknown} = Enum.split_with(used, &Map.has_key?(codepoints, &1))

    if unknown != [] do
      Mix.raise("""
      icons used by the design but absent from #{@codepoints}:

        #{Enum.join(unknown, "\n  ")}

      The codepoints file is probably older than the design. Refresh it from
      google/material-design-icons.
      """)
    end

    pairs = Enum.map(known, &{&1, Map.fetch!(codepoints, &1)})
    File.write!(@target, render(pairs))

    Mix.shell().info("wrote #{@target} — #{length(pairs)} icons")

    Mix.shell().info("""

    If the set changed, rebuild the font subset so the glyphs exist:

      pyftsubset MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf \\
        --unicodes=#{pairs |> Enum.map(fn {_, cp} -> "U+" <> String.upcase(cp) end) |> Enum.join(",") |> String.slice(0, 60)}… \\
        --output-file=android/app/src/main/res/font/kati_symbols.ttf
    """)
  end

  defp load_codepoints do
    @codepoints
    |> File.read!()
    |> String.split("\n", trim: true)
    |> Map.new(fn line ->
      [name, cp] = String.split(line, " ", parts: 2)
      {name, String.trim(cp)}
    end)
  end

  # Deliberately EMPTY, and worth saying why so nobody refills it.
  #
  # Two glyphs looked like they belonged here: `star_half` for screen 33 and
  # `expand_less` for screen 02's air-date group. Neither is in the drawings,
  # because the design makes both marks WITHOUT a Material Symbol — the half
  # star is a gradient hard-stopped across one `star`, and the collapse chevron
  # is `expand_more` rotated 180deg in CSS.
  #
  # Adding them here would have meant re-subsetting the font from a source
  # variable font that is not in this repo, to obtain one glyph that is another
  # glyph upside down and one that is another glyph cut in half. Fence K-16
  # gave the bridge `rotate` and `clip_width` instead, which is what the design
  # itself uses, and the subset stays exactly the set the drawings name.
  @extra []

  defp scan_design do
    scanned =
      @screens
      |> Path.join("*.html")
      |> Path.wildcard()
      |> Enum.flat_map(fn path ->
        Regex.scan(
          ~r/<span[^>]*Material Symbols Rounded[^>]*>([a-z0-9_]+)<\/span>/,
          File.read!(path)
        )
        |> Enum.map(fn [_, name] -> name end)
      end)

    (scanned ++ @extra)
    |> Enum.uniq()
    |> Enum.sort()
  end

  defp render(pairs) do
    entries =
      pairs
      |> Enum.map(fn {name, cp} -> ~s(    "#{name}" => "\\u#{String.upcase(cp)}") end)
      |> Enum.join(",\n")

    """
    defmodule Kati.Icons do
      @moduledoc \"\"\"
      Material Symbols Rounded, by name.

      Generated by `mix kati.gen.icons` from the design in
      `.scratch/design/screens/` — do not edit. #{length(pairs)} icons, which is
      every symbol the 62 screens use.

      Kati ships a **subset**: the full variable font is 15 MB, the subset is
      411 KB, and it keeps all four axes so `FILL 1` still works for the active
      tab. An icon absent here is absent from the font too, which is why
      `glyph!/1` raises rather than rendering a blank box.
      \"\"\"

      @icons %{
    #{entries}
      }

      @doc "The character for an icon name, or `nil`."
      @spec glyph(String.t()) :: String.t() | nil
      def glyph(name), do: Map.get(@icons, name)

      @doc \"\"\"
      The character for an icon name, raising if the font does not carry it.

      Loud on purpose: a missing glyph renders as an empty box, which reads as
      a layout bug rather than a missing asset and is expensive to trace back.
      \"\"\"
      @spec glyph!(String.t()) :: String.t()
      def glyph!(name) do
        case glyph(name) do
          nil ->
            raise ArgumentError,
                  "no Material Symbol \#{inspect(name)} in Kati's subset. " <>
                    "Add it to the design and run `mix kati.gen.icons`, then re-subset the font."

          char ->
            char
        end
      end

      @doc "Every icon name Kati ships."
      @spec names() :: [String.t()]
      def names, do: Map.keys(@icons) |> Enum.sort()
    end
    """
  end
end
