// KATI-BEGIN(K-05 vendored-header) mob_new=0.4.20
// KATI-VENDORED: generated by mob_new 0.4.20 against mob 0.7.20 on 2026-08-18.
// Third-party code. Do not edit outside KATI-BEGIN/KATI-END fences.
// Upgrade procedure: bin/mob_bridge_diff.sh — see native/README.md.
// KATI-END(K-05 vendored-header)
// beam_main.m — Generated by mix mob.new.
// Edit APP_MODULE to change the Elixir app module name.

#define APP_MODULE "kati"

// Returns the app module name to AppDelegate.m (avoids a shared header).
const char* mob_app_module(void) {
    return APP_MODULE;
}
