defmodule Kati.Screens.Shopping do
  @moduledoc """
  Screen 48 — Shopping, pushed under Meals.

  Built to `.scratch/design/screens/48.html`. The list is generated by summing
  the week's ingredients and grouping them by aisle, and every line carries the
  meals that asked for it — `7 meals`, `4 dinners`, `snack ×7` — so cutting a
  meal visibly shrinks the list. That sub-line is the screen's whole argument,
  which is why the copy is the design's rather than invented.

  Three groupings sit above it as chips ("By aisle" chosen), and a basket card
  states progress in words as well as in a bar: `9 of 24 in the basket`. The
  bar alone would be colour carrying meaning on its own, which screen 41 rules
  out.

  The aisle groups are `Kati.UI.SettingsList`'s card and row — the same
  `#FBFAF8` at radius 20, the same `4px 15px`, the same hairline the last row
  does not get — with a tick box in the leading slot instead of the 30pt icon
  tile. What is bespoke here is bespoke in the drawing too: the checkbox, the
  mono sub-line at `#C4BDB3`, and the amount in the trailing slot.

  No dock, so the frame's bottom inset is 40 rather than 132.

  ## The struck line

  The design greys a bought item and strikes it through. The bridge's `Text`
  has no text-decoration prop and nothing measures text, so the strike is a
  hairline of **declared** width drawn over the label inside a `Box` — the same
  crude-but-honest trick `Kati.UI.chip/2` uses for its own width. It
  deliberately undershoots, because a strike that stops inside the word reads
  as a strike, and one that overshoots reads as a layout bug.
  """
  use Kati.Screens.Pushed, back: "Meals"

  alias Kati.Components.MishkaActionIcon
  alias Kati.Meals.SampleShopping
  alias Kati.Theme.Palette
  alias Kati.UI.SettingsList

  @impl true
  def load(socket), do: Mob.Socket.assign(socket, :list, SampleShopping.list())

  @doc false
  def content(assigns) do
    list = assigns.list

    ~MOB"""
    <Scroll>
      <Column
        fill_width={true}
        padding_left={21}
        padding_right={21}
        padding_top={64}
        padding_bottom={40}
      >
        {SettingsList.chrome("more_horiz")}
        {SettingsList.title("Shopping", list.subtitle)}
        {Kati.Screens.Shopping.basket(list)}
        {Kati.Screens.Shopping.filters(list)}
        {Enum.map(list.aisles, fn aisle -> Kati.Screens.Shopping.aisle(aisle) end)}
        {Kati.Screens.Shopping.actions()}
      </Column>
    </Scroll>
    """
  end

  @doc false
  def basket(list) do
    ~MOB"""
    <Column fill_width={true}>
      <Column
        fill_width={true}
        background={Palette.card()}
        corner_radius={20}
        shadow={Kati.Theme.shadow_card_soft()}
        padding={15}
      >
        <Row fill_width={true} align="center">
          <Text
            text={list.basket}
            text_size={13.5}
            font_weight="bold"
            text_color={:on_surface}
            max_lines={1}
          />
          <Spacer weight={1.0} />
          <Text
            text={list.estimate}
            font_family="mono"
            text_size={11.5}
            text_color={Palette.ink_soft()}
            max_lines={1}
          />
        </Row>
        <Spacer size={12} />
        {Kati.Screens.Shopping.progress(list.progress)}
      </Column>
      <Spacer size={18} />
    </Column>
    """
  end

  # Two weighted children inside a filled track, not a child of declared width:
  # nothing reports the track's pixel width back, so the fraction has to be
  # expressed as weight or it cannot be expressed at all.
  @doc false
  def progress(fraction) do
    ~MOB"""
    <Box fill_width={true} height={6} corner_radius={3} background={Palette.paper()}>
      <Row fill_width={true}>
        <Box weight={fraction} height={6} corner_radius={3} background={Palette.ink()} />
        <Spacer weight={1.0 - fraction} />
      </Row>
    </Box>
    """
  end

  @doc false
  def filters(list) do
    ~MOB"""
    <Column fill_width={true}>
      <Row fill_width={true} align="center">
        {list.filters
         |> Enum.map(fn {label, on?} -> Kati.Screens.Shopping.filter(label, on?) end)
         |> Enum.intersperse(Kati.Screens.Shopping.filter_gap())}
      </Row>
      <Spacer size={20} />
    </Column>
    """
  end

  @doc false
  def filter_gap, do: ~MOB"<Spacer size={7} />"

  # A Row, not a Box: a chip hugs its label, and a Box would fill the line.
  # The chosen chip carries no shadow in the drawing — ink on paper needs no
  # lift — so the shadow is part of the unchosen recipe only.
  #
  # And NOT `Kati.Components.MishkaChip`, for that same shadow. Everything else
  # these three need is now on the chip: `height: 32` with `padding_y: 0`,
  # `padding_x: 14`, `corner_radius: 16`, `text_size: 12.5`, `font_weight:
  # :semibold`, `max_lines: 1`, and the newly separated `unchecked_color` /
  # `unchecked_text_color` so the two idle chips can be `#FBFAF8` on `#5C574F`
  # instead of the theme's `:surface_raised` on `:on_surface`. `chip/1` builds
  # its Box and then puts `width`, `height`, `align` and `on_tap` on it — there
  # is no `shadow` among them, and no slot that reaches the root node — so an
  # adopted chip would silently drop the lift from the two unchosen ones.
  # Screen 46's filter row is blocked on exactly the same prop.
  @doc false
  def filter(label, true) do
    ~MOB"""
    <Row
      height={32}
      corner_radius={16}
      background={Palette.ink_fill()}
      padding_left={14}
      padding_right={14}
      align="center"
    >
      <Text
        text={label}
        text_size={12.5}
        font_weight="semibold"
        text_color={Palette.on_ink()}
        max_lines={1}
      />
    </Row>
    """
  end

  def filter(label, false) do
    ~MOB"""
    <Row
      height={32}
      corner_radius={16}
      background={Palette.card()}
      shadow={Kati.Theme.shadow_card_soft()}
      padding_left={14}
      padding_right={14}
      align="center"
    >
      <Text
        text={label}
        text_size={12.5}
        font_weight="semibold"
        text_color={Palette.ink_soft()}
        max_lines={1}
      />
    </Row>
    """
  end

  # The aisle eyebrow takes the muted #C4BDB3 dash, not the accent one:
  # Kati.Theme's rule is that orange means new or now, and an aisle is neither.
  @doc false
  def aisle(aisle) do
    last = length(aisle.items) - 1

    rows =
      aisle.items
      |> Enum.with_index()
      |> Enum.map(fn {item, i} -> Kati.Screens.Shopping.item(item, i < last) end)

    ~MOB"""
    <Column fill_width={true}>
      {Kati.UI.SettingsList.eyebrow_muted(aisle.name)}
      {Kati.UI.SettingsList.card(rows)}
      <Spacer size={18} />
    </Column>
    """
  end

  # 12pt rows rather than the settings family's 13 — the drawing's own number,
  # and the one knob SettingsList.row/4 exposes.
  @doc false
  def item(item, rule?) do
    SettingsList.row(
      Kati.Screens.Shopping.tick(item.got),
      Kati.Screens.Shopping.item_body(item),
      Kati.Screens.Shopping.amount(item),
      padding: 12,
      rule: rule?
    )
  end

  @doc false
  def item_body(item) do
    ~MOB"""
    <Column fill_width={true}>
      {Kati.Screens.Shopping.label(item)}
      <Spacer size={3} />
      <Text
        text={item.meals}
        font_family="mono"
        text_size={10}
        text_color={Palette.rail_idle()}
        max_lines={1}
      />
    </Column>
    """
  end

  @doc false
  def amount(item) do
    color = if item.got, do: Palette.rail_idle(), else: Palette.ink_soft()

    ~MOB"""
    <Text text={item.amount} font_family="mono" text_size={11.5} text_color={color} max_lines={1} />
    """
  end

  @doc false
  def tick(true) do
    ~MOB"""
    <Box width={22} height={22} corner_radius={7} background={Palette.ink_fill()} align="center">
      {Kati.UI.symbol("check", size: 14, color: Palette.on_ink())}
    </Box>
    """
  end

  def tick(false) do
    ~MOB"""
    <Box
      width={22}
      height={22}
      corner_radius={7}
      border_width={1.5}
      border_color={Palette.border()}
      align="center"
    />
    """
  end

  @doc false
  def label(%{got: false} = item) do
    ~MOB"""
    <Text
      text={item.name}
      text_size={13.5}
      font_weight="semibold"
      text_color={:on_surface}
      max_lines={1}
    />
    """
  end

  def label(%{got: true} = item) do
    width = Kati.Screens.Shopping.strike_width(item.name)

    ~MOB"""
    <Box fill_width={true} align="leading">
      <Text
        text={item.name}
        text_size={13.5}
        font_weight="semibold"
        text_color={Palette.tertiary()}
        max_lines={1}
      />
      <Box width={width} height={1} background={Palette.tertiary()} />
    </Box>
    """
  end

  @doc """
  How wide to draw a struck line, in dp.

  Declared, never measured — Compose reports no geometry back to `render/1`.
  6.6 per character undershoots Plus Jakarta Sans SemiBold at 13.5pt for
  ordinary lower-case copy, which is the safe direction to be wrong in.
  """
  @spec strike_width(String.t()) :: non_neg_integer()
  def strike_width(label), do: round(String.length(label) * 6.6)

  @doc false
  def actions do
    ~MOB"""
    <Row fill_width={true} align="center">
      <Box weight={1.0}>
        <Box
          fill_width={true}
          height={50}
          corner_radius={25}
          background={Palette.ink_fill()}
          align="center"
        >
          <Row align="center">
            {Kati.UI.symbol("ios_share", size: 18, color: Palette.on_ink())}
            <Spacer size={8} />
            <Text
              text="Send list"
              text_size={13.5}
              font_weight="bold"
              text_color={Palette.on_ink()}
              max_lines={1}
            />
          </Row>
        </Box>
      </Box>
      <Spacer size={10} />
      {Kati.Screens.Shopping.add_button()}
    </Row>
    """
  end

  # `Kati.Components.MishkaActionIcon` — an icon-only button on a raised
  # surface, which is what this is. It could not be one until the component
  # took a `shadow`: a floating disc is defined by its shadow, and `#FBFAF8` on
  # `#EFECE7` paper without one barely reads as a disc at all. The recipe is
  # the drawing's card-soft one, handed to the container as a string; the
  # component does not interpret it.
  #
  # `shape: :circle` computes 50 / 2 = 25.0, the radius written here before,
  # and `variant: :filled` paints `background` and stops. The glyph is a child
  # rather than `icon:`, because Kati's icons are Material Symbols through
  # `Kati.UI.symbol/2` — a `Text` in the `symbols` family — and a child is
  # wrapped in a `<Row>` that hugs it, inside a Box that already centred it.
  # No handler is passed, so none is wired, exactly as before.
  @doc false
  def add_button do
    MishkaActionIcon.action_icon(
      [
        size: 50,
        shape: :circle,
        variant: :filled,
        background: Palette.card(),
        shadow: Kati.Theme.shadow_card_soft()
      ],
      [Kati.UI.symbol("add", size: 21)]
    )
  end
end
