defmodule Kati.Screens.Shopping do
  @moduledoc """
  Screen 48 — Shopping, pushed under Meals.

  Built to `.scratch/design/screens/48.html`. The list is generated by summing
  the week's ingredients and grouping them by aisle, and every line carries the
  meals that asked for it — `7 meals`, `4 dinners`, `snack ×7` — so cutting a
  meal visibly shrinks the list. That sub-line is the screen's whole argument,
  which is why the copy is the design's rather than invented.

  Three groupings sit above it as chips ("By aisle" chosen), and a basket card
  states progress in words as well as in a bar: `9 of 24 in the basket`. The
  bar alone would be colour carrying meaning on its own, which screen 41 rules
  out.

  The aisle groups are `Kati.UI.SettingsList`'s card and row — the same
  `#FBFAF8` at radius 20, the same `4px 15px`, the same hairline the last row
  does not get — with a tick box in the leading slot instead of the 30pt icon
  tile. What is bespoke here is bespoke in the drawing too: the checkbox, the
  mono sub-line at `#C4BDB3`, and the amount in the trailing slot.

  No dock, so the frame's bottom inset is 40 rather than 132.

  ## Where the data comes from

  `Kati.Meals`, through `list/1`: the active plan's `Kati.Meals.ShoppingListItem`
  rows for the week today falls in, grouped into aisles in
  `Kati.Meals.Aisle`'s shopping order. The basket line and the bar count those
  rows, and the estimate is the sum of the lines that carry a price — silent
  when none does, which is the resource's own rule about inventing totals. With
  no active plan, or no list generated for the week, the screen falls back to
  `Kati.Meals.SampleShopping`.

  The three grouping chips are a control with nothing behind them: no column
  records which one is chosen, and no tap has ever changed one.

  ## The struck line

  The design greys a bought item and strikes it through. The bridge's `Text`
  has no text-decoration prop and nothing measures text, so the strike is a
  hairline of **declared** width drawn over the label inside a `Box` — the same
  crude-but-honest trick `Kati.UI.chip/2` uses for its own width. It
  deliberately undershoots, because a strike that stops inside the word reads
  as a strike, and one that overshoots reads as a layout bug.
  """
  use Kati.Screens.Pushed, back: "Meals"

  alias Kati.Components.MishkaActionIcon
  alias Kati.Meals.Aisle
  alias Kati.Meals.SampleShopping
  alias Kati.Meals.ShoppingListItem
  alias Kati.Theme.Palette
  alias Kati.UI.SettingsList

  @impl true
  def load(socket), do: Mob.Socket.assign(socket, :list, list(Kati.Time.today()))

  @doc """
  The week's list: the active plan's own, or the drawing's.

  A device with no plan has no list to roll up, and a rolled-up list with no
  lines would draw a card with nothing in it, a basket line reading `0 of 0`
  and an empty progress bar where the design draws nine items over three
  aisles. FIDELITY's rule applies — *missing data is not a reason for a blank
  screen* — so the drawn list stands in, exactly as `Kati.Screens.Calendar`
  falls back to its drawn day.

  One gate for the whole screen rather than a fallback per block: a subtitle
  counting the user's real items over a card showing the drawing's would be
  worse than either.
  """
  @spec list(Date.t()) :: map()
  def list(date) do
    monday = Date.add(date, -(Date.day_of_week(date) - 1))

    with plan when not is_nil(plan) <- active_plan(),
         [_ | _] = items <- week_items(plan, monday) do
      shopping_list(items, monday)
    else
      _ -> SampleShopping.list()
    end
  end

  defp shopping_list(items, monday) do
    count = length(items)
    got = Enum.count(items, & &1.got)

    %{
      subtitle: "week of #{Calendar.strftime(monday, "%-d %b")} · #{plural(count, "item")}",
      basket: "#{got} of #{count} in the basket",
      estimate: estimate(items),
      progress: got / count,
      # The three groupings are a control, not data: nothing in
      # `Kati.Meals.ShoppingListItem` records which chip is chosen, and the
      # screen has never wired one. They stay the drawing's until there is a
      # place to keep the choice.
      filters: SampleShopping.filters(),
      aisles: aisles(items)
    }
  end

  # In the shop's own order — `Kati.Meals.Aisle.values/0` is walked rather than
  # sorted, because the aisle column sorts alphabetically and a list grouped
  # alphabetically stops reading as a route. An aisle with nothing in it is not
  # drawn at all.
  defp aisles(items) do
    grouped = Enum.group_by(items, & &1.aisle)

    Aisle.values()
    |> Enum.filter(&Map.has_key?(grouped, &1))
    |> Enum.map(fn aisle ->
      %{
        name: Aisle.label(aisle),
        items: grouped |> Map.fetch!(aisle) |> Enum.map(&item_row/1)
      }
    end)
  end

  defp item_row(item) do
    %{name: item.name, meals: meals_label(item), amount: amount_line(item), got: item.got}
  end

  # The label is stored because the phrasing varies with what the meals have in
  # common — `7 meals`, `4 dinners`, `snack ×7` — and only the plainest of those
  # can be recovered from a count. A line the user added by hand has no meals
  # asking for it and says nothing rather than `0 meals`.
  defp meals_label(%{meals_label: label}) when is_binary(label) and label != "", do: label
  defp meals_label(%{meal_count: 0}), do: ""
  defp meals_label(%{meal_count: count}), do: plural(count, "meal")

  # `price_source: :none` contributes nothing and invents nothing — the
  # resource's own rule. A week where no line carries a price therefore states
  # no total at all, rather than an estimate built out of the few that do.
  defp estimate(items) do
    case Enum.filter(items, &(&1.price_source != :none and &1.price_minor)) do
      [] ->
        ""

      [first | _] = priced ->
        # Only the lines in the same currency as the first are added up. A
        # remembered price carries the currency it was paid in, and a list
        # holding two of them has no single total — adding the minor units
        # would print one anyway, which is the failure worth ten lines of
        # arithmetic to avoid.
        same = Enum.filter(priced, &(&1.price_currency == first.price_currency))

        "#{symbol(first.price_currency)}#{money(same)} est."
    end
  end

  defp money(priced) do
    minor = Enum.reduce(priced, 0, &(&1.price_minor + &2))
    :erlang.float_to_binary(minor / 100, decimals: 2)
  end

  defp symbol("GBP"), do: "£"
  defp symbol("EUR"), do: "€"
  defp symbol("USD"), do: "$"
  defp symbol(nil), do: ""
  defp symbol(code), do: code <> " "

  # Thousandths of the unit, back into the shop's own words. `:piece` is the
  # drawing's `×7`; grams and millilitres climb to kg and l on the thousand so
  # a kilo of rice does not read as `1000 g`.
  defp amount_line(%{unit: :piece, amount_mg: amount}), do: "×#{div(amount, 1000)}"
  defp amount_line(%{unit: :g, amount_mg: amount}), do: scaled(div(amount, 1000), "g", "kg")
  defp amount_line(%{unit: :ml, amount_mg: amount}), do: scaled(div(amount, 1000), "ml", "l")

  defp amount_line(%{unit: unit, amount_mg: amount}) do
    count = div(amount, 1000)
    {one, many} = unit_words(unit)
    if count == 1, do: "1 #{one}", else: "#{count} #{many}"
  end

  defp scaled(amount, small, large) do
    if amount >= 1000 and rem(amount, 1000) == 0,
      do: "#{div(amount, 1000)} #{large}",
      else: "#{amount} #{small}"
  end

  defp unit_words(:tub), do: {"tub", "tubs"}
  defp unit_words(:pack), do: {"pack", "packs"}
  defp unit_words(:pinch), do: {"pinch", "pinches"}
  defp unit_words(unit), do: {Atom.to_string(unit), Atom.to_string(unit)}

  defp plural(1, word), do: "1 #{word}"
  defp plural(count, word), do: "#{count} #{word}s"

  defp active_plan do
    case Kati.Meals.MealPlan |> Ash.Query.for_read(:active) |> Ash.read_one() do
      {:ok, plan} -> plan
      _ -> nil
    end
  rescue
    _ -> nil
  end

  defp week_items(plan, monday) do
    ShoppingListItem
    |> Ash.Query.for_read(:for_week, %{meal_plan_id: plan.id, week_starting_on: monday})
    |> Ash.read!()
  rescue
    _ -> []
  end

  @doc false
  def content(assigns) do
    list = assigns.list

    ~MOB"""
    <Scroll>
      <Column
        fill_width={true}
        padding_left={21}
        padding_right={21}
        padding_top={64}
        padding_bottom={40}
      >
        {SettingsList.chrome("more_horiz")}
        {SettingsList.title("Shopping", list.subtitle, nil, :meta_tight)}
        {Kati.Screens.Shopping.basket(list)}
        {Kati.Screens.Shopping.filters(list)}
        {Enum.map(list.aisles, fn aisle -> Kati.Screens.Shopping.aisle(aisle) end)}
        {Kati.Screens.Shopping.actions()}
      </Column>
    </Scroll>
    """
  end

  @doc false
  def basket(list) do
    ~MOB"""
    <Column fill_width={true}>
      <Column
        fill_width={true}
        background={Palette.card()}
        corner_radius={20}
        shadow={Kati.Theme.shadow_card_soft()}
        padding={15}
      >
        <Row fill_width={true} align="center">
          <Text
            text={list.basket}
            text_size={13.5}
            font_weight="bold"
            text_color={:on_surface}
            max_lines={1}
          />
          <Spacer weight={1.0} />
          <Text
            text={list.estimate}
            font_family="mono"
            text_size={11.5}
            text_color={Palette.ink_soft()}
            max_lines={1}
          />
        </Row>
        <Spacer size={12} />
        {Kati.Screens.Shopping.progress(list.progress)}
      </Column>
      <Spacer size={18} />
    </Column>
    """
  end

  # Two weighted children inside a filled track, not a child of declared width:
  # nothing reports the track's pixel width back, so the fraction has to be
  # expressed as weight or it cannot be expressed at all.
  #
  # An empty basket draws the track and nothing else. `weight` is a share of
  # what is left over after the fixed children, and a share of zero is not a
  # zero-width child — it is a child Compose is asked to give none of a
  # remainder to, which is not the same question. The drawing never asks it
  # (9 of 24 is 0.38), and a real Monday morning asks it every week.
  @doc false
  def progress(fraction) when fraction == 0 do
    ~MOB"""
    <Box fill_width={true} height={6} corner_radius={3} background={Palette.paper()} />
    """
  end

  def progress(fraction) do
    ~MOB"""
    <Box fill_width={true} height={6} corner_radius={3} background={Palette.paper()}>
      <Row fill_width={true}>
        <Box weight={fraction} height={6} corner_radius={3} background={Palette.ink()} />
        <Spacer weight={1.0 - fraction} />
      </Row>
    </Box>
    """
  end

  @doc false
  def filters(list) do
    ~MOB"""
    <Column fill_width={true}>
      <Row fill_width={true} align="center">
        {list.filters
         |> Enum.map(fn {label, on?} -> Kati.Screens.Shopping.filter(label, on?) end)
         |> Enum.intersperse(Kati.Screens.Shopping.filter_gap())}
      </Row>
      <Spacer size={20} />
    </Column>
    """
  end

  @doc false
  def filter_gap, do: ~MOB"<Spacer size={7} />"

  # A Row, not a Box: a chip hugs its label, and a Box would fill the line.
  # The chosen chip carries no shadow in the drawing — ink on paper needs no
  # lift — so the shadow is part of the unchosen recipe only.
  #
  # And NOT `Kati.Components.MishkaChip`, for that same shadow. Everything else
  # these three need is now on the chip: `height: 32` with `padding_y: 0`,
  # `padding_x: 14`, `corner_radius: 16`, `text_size: 12.5`, `font_weight:
  # :semibold`, `max_lines: 1`, and the newly separated `unchecked_color` /
  # `unchecked_text_color` so the two idle chips can be `#FBFAF8` on `#5C574F`
  # instead of the theme's `:surface_raised` on `:on_surface`. `chip/1` builds
  # its Box and then puts `width`, `height`, `align` and `on_tap` on it — there
  # is no `shadow` among them, and no slot that reaches the root node — so an
  # adopted chip would silently drop the lift from the two unchosen ones.
  # Screen 46's filter row is blocked on exactly the same prop.
  @doc false
  def filter(label, true) do
    ~MOB"""
    <Row
      height={32}
      corner_radius={16}
      background={Palette.ink_fill()}
      padding_left={14}
      padding_right={14}
      align="center"
    >
      <Text
        text={label}
        text_size={12.5}
        font_weight="semibold"
        text_color={Palette.on_ink()}
        max_lines={1}
      />
    </Row>
    """
  end

  def filter(label, false) do
    ~MOB"""
    <Row
      height={32}
      corner_radius={16}
      background={Palette.card()}
      shadow={Kati.Theme.shadow_card_soft()}
      padding_left={14}
      padding_right={14}
      align="center"
    >
      <Text
        text={label}
        text_size={12.5}
        font_weight="semibold"
        text_color={Palette.ink_soft()}
        max_lines={1}
      />
    </Row>
    """
  end

  # The aisle eyebrow takes the muted #C4BDB3 dash, not the accent one:
  # Kati.Theme's rule is that orange means new or now, and an aisle is neither.
  @doc false
  def aisle(aisle) do
    last = length(aisle.items) - 1

    rows =
      aisle.items
      |> Enum.with_index()
      |> Enum.map(fn {item, i} -> Kati.Screens.Shopping.item(item, i < last) end)

    ~MOB"""
    <Column fill_width={true}>
      {Kati.UI.SettingsList.eyebrow_muted(aisle.name)}
      {Kati.UI.SettingsList.card(rows)}
      <Spacer size={18} />
    </Column>
    """
  end

  # 12pt rows rather than the settings family's 13 — the drawing's own number,
  # and the one knob SettingsList.row/4 exposes.
  @doc false
  def item(item, rule?) do
    SettingsList.row(
      Kati.Screens.Shopping.tick(item.got),
      Kati.Screens.Shopping.item_body(item),
      Kati.Screens.Shopping.amount(item),
      padding: 12,
      rule: rule?
    )
  end

  @doc false
  def item_body(item) do
    ~MOB"""
    <Column fill_width={true}>
      {Kati.Screens.Shopping.label(item)}
      <Spacer size={3} />
      <Text
        text={item.meals}
        font_family="mono"
        text_size={10}
        text_color={Palette.rail_idle()}
        max_lines={1}
      />
    </Column>
    """
  end

  @doc false
  def amount(item) do
    color = if item.got, do: Palette.rail_idle(), else: Palette.ink_soft()

    ~MOB"""
    <Text text={item.amount} font_family="mono" text_size={11.5} text_color={color} max_lines={1} />
    """
  end

  @doc false
  def tick(true) do
    ~MOB"""
    <Box width={22} height={22} corner_radius={7} background={Palette.ink_fill()} align="center">
      {Kati.UI.symbol("check", size: 14, color: Palette.on_ink())}
    </Box>
    """
  end

  def tick(false) do
    ~MOB"""
    <Box
      width={22}
      height={22}
      corner_radius={7}
      border_width={1.5}
      border_color={Palette.border()}
      align="center"
    />
    """
  end

  @doc false
  def label(%{got: false} = item) do
    ~MOB"""
    <Text
      text={item.name}
      text_size={13.5}
      font_weight="semibold"
      text_color={:on_surface}
      max_lines={1}
    />
    """
  end

  def label(%{got: true} = item) do
    width = Kati.Screens.Shopping.strike_width(item.name)

    ~MOB"""
    <Box fill_width={true} align="leading">
      <Text
        text={item.name}
        text_size={13.5}
        font_weight="semibold"
        text_color={Palette.tertiary()}
        max_lines={1}
      />
      <Box width={width} height={1} background={Palette.tertiary()} />
    </Box>
    """
  end

  @doc """
  How wide to draw a struck line, in dp.

  Declared, never measured — Compose reports no geometry back to `render/1`.
  6.6 per character undershoots Plus Jakarta Sans SemiBold at 13.5pt for
  ordinary lower-case copy, which is the safe direction to be wrong in.
  """
  @spec strike_width(String.t()) :: non_neg_integer()
  def strike_width(label), do: round(String.length(label) * 6.6)

  @doc false
  def actions do
    ~MOB"""
    <Row fill_width={true} align="center">
      <Box weight={1.0}>
        <Box
          fill_width={true}
          height={50}
          corner_radius={25}
          background={Palette.ink_fill()}
          align="center"
        >
          <Row align="center">
            {Kati.UI.symbol("ios_share", size: 18, color: Palette.on_ink())}
            <Spacer size={8} />
            <Text
              text="Send list"
              text_size={13.5}
              font_weight="bold"
              text_color={Palette.on_ink()}
              max_lines={1}
            />
          </Row>
        </Box>
      </Box>
      <Spacer size={10} />
      {Kati.Screens.Shopping.add_button()}
    </Row>
    """
  end

  # `Kati.Components.MishkaActionIcon` — an icon-only button on a raised
  # surface, which is what this is. It could not be one until the component
  # took a `shadow`: a floating disc is defined by its shadow, and `#FBFAF8` on
  # `#EFECE7` paper without one barely reads as a disc at all. The recipe is
  # the drawing's card-soft one, handed to the container as a string; the
  # component does not interpret it.
  #
  # `shape: :circle` computes 50 / 2 = 25.0, the radius written here before,
  # and `variant: :filled` paints `background` and stops. The glyph is a child
  # rather than `icon:`, because Kati's icons are Material Symbols through
  # `Kati.UI.symbol/2` — a `Text` in the `symbols` family — and a child is
  # wrapped in a `<Row>` that hugs it, inside a Box that already centred it.
  # No handler is passed, so none is wired, exactly as before.
  @doc false
  def add_button do
    MishkaActionIcon.action_icon(
      [
        size: 50,
        shape: :circle,
        variant: :filled,
        background: Palette.card(),
        shadow: Kati.Theme.shadow_card_soft()
      ],
      [Kati.UI.symbol("add", size: 21)]
    )
  end
end
