// beam_jni.c — JNI entry points for Kati.
// Generated by mix mob.new. Edit the two defines below; do not touch the rest.

#include <jni.h>
#include "mob_beam.h"

#define BRIDGE_CLASS  "com/example/kati/MobBridge"
#define APP_MODULE    "kati"

JavaVM* g_jvm      = NULL;
jobject g_activity = NULL;

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    JNIEnv* env;
    (*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6);
    mob_ui_cache_class(env, BRIDGE_CLASS);
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_example_kati_MainActivity_nativeSetActivity(JNIEnv* env, jobject thiz, jobject activity) {
    mob_init_bridge(env, activity);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MainActivity_nativeStartBeam(JNIEnv* env, jobject thiz) {
    mob_start_beam(APP_MODULE);
}

// Called from MobBridge.nativeSendTap(handle) in Kotlin when a button is tapped.
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendTap(JNIEnv* env, jclass cls, jint handle) {
    mob_send_tap((int)handle);
}

// Called from MobBridge.nativeSendChangeStr/Bool/Float when an input widget changes.
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendChangeStr(JNIEnv* env, jclass cls, jint handle, jstring value) {
    const char* utf8 = (*env)->GetStringUTFChars(env, value, NULL);
    mob_send_change_str((int)handle, utf8);
    (*env)->ReleaseStringUTFChars(env, value, utf8);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendChangeBool(JNIEnv* env, jclass cls, jint handle, jboolean value) {
    mob_send_change_bool((int)handle, (int)value);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendChangeFloat(JNIEnv* env, jclass cls, jint handle, jfloat value) {
    mob_send_change_float((int)handle, (double)value);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendFocus(JNIEnv* env, jclass cls, jint handle) {
    mob_send_focus((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendBlur(JNIEnv* env, jclass cls, jint handle) {
    mob_send_blur((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendSubmit(JNIEnv* env, jclass cls, jint handle) {
    mob_send_submit((int)handle);
}

// Called from MobBridge.nativeHandleBack() when the Android back gesture fires.
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeHandleBack(JNIEnv* env, jclass cls) {
    mob_handle_back();
}

// Called from MobBridge.notifyColorSchemeChanged when MainActivity's
// onConfigurationChanged sees a uiMode flip. `scheme` is "light" or "dark".
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeNotifyColorScheme(JNIEnv* env, jclass cls,
    jstring scheme) {
    if (!scheme) return;
    const char* utf8 = (*env)->GetStringUTFChars(env, scheme, NULL);
    if (utf8) {
        mob_send_color_scheme_changed(utf8);
        (*env)->ReleaseStringUTFChars(env, scheme, utf8);
    }
}

// ── Device capability result delivery ────────────────────────────────────
// Called from MobBridge when async results are ready.

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverAtom2(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    mob_deliver_atom2(pid, ca1, ca2);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverAtom3(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2, jstring a3) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    const char* ca3 = (*env)->GetStringUTFChars(env, a3, NULL);
    mob_deliver_atom3(pid, ca1, ca2, ca3);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
    (*env)->ReleaseStringUTFChars(env, a3, ca3);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverLocation(JNIEnv* env, jclass cls,
    jlong pid, jdouble lat, jdouble lon, jdouble acc, jdouble alt) {
    mob_deliver_location(pid, lat, lon, acc, alt);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverMotion(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz, jlong ts) {
    mob_deliver_motion(pid, ax, ay, az, gx, gy, gz, (long long)ts);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverFileResult(JNIEnv* env, jclass cls,
    jlong pid, jstring event, jstring sub, jstring json_items) {
    const char* ce  = (*env)->GetStringUTFChars(env, event, NULL);
    const char* cs  = (*env)->GetStringUTFChars(env, sub,   NULL);
    const char* cj  = json_items ? (*env)->GetStringUTFChars(env, json_items, NULL) : NULL;
    mob_deliver_file_result(pid, ce, cs, cj);
    (*env)->ReleaseStringUTFChars(env, event, ce);
    (*env)->ReleaseStringUTFChars(env, sub,   cs);
    if (cj) (*env)->ReleaseStringUTFChars(env, json_items, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverCameraFrame(JNIEnv* env, jclass cls,
    jlong pid, jbyteArray bytes, jint width, jint height, jstring format,
    jlong timestamp_ms, jlong dropped) {
    if (!bytes) return;
    // Resolve every other JNI handle BEFORE entering the critical
    // section. JNI's rule: between Get/ReleasePrimitiveArrayCritical
    // you can call neither another JNI method nor any blocking native
    // code (CheckJNI catches this and SIGABRTs with "using JNI after
    // critical get"). The mob_deliver_camera_frame call itself only
    // does memcpy + BEAM-owned allocs, so it's safe.
    jsize n = (*env)->GetArrayLength(env, bytes);
    const char* fmt = format ? (*env)->GetStringUTFChars(env, format, NULL) : NULL;
    const char* fmt_use = fmt ? fmt : "rgb_f32";

    void* raw = (*env)->GetPrimitiveArrayCritical(env, bytes, NULL);
    if (raw) {
        mob_deliver_camera_frame(pid, (const unsigned char*)raw, (size_t)n,
                                 (int)width, (int)height, fmt_use,
                                 timestamp_ms, dropped);
        (*env)->ReleasePrimitiveArrayCritical(env, bytes, raw, JNI_ABORT);
    }

    if (fmt) (*env)->ReleaseStringUTFChars(env, format, fmt);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverPushToken(JNIEnv* env, jclass cls,
    jlong pid, jstring token) {
    const char* ct = (*env)->GetStringUTFChars(env, token, NULL);
    mob_deliver_push_token(pid, ct);
    (*env)->ReleaseStringUTFChars(env, token, ct);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverNotification(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_notification(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSetLaunchNotification(JNIEnv* env, jclass cls,
    jstring json) {
    if (!json) { mob_set_launch_notification(NULL); return; }
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_set_launch_notification(cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverWebViewMessage(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_webview_message(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverWebViewBlocked(JNIEnv* env, jclass cls,
    jlong pid, jstring url) {
    const char* cu = (*env)->GetStringUTFChars(env, url, NULL);
    mob_deliver_webview_blocked(pid, cu);
    (*env)->ReleaseStringUTFChars(env, url, cu);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverAlertAction(JNIEnv* env, jclass cls,
    jstring action) {
    const char* ca = (*env)->GetStringUTFChars(env, action, NULL);
    mob_deliver_alert_action(ca);
    (*env)->ReleaseStringUTFChars(env, action, ca);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverComponentEvent(JNIEnv* env, jclass cls,
    jint handle, jstring event, jstring payload_json) {
    const char* ce = (*env)->GetStringUTFChars(env, event,        NULL);
    const char* cj = (*env)->GetStringUTFChars(env, payload_json, NULL);
    mob_send_component_event((int)handle, ce, cj);
    (*env)->ReleaseStringUTFChars(env, event,        ce);
    (*env)->ReleaseStringUTFChars(env, payload_json, cj);
}

// ── Mob.Peripheral.VendorUsb delivery thunks ─────────────────────────────────
// Called from MobBridge's USB code when Android USB host events fire.
// See lib/mob/peripheral/vendor_usb.ex for the public message envelope shape.

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbDevices(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_vendor_usb_devices(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbPermission(JNIEnv* env, jclass cls,
    jlong pid, jboolean granted, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_permission(pid, granted ? 1 : 0, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbOpened(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_opened(pid, (int)session_id, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbData(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jbyteArray bytes, jint len) {
    if (!bytes || len <= 0) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, NULL, 0);
        return;
    }
    jbyte* buf = (*env)->GetByteArrayElements(env, bytes, NULL);
    if (buf) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, (const uint8_t*)buf, (size_t)len);
        (*env)->ReleaseByteArrayElements(env, bytes, buf, JNI_ABORT);
    }
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbWriteComplete(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jint bytes_written) {
    mob_deliver_vendor_usb_write_complete(pid, (int)session_id, (int)bytes_written);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbEvent(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring tag, jstring reason) {
    const char* ct = (*env)->GetStringUTFChars(env, tag, NULL);
    const char* cr = reason ? (*env)->GetStringUTFChars(env, reason, NULL) : NULL;
    mob_deliver_vendor_usb_event(pid, (int)session_id, ct, cr);
    (*env)->ReleaseStringUTFChars(env, tag, ct);
    if (cr) (*env)->ReleaseStringUTFChars(env, reason, cr);
}

// ── Bluetooth Classic (Mob.Bt suite) — JNI thunks ───────────────────────
// Each thunk unmarshals Java args into C primitives, calls the matching
// mob_deliver_bt_* helper, then releases.

// ── Adapter-level events (no session) ──────────────────────────────────

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtDiscoveryStarted(JNIEnv* env, jclass cls,
    jlong pid) {
    mob_deliver_bt_discovery_started(pid);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtDiscoveryFinished(JNIEnv* env, jclass cls,
    jlong pid) {
    mob_deliver_bt_discovery_finished(pid);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtDiscoveryCancelled(JNIEnv* env, jclass cls,
    jlong pid) {
    mob_deliver_bt_discovery_cancelled(pid);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtDiscovered(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring name, jboolean bonded) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_name    = (*env)->GetStringUTFChars(env, name,    NULL);
    mob_deliver_bt_discovered(pid, c_address, c_name, bonded ? 1 : 0);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, name,    c_name);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtPaired(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring name, jboolean bonded) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_name    = (*env)->GetStringUTFChars(env, name,    NULL);
    mob_deliver_bt_paired(pid, c_address, c_name, bonded ? 1 : 0);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, name,    c_name);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtPairFailed(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring reason) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_reason  = (*env)->GetStringUTFChars(env, reason,  NULL);
    mob_deliver_bt_pair_failed(pid, c_address, c_reason);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, reason,  c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtUnpaired(JNIEnv* env, jclass cls,
    jlong pid, jstring address) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    mob_deliver_bt_unpaired(pid, c_address);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtError(JNIEnv* env, jclass cls,
    jlong pid, jstring reason) {
    const char* c_reason = (*env)->GetStringUTFChars(env, reason, NULL);
    mob_deliver_bt_error(pid, c_reason);
    (*env)->ReleaseStringUTFChars(env, reason, c_reason);
}

// ── Paired-list streaming builder ──────────────────────────────────────

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtPairedListBegin(JNIEnv* env, jclass cls,
    jlong pid) {
    mob_deliver_bt_paired_list_begin(pid);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtPairedListEntry(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring name, jboolean bonded) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_name    = (*env)->GetStringUTFChars(env, name,    NULL);
    mob_deliver_bt_paired_list_entry(pid, c_address, c_name, bonded ? 1 : 0);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, name,    c_name);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtPairedListFinish(JNIEnv* env, jclass cls,
    jlong pid) {
    mob_deliver_bt_paired_list_finish(pid);
}

// ── HFP profile ────────────────────────────────────────────────────────

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpConnecting(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring address) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    mob_deliver_bt_hfp_connecting(pid, (int)session, c_address);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpConnected(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring address, jstring name) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_name    = (*env)->GetStringUTFChars(env, name,    NULL);
    mob_deliver_bt_hfp_connected(pid, (int)session, c_address, c_name);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, name,    c_name);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpConnectFailed(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring reason) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_reason  = (*env)->GetStringUTFChars(env, reason,  NULL);
    mob_deliver_bt_hfp_connect_failed(pid, c_address, c_reason);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, reason,  c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpDisconnected(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring reason) {
    const char* c_reason = (*env)->GetStringUTFChars(env, reason, NULL);
    mob_deliver_bt_hfp_disconnected(pid, (int)session, c_reason);
    (*env)->ReleaseStringUTFChars(env, reason, c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpVendorSubscribed(JNIEnv* env, jclass cls,
    jlong pid, jint session) {
    mob_deliver_bt_hfp_vendor_subscribed(pid, (int)session);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpVendorAt(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring cmd, jint cmd_type, jstring args, jstring address) {
    const char* c_cmd     = (*env)->GetStringUTFChars(env, cmd,     NULL);
    const char* c_args    = (*env)->GetStringUTFChars(env, args,    NULL);
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    mob_deliver_bt_hfp_vendor_at(pid, (int)session, c_cmd, (int)cmd_type, c_args, c_address);
    (*env)->ReleaseStringUTFChars(env, cmd,     c_cmd);
    (*env)->ReleaseStringUTFChars(env, args,    c_args);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpScoStarted(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring address) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    mob_deliver_bt_hfp_sco_started(pid, (int)session, c_address);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpScoStopped(JNIEnv* env, jclass cls,
    jlong pid, jint session) {
    mob_deliver_bt_hfp_sco_stopped(pid, (int)session);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpScoAudio(JNIEnv* env, jclass cls,
    jlong pid, jint session, jbyteArray pcm) {
    jsize len = (*env)->GetArrayLength(env, pcm);
    jbyte* buf = (*env)->GetByteArrayElements(env, pcm, NULL);
    mob_deliver_bt_hfp_sco_audio(pid, (int)session, (const char*)buf, (size_t)len);
    (*env)->ReleaseByteArrayElements(env, pcm, buf, JNI_ABORT);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHfpError(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring reason) {
    const char* c_reason = (*env)->GetStringUTFChars(env, reason, NULL);
    mob_deliver_bt_hfp_error(pid, (int)session, c_reason);
    (*env)->ReleaseStringUTFChars(env, reason, c_reason);
}

// ── SPP profile ────────────────────────────────────────────────────────

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtSppConnected(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring address, jstring name) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_name    = (*env)->GetStringUTFChars(env, name,    NULL);
    mob_deliver_bt_spp_connected(pid, (int)session, c_address, c_name);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, name,    c_name);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtSppConnectFailed(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring reason) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_reason  = (*env)->GetStringUTFChars(env, reason,  NULL);
    mob_deliver_bt_spp_connect_failed(pid, c_address, c_reason);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, reason,  c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtSppDisconnected(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring reason) {
    const char* c_reason = (*env)->GetStringUTFChars(env, reason, NULL);
    mob_deliver_bt_spp_disconnected(pid, (int)session, c_reason);
    (*env)->ReleaseStringUTFChars(env, reason, c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtSppData(JNIEnv* env, jclass cls,
    jlong pid, jint session, jbyteArray data) {
    jsize len = (*env)->GetArrayLength(env, data);
    jbyte* buf = (*env)->GetByteArrayElements(env, data, NULL);
    mob_deliver_bt_spp_data(pid, (int)session, (const char*)buf, (size_t)len);
    (*env)->ReleaseByteArrayElements(env, data, buf, JNI_ABORT);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtSppWritten(JNIEnv* env, jclass cls,
    jlong pid, jint session, jint size) {
    mob_deliver_bt_spp_written(pid, (int)session, (int)size);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtSppError(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring reason) {
    const char* c_reason = (*env)->GetStringUTFChars(env, reason, NULL);
    mob_deliver_bt_spp_error(pid, (int)session, c_reason);
    (*env)->ReleaseStringUTFChars(env, reason, c_reason);
}

// ── HID profile ────────────────────────────────────────────────────────

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHidConnected(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring address) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    mob_deliver_bt_hid_connected(pid, (int)session, c_address);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHidConnectFailed(JNIEnv* env, jclass cls,
    jlong pid, jstring address, jstring reason) {
    const char* c_address = (*env)->GetStringUTFChars(env, address, NULL);
    const char* c_reason  = (*env)->GetStringUTFChars(env, reason,  NULL);
    mob_deliver_bt_hid_connect_failed(pid, c_address, c_reason);
    (*env)->ReleaseStringUTFChars(env, address, c_address);
    (*env)->ReleaseStringUTFChars(env, reason,  c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHidDisconnected(JNIEnv* env, jclass cls,
    jlong pid, jint session, jstring reason) {
    const char* c_reason = (*env)->GetStringUTFChars(env, reason, NULL);
    mob_deliver_bt_hid_disconnected(pid, (int)session, c_reason);
    (*env)->ReleaseStringUTFChars(env, reason, c_reason);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHidInput(JNIEnv* env, jclass cls,
    jlong pid, jint session, jint type, jint code, jint value) {
    mob_deliver_bt_hid_input(pid, (int)session, (int)type, (int)code, (int)value);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverBtHidRawReport(JNIEnv* env, jclass cls,
    jlong pid, jint session, jbyteArray report) {
    jsize len = (*env)->GetArrayLength(env, report);
    jbyte* buf = (*env)->GetByteArrayElements(env, report, NULL);
    mob_deliver_bt_hid_raw_report(pid, (int)session, (const char*)buf, (size_t)len);
    (*env)->ReleaseByteArrayElements(env, report, buf, JNI_ABORT);
}

