/*
 * c_src/kati_secure_store.c — the missing link in Kati's credential store.
 *
 * Generated by `mix mob.add_nif kati_secure_store --type c`; the body is
 * Kati's. Statically linked into the app binary alongside libbeam.a (never
 * dlopen'd — see MobDev.StaticNifs), and registered in
 * priv/generated/driver_tab_android.zig as `kati_secure_store_nif_init` so
 * `:erlang.load_nif/2` in Kati.Nifs.KatiSecureStore binds these four functions.
 *
 * THE CHAIN THIS FILE COMPLETES
 *
 *     Kati.SecureStore.get/1
 *       └─ Kati.Nifs.KatiSecureStore.get/1     (this file)
 *            └─ MobBridge.secureStoreGet       K-19 secure-store-bridge
 *                 └─ KatiSecureStore.get       K-19 secure-store
 *                      └─ AES-256-GCM under an AndroidKeyStore key
 *
 * Every function here is a marshalling step and nothing else: no policy, no
 * validation, no key handling. `Kati.SecureStore` owns the key grammar and the
 * size cap; `KatiSecureStore.kt` owns the crypto. This file's only judgement
 * call is that a boundary failure answers `error:<reason>` rather than raising,
 * because the caller is Kati's single screen process and a raise there is a
 * black screen rather than a failed save.
 *
 * WHY NOT `--type zigler` OR A DYNAMIC .so
 *
 * mob_dev links project NIFs statically on both platforms: iOS rejects bundled
 * .dylib files outright, and Android's loader uses RTLD_LOCAL, which hides the
 * `enif_*` symbols from a dlopen'd child. Both force the same answer.
 *
 * ON iOS AND ON THE HOST
 *
 * `#ifdef __ANDROID__` is the whole platform split. Off Android these answer
 * `error:no_native_store`, which `Kati.SecureStore` maps to the reason of the
 * same name — so `available?/0` is honestly false rather than raising, and
 * nothing anywhere falls back to writing a credential in plaintext.
 *
 * Nothing compiles that arm right now: the mob.exs entry is
 * `archs: [:android]`, because `mix mob.add_nif --type c` wires the c_src
 * directory into the Android build only. On iOS the module is therefore never bound at
 * all, its stubs raise `:nif_not_loaded`, and `Kati.SecureStore` reads that
 * as the same `:no_native_store`. Two routes, one honest answer.
 */

#include "kati_jni.h"

#ifdef __ANDROID__

static ERL_NIF_TERM ks_status(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_bridge_call(env, "secureStoreStatus", "()Ljava/lang/String;", NULL, NULL);
}

static ERL_NIF_TERM ks_put(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *key;
    char *value;
    ERL_NIF_TERM reply;

    (void)argc;
    key = kati_take_cstr(env, argv[0]);
    if (key == NULL) return enif_make_badarg(env);

    value = kati_take_cstr(env, argv[1]);
    if (value == NULL) {
        kati_free_cstr(key);
        return enif_make_badarg(env);
    }

    reply = kati_bridge_call(env, "secureStorePut",
                             "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", key,
                             value);

    /* The plaintext never reaches this file — `value` is already base64 of the
     * secret — but it is still key material shaped bytes sitting in a heap
     * block the allocator will hand to something else, so wipe before free. */
    memset(value, 0, strlen(value));
    kati_free_cstr(value);
    kati_free_cstr(key);
    return reply;
}

static ERL_NIF_TERM ks_get(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *key;
    ERL_NIF_TERM reply;

    (void)argc;
    key = kati_take_cstr(env, argv[0]);
    if (key == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call(env, "secureStoreGet", "(Ljava/lang/String;)Ljava/lang/String;", key,
                             NULL);
    kati_free_cstr(key);
    return reply;
}

static ERL_NIF_TERM ks_delete(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *key;
    ERL_NIF_TERM reply;

    (void)argc;
    key = kati_take_cstr(env, argv[0]);
    if (key == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call(env, "secureStoreDelete", "(Ljava/lang/String;)Ljava/lang/String;",
                             key, NULL);
    kati_free_cstr(key);
    return reply;
}

#else /* not Android — iOS and any host build that links this table */

static ERL_NIF_TERM ks_status(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_cstr_binary(env, "error:no_native_store");
}

static ERL_NIF_TERM ks_put(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_cstr_binary(env, "error:no_native_store");
}

static ERL_NIF_TERM ks_get(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_cstr_binary(env, "error:no_native_store");
}

static ERL_NIF_TERM ks_delete(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_cstr_binary(env, "error:no_native_store");
}

#endif /* __ANDROID__ */

static ErlNifFunc nif_funcs[] = {
    {"status", 0, ks_status, 0},
    {"put", 2, ks_put, 0},
    {"get", 1, ks_get, 0},
    {"delete", 1, ks_delete, 0},
};

/* First arg is the BEAM module name the static-NIF table matches against; the
 * init function's SYMBOL name comes from -DSTATIC_ERLANG_NIF_LIBNAME on the
 * compile line, which build.zig and CMakeLists.txt both set from the file
 * name. */
ERL_NIF_INIT(Elixir.Kati.Nifs.KatiSecureStore, nif_funcs, NULL, NULL, NULL, NULL)
