/*
 * c_src/kati_bridge.c — the project-owned NIF table.
 *
 * Generated by `mix mob.add_nif kati_bridge --type c`; the body is Kati's.
 *
 * WHAT BELONGS IN HERE
 *
 * Exactly one thing: a binding for a `MobBridge` static that Kati added and
 * that `:mob_nif` does not expose. Mob's NIF table lives in the hex package
 * (deps/mob/src/mob_nif.erl + deps/mob/android/jni/mob_nif.zig), so a bridge
 * method Kati wrote is dead code until something here calls it. Three features
 * are in that position and they arrive together because they share this one
 * mechanism, not because they are related:
 *
 *   * file transport (#64)      — ACTION_CREATE_DOCUMENT and ACTION_SEND, the
 *                                 only way a backup can leave the device.
 *   * notification arming (#58) — `MobBridge.notify_schedule` has existed since
 *                                 `K-01 notify-persist` and has never been
 *                                 callable, which is why the only delivery
 *                                 backend Kati shipped was the inert one.
 *   * periodic refresh (#58)    — WorkManager enqueue/cancel.
 *
 * The credential store is deliberately NOT here: it has its own NIF
 * (c_src/kati_secure_store.c) so that the file holding the credential path can
 * be read, reviewed and reasoned about on its own.
 *
 * TWO REPLY SHAPES, AND WHY
 *
 *   * synchronous  — the bridge method returns a String and this returns it as
 *     a binary: "ok", "ok:<payload>" or "error:<reason>". Used where the answer
 *     is knowable immediately (arming an alarm, enqueuing work).
 *   * asynchronous — the bridge method takes the caller's pid and returns void;
 *     the answer arrives later through mob's own `mob_deliver_file_result`
 *     hook, as `{:kati_files, sub, items}` or `{:kati_files, :cancelled}`.
 *     Used for anything that puts a system UI in front of the user, because
 *     the user may take a minute or may never come back, and a NIF that blocks
 *     a scheduler thread waiting for a human is not an option.
 *
 * The synchronous return of an asynchronous call says only whether the call
 * reached Kotlin. Confusing the two is how "the share sheet never opened" gets
 * reported as success.
 */

#include "kati_jni.h"

#ifdef __ANDROID__

/*
 * `"ok"` when this NIF is bound AND the bridge class was cached, so callers
 * have a side-effect-free way to ask "is the transport real here?".
 *
 * It has to be its own function. Probing by calling one of the others would
 * either arm something (notify_arm), enqueue something (periodic_ensure), or —
 * worst — put a file dialog in front of the user and deliver a spurious error
 * message to whatever process asked the question.
 */
static ERL_NIF_TERM kb_available(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    if (g_jvm == NULL) return kati_cstr_binary(env, "error:no_jvm");
    if (g_kati_bridge_cls == NULL) return kati_cstr_binary(env, "error:no_bridge");
    return kati_cstr_binary(env, "ok");
}

/* ── #64: getting a file off the device ──────────────────────────────────── */

static ERL_NIF_TERM kb_file_save_as(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *json;
    ERL_NIF_TERM reply;

    (void)argc;
    json = kati_take_cstr(env, argv[0]);
    if (json == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call_pid(env, "katiFileSaveAs", "(JLjava/lang/String;)V", json);
    kati_free_cstr(json);
    return reply;
}

static ERL_NIF_TERM kb_file_share(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *json;
    ERL_NIF_TERM reply;

    (void)argc;
    json = kati_take_cstr(env, argv[0]);
    if (json == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call_pid(env, "katiFileShare", "(JLjava/lang/String;)V", json);
    kati_free_cstr(json);
    return reply;
}

/* ── #58: arming a real alarm ────────────────────────────────────────────── */

static ERL_NIF_TERM kb_notify_arm(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *json;
    ERL_NIF_TERM reply;

    (void)argc;
    json = kati_take_cstr(env, argv[0]);
    if (json == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call(env, "katiNotifyArm", "(Ljava/lang/String;)Ljava/lang/String;", json,
                             NULL);
    kati_free_cstr(json);
    return reply;
}

static ERL_NIF_TERM kb_notify_cancel(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *id;
    ERL_NIF_TERM reply;

    (void)argc;
    id = kati_take_cstr(env, argv[0]);
    if (id == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call(env, "katiNotifyCancel", "(Ljava/lang/String;)Ljava/lang/String;", id,
                             NULL);
    kati_free_cstr(id);
    return reply;
}

static ERL_NIF_TERM kb_notify_status(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_bridge_call(env, "katiNotifyStatus", "()Ljava/lang/String;", NULL, NULL);
}

/* ── #9: reading a permission, which Mob can only request ────────────────── */

static ERL_NIF_TERM kb_permission_status(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *cap;
    ERL_NIF_TERM reply;

    (void)argc;
    cap = kati_take_cstr(env, argv[0]);
    if (cap == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call(env, "katiPermissionStatus", "(Ljava/lang/String;)Ljava/lang/String;",
                             cap, NULL);
    kati_free_cstr(cap);
    return reply;
}

/* ── #58: the periodic refresh worker ────────────────────────────────────── */

static ERL_NIF_TERM kb_periodic_ensure(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    char *json;
    ERL_NIF_TERM reply;

    (void)argc;
    json = kati_take_cstr(env, argv[0]);
    if (json == NULL) return enif_make_badarg(env);

    reply = kati_bridge_call(env, "katiPeriodicEnsure", "(Ljava/lang/String;)Ljava/lang/String;",
                             json, NULL);
    kati_free_cstr(json);
    return reply;
}

static ERL_NIF_TERM kb_periodic_cancel(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kati_bridge_call(env, "katiPeriodicCancel", "()Ljava/lang/String;", NULL, NULL);
}

#else /* not Android */

/*
 * `no_bridge` rather than a silent success: a caller that cannot tell an
 * absent transport from a completed one will tell the user their backup was
 * saved.
 *
 * Nothing compiles this arm today — the mob.exs entry is `archs: [:android]`,
 * because `mix mob.add_nif --type c` wires the c_src directory into the
 * Android build only, so on iOS the module is never bound and its stubs raise
 * `:nif_not_loaded`, which `Kati.Native.Bridge` reads as the same
 * `:no_bridge`. Two routes, one answer.
 *
 * On iOS this is also the accurate answer for two of the three.
 * Background fetch there needs BGTaskScheduler registered inside
 * `didFinishLaunchingWithOptions`, which is a host template edit in
 * deps/mob (not app-owned), and a file leaves the app through
 * UIFileSharingEnabled + LSSupportsOpeningDocumentsInPlace rather than through
 * an intent — see the iOS notes in Kati.Native.Files and #64.
 */

static ERL_NIF_TERM kb_unavailable(ErlNifEnv *env) {
    return kati_cstr_binary(env, "error:no_bridge");
}

static ERL_NIF_TERM kb_available(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_file_save_as(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_file_share(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_notify_arm(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_notify_cancel(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_permission_status(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_notify_status(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_periodic_ensure(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

static ERL_NIF_TERM kb_periodic_cancel(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    (void)argc;
    (void)argv;
    return kb_unavailable(env);
}

#endif /* __ANDROID__ */

static ErlNifFunc nif_funcs[] = {
    {"available", 0, kb_available, 0},
    {"file_save_as", 1, kb_file_save_as, 0},
    {"file_share", 1, kb_file_share, 0},
    {"notify_arm", 1, kb_notify_arm, 0},
    {"notify_cancel", 1, kb_notify_cancel, 0},
    {"notify_status", 0, kb_notify_status, 0},
    {"permission_status", 1, kb_permission_status, 0},
    {"periodic_ensure", 1, kb_periodic_ensure, 0},
    {"periodic_cancel", 0, kb_periodic_cancel, 0},
};

ERL_NIF_INIT(Elixir.Kati.Nifs.KatiBridge, nif_funcs, NULL, NULL, NULL, NULL)
