defmodule Kati.Icons do
  @moduledoc """
  Material Symbols Rounded, by name.

  Generated by `mix kati.gen.icons` from the design in
  `.scratch/design/screens/` — do not edit. 143 icons, which is
  every symbol the 62 screens use.

  Kati ships a **subset**: the full variable font is 15 MB, the subset is
  411 KB, and it keeps all four axes so `FILL 1` still works for the active
  tab. An icon absent here is absent from the font too, which is why
  `glyph!/1` raises rather than rendering a blank box.
  """

  @icons %{
    "add" => "\uE145",
    "analytics" => "\uEF3E",
    "archive" => "\uE149",
    "arrow_back" => "\uE5C4",
    "arrow_back_ios_new" => "\uE2EA",
    "arrow_downward" => "\uE5DB",
    "arrow_drop_up" => "\uE5C7",
    "arrow_forward" => "\uE5C8",
    "arrow_forward_ios" => "\uE5E1",
    "auto_awesome" => "\uE65F",
    "auto_mode" => "\uEC20",
    "bar_chart_4_bars" => "\uF681",
    "bedtime" => "\uF159",
    "block" => "\uF08C",
    "bolt" => "\uEA0B",
    "bookmark" => "\uE8E7",
    "bookmarks" => "\uE98B",
    "calendar_month" => "\uEBCC",
    "calendar_today" => "\uE935",
    "calendar_view_week" => "\uEFE8",
    "call_merge" => "\uE0B3",
    "call_split" => "\uE0B6",
    "cancel" => "\uE888",
    "cast" => "\uE307",
    "celebration" => "\uEA65",
    "check" => "\uE668",
    "check_circle" => "\uF0BE",
    "checklist" => "\uE6B1",
    "chevron_left" => "\uE5CB",
    "chevron_right" => "\uE5CC",
    "close" => "\uE5CD",
    "cloud" => "\uF15C",
    "cloud_done" => "\uE2BF",
    "cloud_off" => "\uE2C1",
    "colorize" => "\uE3B8",
    "computer" => "\uE31E",
    "content_copy" => "\uE14D",
    "contrast" => "\uEB37",
    "delete" => "\uE92E",
    "delete_forever" => "\uE92B",
    "density_medium" => "\uEB9E",
    "description" => "\uE873",
    "dns" => "\uE875",
    "do_not_disturb_on" => "\uF08F",
    "download" => "\uF090",
    "drag_indicator" => "\uE945",
    "edit" => "\uF097",
    "edit_calendar" => "\uE742",
    "edit_note" => "\uE745",
    "error" => "\uF8B6",
    "event" => "\uE878",
    "event_available" => "\uE614",
    "event_busy" => "\uE615",
    "event_repeat" => "\uEB7B",
    "event_upcoming" => "\uF238",
    "expand_more" => "\uE5CF",
    "explore" => "\uE87A",
    "featured_seasonal_and_gifts" => "\uEF91",
    "fitness_center" => "\uEB43",
    "format_bold" => "\uE238",
    "format_italic" => "\uE23F",
    "format_size" => "\uE245",
    "format_textdirection_l_to_r" => "\uE247",
    "graphic_eq" => "\uE1B8",
    "grid_view" => "\uE9B0",
    "group" => "\uEA21",
    "hd" => "\uE052",
    "help" => "\uE8FD",
    "history" => "\uE8B3",
    "home" => "\uE9B2",
    "inbox" => "\uE156",
    "info" => "\uE88E",
    "inventory_2" => "\uE1A1",
    "ios_share" => "\uE6B8",
    "label" => "\uE893",
    "lightbulb" => "\uE90F",
    "link" => "\uE250",
    "live_tv" => "\uE63A",
    "local_fire_department" => "\uEF55",
    "lock" => "\uE899",
    "mail" => "\uE159",
    "medication" => "\uF033",
    "menu_book" => "\uEA19",
    "mic" => "\uE31D",
    "monitor_heart" => "\uEAA2",
    "monitor_weight" => "\uF039",
    "monitoring" => "\uF190",
    "more_horiz" => "\uE5D3",
    "motion_blur" => "\uF0D0",
    "movie" => "\uE684",
    "nights_stay" => "\uF174",
    "notifications" => "\uE7F5",
    "notifications_active" => "\uE7F7",
    "notifications_off" => "\uE7F6",
    "nutrition" => "\uE110",
    "pause_circle" => "\uE1A2",
    "payments" => "\uEF63",
    "percent" => "\uEB58",
    "person" => "\uF0D3",
    "phone_iphone" => "\uF2DA",
    "photo_camera" => "\uE412",
    "picture_as_pdf" => "\uE415",
    "pin" => "\uF045",
    "place" => "\uF1DB",
    "play_arrow" => "\uE037",
    "play_circle" => "\uE1C4",
    "playlist_play" => "\uE05F",
    "public" => "\uE80B",
    "qr_code_scanner" => "\uF206",
    "radio_button_unchecked" => "\uE836",
    "record_voice_over" => "\uE91F",
    "remove" => "\uE15B",
    "repeat" => "\uE040",
    "replay" => "\uE042",
    "restaurant" => "\uE56C",
    "schedule" => "\uEFD6",
    "search" => "\uEF7A",
    "sell" => "\uF05B",
    "sensors" => "\uE51E",
    "settings" => "\uE8B8",
    "shield" => "\uE9E0",
    "shopping_cart" => "\uE8CC",
    "sort" => "\uE164",
    "star" => "\uF09A",
    "sticky_note_2" => "\uF1FC",
    "subscriptions" => "\uE064",
    "subtitles" => "\uE048",
    "swap_horiz" => "\uE8D4",
    "sync" => "\uE627",
    "tablet_mac" => "\uE331",
    "text_fields" => "\uE262",
    "timer" => "\uE425",
    "touch_app" => "\uE913",
    "translate" => "\uE8E2",
    "trending_up" => "\uE8E5",
    "tune" => "\uE429",
    "tv" => "\uE63B",
    "undo" => "\uE166",
    "unfold_more" => "\uE5D7",
    "upload" => "\uF09B",
    "upload_file" => "\uE9FC",
    "visibility_off" => "\uE8F5",
    "wb_twilight" => "\uE1C6"
  }

  @doc "The character for an icon name, or `nil`."
  @spec glyph(String.t()) :: String.t() | nil
  def glyph(name), do: Map.get(@icons, name)

  @doc """
  The character for an icon name, raising if the font does not carry it.

  Loud on purpose: a missing glyph renders as an empty box, which reads as
  a layout bug rather than a missing asset and is expensive to trace back.
  """
  @spec glyph!(String.t()) :: String.t()
  def glyph!(name) do
    case glyph(name) do
      nil ->
        raise ArgumentError,
              "no Material Symbol #{inspect(name)} in Kati's subset. " <>
                "Add it to the design and run `mix kati.gen.icons`, then re-subset the font."

      char ->
        char
    end
  end

  @doc "Every icon name Kati ships."
  @spec names() :: [String.t()]
  def names, do: Map.keys(@icons) |> Enum.sort()
end
