defmodule Kati.Repo.Migrations.AddMoodPaceAndContentWarnings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:media_watches) do
      add :moods, {:array, :text}, default: []
      add :pace, :text
      add :driven_by, :text
    end

    create table(:media_warning_preferences, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :stance, :text, null: false
      add :category, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:media_warning_preferences, ["category"], unique: true)

    create table(:media_content_warnings, primary_key: false) do
      add :tracked_title_id,
          references(:tracked_titles,
            column: :id,
            name: "media_content_warnings_tracked_title_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :origin, :text, null: false
      add :note, :text
      add :category, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:media_content_warnings, ["tracked_title_id", "category"])
  end

  def down do
    drop_if_exists index(:media_content_warnings, ["tracked_title_id", "category"],
                     name: "media_content_warnings_tracked_title_id_category_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `media_content_warnings` table without the `media_content_warnings_tracked_title_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:media_content_warnings)

    drop_if_exists index(:media_warning_preferences, ["category"],
                     name: "media_warning_preferences_category_index"
                   )

    drop table(:media_warning_preferences)

    alter table(:media_watches) do
      remove :driven_by
      remove :pace
      remove :moods
    end
  end
end