defmodule Kati.Repo.Migrations.AddServicesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:services, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :provider_id, :text
      add :paused, :boolean, null: false
      add :renews_on, :date
      add :currency, :text, null: false
      add :monthly_pence, :bigint
      add :tier, :text, null: false
      add :badge, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:services, ["tier", "name"])
  end

  def down do
    drop_if_exists index(:services, ["tier", "name"], name: "services_tier_name_index")

    drop table(:services)
  end
end