defmodule Kati.Repo.Migrations.MediaSeasonsAndEpisodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cached_seasons, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_modified, :text
      add :etag, :text
      add :last_checked_at, :utc_datetime_usec
      add :fetched_at, :utc_datetime_usec, null: false
      add :release_source, :text
      add :date_confidence, :text, null: false
      add :air_at, :utc_datetime_usec
      add :episode_count, :bigint
      add :poster_path, :text
      add :overview, :text
      add :name, :text
      add :source_id, :text
      add :season_number, :bigint, null: false
      add :title_source_id, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:cached_seasons, ["air_at"])

    create index(:cached_seasons, ["source", "fetched_at"])

    create index(:cached_seasons, ["source", "title_source_id", "season_number"], unique: true)

    create table(:cached_episodes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_modified, :text
      add :etag, :text
      add :last_checked_at, :utc_datetime_usec
      add :fetched_at, :utc_datetime_usec, null: false
      add :release_source, :text
      add :date_confidence, :text, null: false
      add :air_at, :utc_datetime_usec
      add :runtime_minutes, :bigint
      add :still_path, :text
      add :overview, :text
      add :title, :text
      add :special, :boolean, null: false
      add :absolute_number, :bigint
      add :episode_number, :bigint
      add :season_number, :bigint
      add :title_source_id, :text, null: false
      add :source_id, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:cached_episodes, ["air_at"])

    create index(:cached_episodes, ["source", "fetched_at"])

    create index(:cached_episodes, [
             "source",
             "title_source_id",
             "season_number",
             "episode_number"
           ])

    create index(:cached_episodes, ["source", "source_id"], unique: true)
  end

  def down do
    drop_if_exists index(:cached_episodes, ["source", "source_id"],
                     name: "cached_episodes_source_source_id_index"
                   )

    drop_if_exists index(
                     :cached_episodes,
                     ["source", "title_source_id", "season_number", "episode_number"],
                     name:
                       "cached_episodes_source_title_source_id_season_number_episode_number_index"
                   )

    drop_if_exists index(:cached_episodes, ["source", "fetched_at"],
                     name: "cached_episodes_source_fetched_at_index"
                   )

    drop_if_exists index(:cached_episodes, ["air_at"], name: "cached_episodes_air_at_index")

    drop table(:cached_episodes)

    drop_if_exists index(:cached_seasons, ["source", "title_source_id", "season_number"],
                     name: "cached_seasons_source_title_source_id_season_number_index"
                   )

    drop_if_exists index(:cached_seasons, ["source", "fetched_at"],
                     name: "cached_seasons_source_fetched_at_index"
                   )

    drop_if_exists index(:cached_seasons, ["air_at"], name: "cached_seasons_air_at_index")

    drop table(:cached_seasons)
  end
end