defmodule Kati.Repo.Migrations.AddUpgradeProbe do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:spike_things) do
      add :upgrade_probe, :text
    end
  end

  def down do
    alter table(:spike_things) do
      remove :upgrade_probe
    end
  end
end