defmodule Kati.Repo.Migrations.CalendarDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :calendar_id,
          references(:calendars, column: :id, name: "events_calendar_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sync_state, :text, null: false
      add :deleted_at, :utc_datetime_usec
      add :remote_etag, :text
      add :remote_href, :text
      add :remote_id, :text
      add :synced_rev, :bigint, null: false
      add :local_rev, :bigint, null: false
      add :unknown_props, :text
      add :raw_icalendar, :text
      add :created_utc, :utc_datetime_usec
      add :last_modified_utc, :utc_datetime_usec
      add :organizer, :text
      add :sequence, :bigint, null: false
      add :transp, :text
      add :status, :text
      add :kind, :text, null: false
      add :recurs_until_utc, :utc_datetime_usec
      add :rrule, :text
      add :dtend_utc, :utc_datetime_usec
      add :duration_iso, :text
      add :is_all_day, :boolean, null: false
      add :tz_behaviour, :text, null: false
      add :tzid, :text
      add :dtstart_date, :date
      add :dtstart_wall, :text
      add :dtstart_utc, :utc_datetime_usec
      add :description, :text
      add :location, :text
      add :summary, :text
      add :origin, :text, null: false
      add :uid, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:event_occurrence_overrides, primary_key: false) do
      add :calendar_id,
          references(:calendars,
            column: :id,
            name: "event_occurrence_overrides_calendar_id_fkey",
            type: :uuid
          ), null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "event_occurrence_overrides_event_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sync_state, :text, null: false
      add :deleted_at, :utc_datetime_usec
      add :remote_etag, :text
      add :remote_id, :text
      add :synced_rev, :bigint, null: false
      add :local_rev, :bigint, null: false
      add :unknown_props, :text
      add :raw_icalendar, :text
      add :sequence, :bigint
      add :transp, :text
      add :status, :text
      add :dtend_utc, :utc_datetime_usec
      add :duration_iso, :text
      add :is_all_day, :boolean
      add :tz_behaviour, :text
      add :tzid, :text
      add :dtstart_date, :date
      add :dtstart_wall, :text
      add :dtstart_utc, :utc_datetime_usec
      add :description, :text
      add :location, :text
      add :summary, :text
      add :kind, :text, null: false
      add :range_this_and_future, :boolean, null: false
      add :recurrence_id_is_date, :boolean, null: false
      add :recurrence_id_wall, :text, null: false
      add :recurrence_id_utc, :utc_datetime_usec, null: false
      add :event_uid, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:calendars, primary_key: false) do
      add :account_id,
          references(:calendar_accounts,
            column: :id,
            name: "calendars_account_id_fkey",
            type: :uuid
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_sync_at, :utc_datetime_usec
      add :sync_cursor, :text
      add :writeback_policy, :text, null: false
      add :visible, :boolean, null: false
      add :read_only, :boolean, null: false
      add :kind, :text, null: false
      add :colour_token, :text
      add :colour_source, :text
      add :display_name, :text
      add :remote_id, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:events, ["sync_state"])

    create index(:events, ["remote_href"])

    create index(:events, ["remote_id"])

    create index(:events, ["kind", "dtstart_utc"])

    create index(:events, ["calendar_id", "recurs_until_utc"])

    create index(:events, ["calendar_id", "deleted_at", "dtstart_utc"])

    create index(:events, ["calendar_id", "uid"], unique: true)

    create index(:event_occurrence_overrides, ["calendar_id", "event_uid"])

    create index(:event_occurrence_overrides, ["event_id", "recurrence_id_utc"], unique: true)

    create table(:calendar_accounts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sync_window_to, :utc_datetime_usec
      add :sync_window_from, :utc_datetime_usec
      add :last_sync_at, :utc_datetime_usec
      add :state, :text, null: false
      add :credentials_ref, :text
      add :display_name, :text
      add :account_type, :text
      add :account_name, :text
      add :provider, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:calendars, ["account_id", "remote_id"], unique: true)
  end

  def down do
    drop_if_exists index(:calendars, ["account_id", "remote_id"],
                     name: "calendars_account_id_remote_id_index"
                   )

    drop table(:calendar_accounts)

    drop_if_exists index(:event_occurrence_overrides, ["event_id", "recurrence_id_utc"],
                     name: "event_occurrence_overrides_event_id_recurrence_id_utc_index"
                   )

    drop_if_exists index(:event_occurrence_overrides, ["calendar_id", "event_uid"],
                     name: "event_occurrence_overrides_calendar_id_event_uid_index"
                   )

    drop_if_exists index(:events, ["calendar_id", "uid"], name: "events_calendar_id_uid_index")

    drop_if_exists index(:events, ["calendar_id", "deleted_at", "dtstart_utc"],
                     name: "events_calendar_id_deleted_at_dtstart_utc_index"
                   )

    drop_if_exists index(:events, ["calendar_id", "recurs_until_utc"],
                     name: "events_calendar_id_recurs_until_utc_index"
                   )

    drop_if_exists index(:events, ["kind", "dtstart_utc"], name: "events_kind_dtstart_utc_index")

    drop_if_exists index(:events, ["remote_id"], name: "events_remote_id_index")

    drop_if_exists index(:events, ["remote_href"], name: "events_remote_href_index")

    drop_if_exists index(:events, ["sync_state"], name: "events_sync_state_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `calendars` table without the `calendars_account_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:calendars)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `event_occurrence_overrides` table without the `event_occurrence_overrides_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `event_occurrence_overrides` table without the `event_occurrence_overrides_calendar_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:event_occurrence_overrides)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `events` table without the `events_calendar_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:events)
  end
end