defmodule Kati.Repo.Migrations.MediaTrackingAndMeals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tracked_titles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_touched_at, :utc_datetime_usec, null: false
      add :hide_unwatched_titles, :boolean, null: false
      add :add_air_dates_to_calendar, :boolean, null: false
      add :auto_add_new_seasons, :boolean, null: false
      add :notify_new_episodes, :boolean, null: false
      add :user_override_date, :date
      add :rating, :bigint
      add :progress_seconds, :bigint
      add :progress_track, :bigint
      add :progress_page, :bigint
      add :progress_episode, :bigint
      add :progress_season, :bigint
      add :archived, :boolean, null: false
      add :status, :text, null: false
      add :kind, :text, null: false
      add :source_id, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:tracked_titles, ["user_override_date"])

    create index(:tracked_titles, ["status", "last_touched_at"])

    create index(:tracked_titles, ["kind", "archived", "last_touched_at"])

    create index(:tracked_titles, ["source", "source_id"], unique: true)

    create table(:shopping_list_items, primary_key: false) do
      add :food_id,
          references(:foods,
            column: :id,
            name: "shopping_list_items_food_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :meal_plan_id,
          references(:meal_plans,
            column: :id,
            name: "shopping_list_items_meal_plan_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :price_source, :text, null: false
      add :price_currency, :text
      add :price_minor, :bigint
      add :manual, :boolean, null: false
      add :got, :boolean, null: false
      add :meals_label, :text
      add :meal_count, :bigint, null: false
      add :unit, :text, null: false
      add :amount_mg, :bigint, null: false
      add :aisle, :text, null: false
      add :name, :text, null: false
      add :week_starting_on, :date, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:recipes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :fetched_at, :utc_datetime_usec
      add :source_url, :text
      add :totals_rev, :bigint, null: false
      add :ingredients_rev, :bigint, null: false
      add :total_sodium_mg, :bigint, null: false
      add :total_sugar_mg, :bigint, null: false
      add :total_fibre_mg, :bigint, null: false
      add :total_fat_mg, :bigint, null: false
      add :total_carbs_mg, :bigint, null: false
      add :total_protein_mg, :bigint, null: false
      add :total_kcal, :bigint, null: false
      add :note, :text
      add :rating, :bigint
      add :photo_seed, :text
      add :serves, :bigint, null: false
      add :oven_c, :bigint
      add :minutes, :bigint
      add :method, :text
      add :origin, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:recipes, ["ingredients_rev", "totals_rev"])

    create index(:recipes, ["minutes"])

    create index(:recipes, ["total_kcal"])

    create index(:recipes, ["title"])

    create table(:recipe_ingredients, primary_key: false) do
      add :licensed_food_id,
          references(:licensed_foods,
            column: :id,
            name: "recipe_ingredients_licensed_food_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :bundled_food_id,
          references(:bundled_foods,
            column: :id,
            name: "recipe_ingredients_bundled_food_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :food_id,
          references(:foods,
            column: :id,
            name: "recipe_ingredients_food_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_ingredients_recipe_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :shop_for, :boolean, null: false
      add :sodium_mg, :bigint, null: false
      add :sugar_mg, :bigint, null: false
      add :fibre_mg, :bigint, null: false
      add :fat_mg, :bigint, null: false
      add :carbs_mg, :bigint, null: false
      add :protein_mg, :bigint, null: false
      add :kcal, :bigint, null: false
      add :aisle, :text, null: false
      add :unit, :text, null: false
      add :amount_mg, :bigint, null: false
      add :name, :text, null: false
      add :position, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:media_watches, primary_key: false) do
      add :tracked_title_id,
          references(:tracked_titles,
            column: :id,
            name: "media_watches_tracked_title_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tags, :text
      add :companions, :text
      add :place, :text
      add :service, :text
      add :rewatch_number, :bigint
      add :contains_spoilers, :boolean, null: false
      add :review, :text
      add :rating, :bigint
      add :watched_at, :utc_datetime_usec
      add :watched_on, :date
      add :episode_number, :bigint
      add :season_number, :bigint
      add :episode_source_id, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:media_watches, ["watched_at"])

    create index(:media_watches, ["tracked_title_id", "watched_at"])

    create index(:media_watches, ["tracked_title_id", "episode_source_id"])

    create table(:meal_plans, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tags, :text
      add :photo_seed, :text
      add :silent_only, :boolean, null: false
      add :stop_after_skips, :bigint, null: false
      add :skip_during_events, :boolean, null: false
      add :quiet_hours_until, :time
      add :quiet_hours_from, :time
      add :evening_preview_at, :time
      add :reminder_lead_minutes, :bigint, null: false
      add :reminders_enabled, :boolean, null: false
      add :tolerance_permille, :bigint, null: false
      add :target_fibre_mg, :bigint
      add :target_fat_mg, :bigint
      add :target_carbs_mg, :bigint
      add :target_protein_mg, :bigint
      add :target_kcal, :bigint
      add :use_count, :bigint, null: false
      add :last_used_on, :date
      add :keep_history, :boolean, null: false
      add :activates_on, :date
      add :weeks_total, :bigint
      add :starts_on, :date
      add :repeat, :text, null: false
      add :imported_at, :utc_datetime_usec
      add :imported_from, :text
      add :origin, :text, null: false
      add :status, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:meal_plans, ["activates_on"])

    create index(:meal_plans, ["status", "last_used_on"])

    create index(:meal_plans, ["status"],
             name: "meal_plans_single_active_index",
             unique: true,
             where: "status = 'active'"
           )

    create table(:meal_plan_slots, primary_key: false) do
      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "meal_plan_slots_recipe_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :meal_plan_id,
          references(:meal_plans,
            column: :id,
            name: "meal_plan_slots_meal_plan_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :portion_milli, :bigint, null: false
      add :state, :text, null: false
      add :slot_time, :time
      add :slot_name, :text, null: false
      add :position, :bigint, null: false
      add :day_of_week, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:meal_plan_slots, ["meal_plan_id", "day_of_week", "slot_time"])

    create index(:meal_plan_slots, ["meal_plan_id", "day_of_week", "position"], unique: true)

    create table(:meal_logs, primary_key: false) do
      add :meal_plan_slot_id,
          references(:meal_plan_slots,
            column: :id,
            name: "meal_logs_meal_plan_slot_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :meal_plan_id,
          references(:meal_plans,
            column: :id,
            name: "meal_logs_meal_plan_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "meal_logs_recipe_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :rating, :bigint
      add :note, :text
      add :frozen_at, :utc_datetime_usec, null: false
      add :recipe_rev, :bigint
      add :sodium_mg, :bigint, null: false
      add :sugar_mg, :bigint, null: false
      add :fibre_mg, :bigint, null: false
      add :fat_mg, :bigint, null: false
      add :carbs_mg, :bigint, null: false
      add :protein_mg, :bigint, null: false
      add :kcal, :bigint, null: false
      add :portion_milli, :bigint, null: false
      add :slot_time, :time
      add :slot_name, :text
      add :title, :text, null: false
      add :state, :text, null: false
      add :logged_at, :utc_datetime_usec, null: false
      add :logged_on, :date, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:meal_logs, ["state", "logged_on"])

    create index(:meal_logs, ["meal_plan_id", "logged_on"])

    create index(:meal_logs, ["logged_on", "slot_time"])

    create table(:licensed_foods, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_checked_at, :utc_datetime_usec
      add :fetched_at, :utc_datetime_usec, null: false
      add :sodium_mg, :bigint, null: false
      add :sugar_mg, :bigint, null: false
      add :fibre_mg, :bigint, null: false
      add :fat_mg, :bigint, null: false
      add :carbs_mg, :bigint, null: false
      add :protein_mg, :bigint, null: false
      add :kcal, :bigint, null: false
      add :default_aisle, :text, null: false
      add :barcode, :text
      add :brand, :text
      add :name, :text, null: false
      add :attribution, :text
      add :source_id, :text, null: false
      add :source, :text, null: false
      add :licence, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:licensed_foods, ["name"])

    create index(:licensed_foods, ["source", "fetched_at"])

    create index(:licensed_foods, ["source", "source_id"], unique: true)

    create table(:foods, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_price_at, :utc_datetime_usec
      add :last_price_currency, :text
      add :last_price_minor, :bigint
      add :sodium_mg, :bigint
      add :sugar_mg, :bigint
      add :fibre_mg, :bigint
      add :fat_mg, :bigint
      add :carbs_mg, :bigint
      add :protein_mg, :bigint
      add :kcal, :bigint
      add :default_aisle, :text, null: false
      add :cuisine, :text
      add :name_original, :text
      add :name, :text, null: false
      add :licence, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:shopping_list_items, ["meal_plan_id", "week_starting_on", "got"])

    create index(:shopping_list_items, ["meal_plan_id", "week_starting_on", "aisle"])

    create index(:foods, ["default_aisle"])

    create index(:foods, ["cuisine"])

    create index(:foods, ["name"])

    create table(:bundled_foods, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sodium_mg, :bigint, null: false
      add :sugar_mg, :bigint, null: false
      add :fibre_mg, :bigint, null: false
      add :fat_mg, :bigint, null: false
      add :carbs_mg, :bigint, null: false
      add :protein_mg, :bigint, null: false
      add :kcal, :bigint, null: false
      add :default_aisle, :text, null: false
      add :name, :text, null: false
      add :bundle_version, :text, null: false
      add :source_key, :text, null: false
      add :corpus, :text, null: false
      add :licence, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:recipe_ingredients, ["aisle"])

    create index(:recipe_ingredients, ["recipe_id", "position"], unique: true)

    create index(:bundled_foods, ["default_aisle"])

    create index(:bundled_foods, ["name"])

    create index(:bundled_foods, ["corpus", "source_key"], unique: true)
  end

  def down do
    drop_if_exists index(:bundled_foods, ["corpus", "source_key"],
                     name: "bundled_foods_corpus_source_key_index"
                   )

    drop_if_exists index(:bundled_foods, ["name"], name: "bundled_foods_name_index")

    drop_if_exists index(:bundled_foods, ["default_aisle"],
                     name: "bundled_foods_default_aisle_index"
                   )

    drop_if_exists index(:recipe_ingredients, ["recipe_id", "position"],
                     name: "recipe_ingredients_recipe_id_position_index"
                   )

    drop_if_exists index(:recipe_ingredients, ["aisle"], name: "recipe_ingredients_aisle_index")

    drop table(:bundled_foods)

    drop_if_exists index(:foods, ["name"], name: "foods_name_index")

    drop_if_exists index(:foods, ["cuisine"], name: "foods_cuisine_index")

    drop_if_exists index(:foods, ["default_aisle"], name: "foods_default_aisle_index")

    drop_if_exists index(:shopping_list_items, ["meal_plan_id", "week_starting_on", "aisle"],
                     name: "shopping_list_items_meal_plan_id_week_starting_on_aisle_index"
                   )

    drop_if_exists index(:shopping_list_items, ["meal_plan_id", "week_starting_on", "got"],
                     name: "shopping_list_items_meal_plan_id_week_starting_on_got_index"
                   )

    drop table(:foods)

    drop_if_exists index(:licensed_foods, ["source", "source_id"],
                     name: "licensed_foods_source_source_id_index"
                   )

    drop_if_exists index(:licensed_foods, ["source", "fetched_at"],
                     name: "licensed_foods_source_fetched_at_index"
                   )

    drop_if_exists index(:licensed_foods, ["name"], name: "licensed_foods_name_index")

    drop table(:licensed_foods)

    drop_if_exists index(:meal_logs, ["logged_on", "slot_time"],
                     name: "meal_logs_logged_on_slot_time_index"
                   )

    drop_if_exists index(:meal_logs, ["meal_plan_id", "logged_on"],
                     name: "meal_logs_meal_plan_id_logged_on_index"
                   )

    drop_if_exists index(:meal_logs, ["state", "logged_on"],
                     name: "meal_logs_state_logged_on_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `meal_logs` table without the `meal_logs_recipe_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `meal_logs` table without the `meal_logs_meal_plan_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `meal_logs` table without the `meal_logs_meal_plan_slot_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:meal_logs)

    drop_if_exists index(:meal_plan_slots, ["meal_plan_id", "day_of_week", "position"],
                     name: "meal_plan_slots_meal_plan_id_day_of_week_position_index"
                   )

    drop_if_exists index(:meal_plan_slots, ["meal_plan_id", "day_of_week", "slot_time"],
                     name: "meal_plan_slots_meal_plan_id_day_of_week_slot_time_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `meal_plan_slots` table without the `meal_plan_slots_meal_plan_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `meal_plan_slots` table without the `meal_plan_slots_recipe_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:meal_plan_slots)

    drop_if_exists index(:meal_plans, ["status"], name: "meal_plans_single_active_index")

    drop_if_exists index(:meal_plans, ["status", "last_used_on"],
                     name: "meal_plans_status_last_used_on_index"
                   )

    drop_if_exists index(:meal_plans, ["activates_on"], name: "meal_plans_activates_on_index")

    drop table(:meal_plans)

    drop_if_exists index(:media_watches, ["tracked_title_id", "episode_source_id"],
                     name: "media_watches_tracked_title_id_episode_source_id_index"
                   )

    drop_if_exists index(:media_watches, ["tracked_title_id", "watched_at"],
                     name: "media_watches_tracked_title_id_watched_at_index"
                   )

    drop_if_exists index(:media_watches, ["watched_at"], name: "media_watches_watched_at_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `media_watches` table without the `media_watches_tracked_title_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:media_watches)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `recipe_ingredients` table without the `recipe_ingredients_recipe_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `recipe_ingredients` table without the `recipe_ingredients_food_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `recipe_ingredients` table without the `recipe_ingredients_bundled_food_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `recipe_ingredients` table without the `recipe_ingredients_licensed_food_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:recipe_ingredients)

    drop_if_exists index(:recipes, ["title"], name: "recipes_title_index")

    drop_if_exists index(:recipes, ["total_kcal"], name: "recipes_total_kcal_index")

    drop_if_exists index(:recipes, ["minutes"], name: "recipes_minutes_index")

    drop_if_exists index(:recipes, ["ingredients_rev", "totals_rev"],
                     name: "recipes_ingredients_rev_totals_rev_index"
                   )

    drop table(:recipes)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `shopping_list_items` table without the `shopping_list_items_meal_plan_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `shopping_list_items` table without the `shopping_list_items_food_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:shopping_list_items)

    drop_if_exists index(:tracked_titles, ["source", "source_id"],
                     name: "tracked_titles_source_source_id_index"
                   )

    drop_if_exists index(:tracked_titles, ["kind", "archived", "last_touched_at"],
                     name: "tracked_titles_kind_archived_last_touched_at_index"
                   )

    drop_if_exists index(:tracked_titles, ["status", "last_touched_at"],
                     name: "tracked_titles_status_last_touched_at_index"
                   )

    drop_if_exists index(:tracked_titles, ["user_override_date"],
                     name: "tracked_titles_user_override_date_index"
                   )

    drop table(:tracked_titles)
  end
end