defmodule Kati.Repo.Migrations.AddSourceToSpikeThings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:spike_things) do
      add :source, :text
    end
  end

  def down do
    alter table(:spike_things) do
      remove :source
    end
  end
end