defmodule Kati.Repo.Migrations.AddRecipeSlotName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:recipes) do
      add :slot_name, :text
    end
  end

  def down do
    alter table(:recipes) do
      remove :slot_name
    end
  end
end