defmodule Kati.Repo.Migrations.AddNotificationPending do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_pending, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :armed_at, :utc_datetime
      add :fingerprint, :bigint, null: false
      add :priority, :text, null: false
      add :tz, :text
      add :kind, :text, null: false
      add :fire_at_utc, :utc_datetime, null: false
      add :domain, :text, null: false
      add :id, :text, null: false, primary_key: true
    end

    create index(:notification_pending, ["domain", "fire_at_utc"])

    create index(:notification_pending, ["fire_at_utc"])
  end

  def down do
    drop_if_exists index(:notification_pending, ["fire_at_utc"],
                     name: "notification_pending_fire_at_utc_index"
                   )

    drop_if_exists index(:notification_pending, ["domain", "fire_at_utc"],
                     name: "notification_pending_domain_fire_at_utc_index"
                   )

    drop table(:notification_pending)
  end
end