defmodule Kati.Repo.Migrations.CreateSpikeThings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:spike_things, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :amount, :decimal, null: false
      add :label, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:spike_things)
  end
end