defmodule Kati.Repo.Migrations.AddGoalsAndMoney do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:expenses, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :section, :text, null: false
      add :spent_on, :date, null: false
      add :currency, :text, null: false
      add :amount_pence, :bigint
      add :description, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:expenses, ["spent_on"])

    create table(:goals, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :repeat, :boolean, null: false
      add :ends_on, :date, null: false
      add :starts_on, :date, null: false
      add :period, :text, null: false
      add :progress, :bigint, null: false
      add :target, :bigint, null: false
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:goals, ["ends_on"])
  end

  def down do
    drop_if_exists index(:goals, ["ends_on"], name: "goals_ends_on_index")

    drop table(:goals)

    drop_if_exists index(:expenses, ["spent_on"], name: "expenses_spent_on_index")

    drop table(:expenses)
  end
end