defmodule Kati.Repo.Migrations.MediaCache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cached_titles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_modified, :text
      add :etag, :text
      add :last_checked_at, :utc_datetime_usec
      add :fetched_at, :utc_datetime_usec, null: false
      add :tvdb_id, :text
      add :mal_id, :text
      add :anilist_id, :text
      add :tvmaze_id, :text
      add :imdb_id, :text
      add :tmdb_id, :text
      add :release_source, :text
      add :date_confidence, :text, null: false
      add :next_release_at, :utc_datetime_usec
      add :genres, :text
      add :runtime_minutes, :bigint
      add :backdrop_path, :text
      add :poster_path, :text
      add :overview, :text
      add :title_original, :text
      add :title, :text
      add :kind, :text, null: false
      add :source_id, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:cached_titles, ["kind"])

    create index(:cached_titles, ["next_release_at"])

    create index(:cached_titles, ["source", "fetched_at"])

    create index(:cached_titles, ["source", "source_id"], unique: true)
  end

  def down do
    drop_if_exists index(:cached_titles, ["source", "source_id"],
                     name: "cached_titles_source_source_id_index"
                   )

    drop_if_exists index(:cached_titles, ["source", "fetched_at"],
                     name: "cached_titles_source_fetched_at_index"
                   )

    drop_if_exists index(:cached_titles, ["next_release_at"],
                     name: "cached_titles_next_release_at_index"
                   )

    drop_if_exists index(:cached_titles, ["kind"], name: "cached_titles_kind_index")

    drop table(:cached_titles)
  end
end