defmodule Kati.Repo.Migrations.AddHealthDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:health_doses, primary_key: false) do
      add :medication_id,
          references(:health_medications,
            column: :id,
            name: "health_doses_medication_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :recorded_at, :utc_datetime
      add :state, :text, null: false
      add :due_at, :text, null: false
      add :due_on, :date, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:health_medications, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :instruction, :text
      add :times, {:array, :text}, null: false, default: []
      add :schedule, :text
      add :dose, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:health_doses, ["due_on", "due_at"])

    create index(:health_medications, ["name"])

    create table(:health_readings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :note, :text
      add :taken_at, :utc_datetime
      add :taken_on, :date, null: false
      add :grams, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:health_readings, ["taken_on"])
  end

  def down do
    drop_if_exists index(:health_readings, ["taken_on"], name: "health_readings_taken_on_index")

    drop table(:health_readings)

    drop_if_exists index(:health_medications, ["name"], name: "health_medications_name_index")

    drop_if_exists index(:health_doses, ["due_on", "due_at"],
                     name: "health_doses_due_on_due_at_index"
                   )

    drop table(:health_medications)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `health_doses` table without the `health_doses_medication_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:health_doses)
  end
end