defmodule Kati.Repo.Migrations.AddMusicDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:music_tracks, primary_key: false) do
      add :album_id,
          references(:music_albums, column: :id, name: "music_tracks_album_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_played_on, :date
      add :plays, :bigint, null: false
      add :seconds, :bigint
      add :title, :text, null: false
      add :position, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:music_listens, primary_key: false) do
      add :album_id,
          references(:music_albums,
            column: :id,
            name: "music_listens_album_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :source, :text, null: false
      add :scope, :text, null: false
      add :minutes, :bigint
      add :tracks, :bigint, null: false
      add :started_at, :utc_datetime
      add :listened_on, :date, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:music_artists, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :first_heard_on, :date
      add :following, :boolean, null: false
      add :photo_seed, :text
      add :source_id, :text
      add :source, :text, null: false
      add :country, :text
      add :role, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:music_artists, ["following"])

    create table(:music_albums, primary_key: false) do
      add :artist_id,
          references(:music_artists,
            column: :id,
            name: "music_albums_artist_id_fkey",
            type: :uuid
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_played_on, :date
      add :first_heard_on, :date
      add :note_on, :date
      add :note, :text
      add :rating, :bigint
      add :art_seed, :text
      add :source_id, :text
      add :source, :text, null: false
      add :released_year, :bigint
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:music_tracks, ["album_id", "position"])

    create index(:music_listens, ["album_id", "listened_on"])

    create index(:music_albums, ["artist_id", "released_year"])

    create index(:music_albums, ["updated_at"])
  end

  def down do
    drop_if_exists index(:music_albums, ["updated_at"], name: "music_albums_updated_at_index")

    drop_if_exists index(:music_albums, ["artist_id", "released_year"],
                     name: "music_albums_artist_id_released_year_index"
                   )

    drop_if_exists index(:music_listens, ["album_id", "listened_on"],
                     name: "music_listens_album_id_listened_on_index"
                   )

    drop_if_exists index(:music_tracks, ["album_id", "position"],
                     name: "music_tracks_album_id_position_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `music_albums` table without the `music_albums_artist_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:music_albums)

    drop_if_exists index(:music_artists, ["following"], name: "music_artists_following_index")

    drop table(:music_artists)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `music_listens` table without the `music_listens_album_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:music_listens)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `music_tracks` table without the `music_tracks_album_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:music_tracks)
  end
end