defmodule Kati.Repo.Migrations.AddBooksDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:books, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :series_total, :bigint
      add :series_position, :bigint
      add :series_name, :text
      add :rating, :bigint
      add :lent_due_on, :date
      add :lent_to, :text
      add :owned, :boolean, null: false
      add :did_not_finish_reason, :text
      add :stopped_at_page, :bigint
      add :current_page, :bigint, null: false
      add :duration_minutes, :bigint
      add :page_count, :bigint
      add :format, :text, null: false
      add :status, :text, null: false
      add :isbn, :text
      add :published_year, :bigint
      add :publisher, :text
      add :cover_seed, :text
      add :source_id, :text
      add :source, :text, null: false
      add :author, :text
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:books, ["status", "updated_at"])

    create index(:books, ["updated_at"])

    create table(:book_reading_sessions, primary_key: false) do
      add :book_id,
          references(:books,
            column: :id,
            name: "book_reading_sessions_book_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :reread, :boolean, null: false
      add :source, :text, null: false
      add :minutes, :bigint
      add :to_page, :bigint, null: false
      add :from_page, :bigint, null: false
      add :started_at, :utc_datetime
      add :read_on, :date, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:book_reading_sessions, ["book_id", "read_on"])

    create table(:book_notes, primary_key: false) do
      add :book_id, references(:books, column: :id, name: "book_notes_book_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :page, :bigint
      add :kind, :text, null: false
      add :body, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:book_notes, ["book_id", "page"])
  end

  def down do
    drop_if_exists index(:book_notes, ["book_id", "page"], name: "book_notes_book_id_page_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `book_notes` table without the `book_notes_book_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:book_notes)

    drop_if_exists index(:book_reading_sessions, ["book_id", "read_on"],
                     name: "book_reading_sessions_book_id_read_on_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `book_reading_sessions` table without the `book_reading_sessions_book_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:book_reading_sessions)

    drop_if_exists index(:books, ["updated_at"], name: "books_updated_at_index")

    drop_if_exists index(:books, ["status", "updated_at"], name: "books_status_updated_at_index")

    drop table(:books)
  end
end