defmodule Kati.Repo.Migrations.SyncOutboxRejectedChangesAndCachedTitleCounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sync_rejected_changes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :dismissed_at, :utc_datetime_usec
      add :applied_at, :utc_datetime_usec
      add :base_properties, :text, null: false
      add :properties, :text, null: false
      add :reason, :text, null: false
      add :side, :text, null: false
      add :event_uid, :text, null: false
      add :calendar_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:sync_rejected_changes, ["applied_at"])

    create index(:sync_rejected_changes, ["calendar_id", "event_uid"])

    create table(:sync_outbox, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_error, :text
      add :state, :text, null: false
      add :depends_on, :uuid
      add :idempotency_key, :text, null: false
      add :next_attempt_at, :utc_datetime_usec
      add :attempt_count, :bigint, null: false
      add :payload, :text, null: false
      add :op, :text, null: false
      add :event_uid, :text, null: false
      add :calendar_id, :uuid, null: false
      add :account_id, :uuid
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:sync_outbox, ["idempotency_key"], unique: true)

    create index(:sync_outbox, ["depends_on"])

    create index(:sync_outbox, ["calendar_id", "event_uid"])

    create index(:sync_outbox, ["calendar_id", "state", "next_attempt_at"])

    alter table(:cached_titles) do
      add :episode_count, :bigint
      add :page_count, :bigint
      add :track_count, :bigint
    end
  end

  def down do
    alter table(:cached_titles) do
      remove :track_count
      remove :page_count
      remove :episode_count
    end

    drop_if_exists index(:sync_outbox, ["calendar_id", "state", "next_attempt_at"],
                     name: "sync_outbox_calendar_id_state_next_attempt_at_index"
                   )

    drop_if_exists index(:sync_outbox, ["calendar_id", "event_uid"],
                     name: "sync_outbox_calendar_id_event_uid_index"
                   )

    drop_if_exists index(:sync_outbox, ["depends_on"], name: "sync_outbox_depends_on_index")

    drop_if_exists index(:sync_outbox, ["idempotency_key"],
                     name: "sync_outbox_idempotency_key_index"
                   )

    drop table(:sync_outbox)

    drop_if_exists index(:sync_rejected_changes, ["calendar_id", "event_uid"],
                     name: "sync_rejected_changes_calendar_id_event_uid_index"
                   )

    drop_if_exists index(:sync_rejected_changes, ["applied_at"],
                     name: "sync_rejected_changes_applied_at_index"
                   )

    drop table(:sync_rejected_changes)
  end
end