// KATI-BEGIN(K-05 vendored-header) mob_new=0.4.20
// KATI-VENDORED: generated by mob_new 0.4.20 against mob 0.7.20 on 2026-08-18.
// Third-party code. Do not edit outside KATI-BEGIN/KATI-END fences.
// Upgrade procedure: bin/mob_bridge_diff.sh — see native/README.md.
// KATI-END(K-05 vendored-header)
// beam_jni.c — JNI entry points for Kati.
// Generated by mix mob.new. Edit the two defines below; do not touch the rest.

#include <jni.h>
#include "mob_beam.h"

#define BRIDGE_CLASS  "com/example/kati/MobBridge"
#define APP_MODULE    "kati"

JavaVM* g_jvm      = NULL;
jobject g_activity = NULL;

// KATI-BEGIN(K-21 nif-bridge-class) mob_new=0.4.20
// WHY: Kati's project-owned static NIFs (c_src/kati_secure_store.c,
// c_src/kati_bridge.c) call @JvmStatic methods on MobBridge. They cannot look
// the class up themselves: a NIF runs on an Erlang scheduler thread, ERTS
// created that thread, it has no Java frames, and FindClass on such a thread
// resolves against the SYSTEM class loader — which does not contain
// com.example.kati.MobBridge. The lookup returns NULL with a pending
// ClassNotFoundException, and the symptom reads as "the bridge method is
// missing" rather than "the lookup happened on the wrong thread".
//
// JNI_OnLoad runs on the thread that called System.loadLibrary, which does
// have a Java frame, so this is the one place the lookup works. Mob solves the
// identical problem one line below in mob_ui_cache_class (mob_nif.zig:1712),
// but caches into a Zig-internal with no C linkage, so Kati caches its own
// alongside it rather than reaching into a dependency's private state.
//
// A global ref, not a local one: a local reference is valid only for the frame
// that created it, and this outlives JNI_OnLoad by the life of the process.
jclass g_kati_bridge_cls = NULL;

static void kati_cache_bridge_class(JNIEnv* env) {
    jclass local = (*env)->FindClass(env, BRIDGE_CLASS);
    if (local == NULL) {
        // Clear the pending exception: leaving one set makes the NEXT JNI call
        // on this thread abort the process, so a missing class would present
        // as an unrelated crash later in startup.
        if ((*env)->ExceptionCheck(env)) (*env)->ExceptionClear(env);
        return;
    }
    g_kati_bridge_cls = (jclass)(*env)->NewGlobalRef(env, local);
    (*env)->DeleteLocalRef(env, local);
}
// KATI-END(K-21 nif-bridge-class)

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    JNIEnv* env;
    (*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6);
    mob_ui_cache_class(env, BRIDGE_CLASS);
    // KATI-BEGIN(K-21 nif-bridge-class-cache) mob_new=0.4.20
    // Same class, Kati's own cache — see the K-21 nif-bridge-class block above
    // for why this cannot be done lazily from the NIF itself.
    kati_cache_bridge_class(env);
    // KATI-END(K-21 nif-bridge-class-cache)
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_example_kati_MainActivity_nativeSetActivity(JNIEnv* env, jobject thiz, jobject activity) {
    mob_init_bridge(env, activity);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MainActivity_nativeStartBeam(JNIEnv* env, jobject thiz) {
    mob_start_beam(APP_MODULE);
}

// Called from MobBridge.nativeSendTap(handle) in Kotlin when a button is tapped.
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendTap(JNIEnv* env, jclass cls, jint handle) {
    mob_send_tap((int)handle);
}

// Called from MobBridge.nativeSendChangeStr/Bool/Float when an input widget changes.
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendChangeStr(JNIEnv* env, jclass cls, jint handle, jstring value) {
    const char* utf8 = (*env)->GetStringUTFChars(env, value, NULL);
    mob_send_change_str((int)handle, utf8);
    (*env)->ReleaseStringUTFChars(env, value, utf8);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendChangeBool(JNIEnv* env, jclass cls, jint handle, jboolean value) {
    mob_send_change_bool((int)handle, (int)value);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendChangeFloat(JNIEnv* env, jclass cls, jint handle, jfloat value) {
    mob_send_change_float((int)handle, (double)value);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendFocus(JNIEnv* env, jclass cls, jint handle) {
    mob_send_focus((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendBlur(JNIEnv* env, jclass cls, jint handle) {
    mob_send_blur((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSendSubmit(JNIEnv* env, jclass cls, jint handle) {
    mob_send_submit((int)handle);
}

// Called from MobBridge.nativeHandleBack() when the Android back gesture fires.
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeHandleBack(JNIEnv* env, jclass cls) {
    mob_handle_back();
}

// Called from MobBridge.notifyColorSchemeChanged when MainActivity's
// onConfigurationChanged sees a uiMode flip. `scheme` is "light" or "dark".
JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeNotifyColorScheme(JNIEnv* env, jclass cls,
    jstring scheme) {
    if (!scheme) return;
    const char* utf8 = (*env)->GetStringUTFChars(env, scheme, NULL);
    if (utf8) {
        mob_send_color_scheme_changed(utf8);
        (*env)->ReleaseStringUTFChars(env, scheme, utf8);
    }
}

// ── Device capability result delivery ────────────────────────────────────
// Called from MobBridge when async results are ready.

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverAtom2(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    mob_deliver_atom2(pid, ca1, ca2);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverAtom3(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2, jstring a3) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    const char* ca3 = (*env)->GetStringUTFChars(env, a3, NULL);
    mob_deliver_atom3(pid, ca1, ca2, ca3);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
    (*env)->ReleaseStringUTFChars(env, a3, ca3);
}

// KATI-BEGIN(K-01 drop-location-stub) mob_new=0.4.20
// mob 0.7.x extracted Location into the standalone `mob_location` plugin and
// removed `mob_deliver_location` from core, but the mob_new template still
// emits this stub. Under NDK 27 / clang 18 an implicit function declaration
// is an error, not a warning, so a stock generated project fails to build:
//
//   beam_jni.c:117:5: error: call to undeclared function 'mob_deliver_location'
//
// Declaring it would only move the failure to link time — the symbol does not
// exist in core at all. Kati does not use location (the permission is not even
// requested), so the stub is removed rather than reinstated. If location is
// ever needed, add {:mob_location, "~> 0.1"} and let the plugin supply both
// halves.
// KATI-END(K-01 drop-location-stub)

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverMotion(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz, jlong ts) {
    mob_deliver_motion(pid, ax, ay, az, gx, gy, gz, (long long)ts);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverFileResult(JNIEnv* env, jclass cls,
    jlong pid, jstring event, jstring sub, jstring json_items) {
    const char* ce  = (*env)->GetStringUTFChars(env, event, NULL);
    const char* cs  = (*env)->GetStringUTFChars(env, sub,   NULL);
    const char* cj  = json_items ? (*env)->GetStringUTFChars(env, json_items, NULL) : NULL;
    mob_deliver_file_result(pid, ce, cs, cj);
    (*env)->ReleaseStringUTFChars(env, event, ce);
    (*env)->ReleaseStringUTFChars(env, sub,   cs);
    if (cj) (*env)->ReleaseStringUTFChars(env, json_items, cj);
}


JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverPushToken(JNIEnv* env, jclass cls,
    jlong pid, jstring token) {
    const char* ct = (*env)->GetStringUTFChars(env, token, NULL);
    mob_deliver_push_token(pid, ct);
    (*env)->ReleaseStringUTFChars(env, token, ct);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverNotification(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_notification(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeSetLaunchNotification(JNIEnv* env, jclass cls,
    jstring json) {
    if (!json) { mob_set_launch_notification(NULL); return; }
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_set_launch_notification(cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverWebViewMessage(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_webview_message(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverWebViewBlocked(JNIEnv* env, jclass cls,
    jlong pid, jstring url) {
    const char* cu = (*env)->GetStringUTFChars(env, url, NULL);
    mob_deliver_webview_blocked(pid, cu);
    (*env)->ReleaseStringUTFChars(env, url, cu);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverAlertAction(JNIEnv* env, jclass cls,
    jstring action) {
    const char* ca = (*env)->GetStringUTFChars(env, action, NULL);
    mob_deliver_alert_action(ca);
    (*env)->ReleaseStringUTFChars(env, action, ca);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverComponentEvent(JNIEnv* env, jclass cls,
    jint handle, jstring event, jstring payload_json) {
    const char* ce = (*env)->GetStringUTFChars(env, event,        NULL);
    const char* cj = (*env)->GetStringUTFChars(env, payload_json, NULL);
    mob_send_component_event((int)handle, ce, cj);
    (*env)->ReleaseStringUTFChars(env, event,        ce);
    (*env)->ReleaseStringUTFChars(env, payload_json, cj);
}

// ── Mob.Peripheral.VendorUsb delivery thunks ─────────────────────────────────
// Called from MobBridge's USB code when Android USB host events fire.
// See lib/mob/peripheral/vendor_usb.ex for the public message envelope shape.

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbDevices(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_vendor_usb_devices(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbPermission(JNIEnv* env, jclass cls,
    jlong pid, jboolean granted, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_permission(pid, granted ? 1 : 0, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbOpened(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_opened(pid, (int)session_id, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbData(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jbyteArray bytes, jint len) {
    if (!bytes || len <= 0) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, NULL, 0);
        return;
    }
    jbyte* buf = (*env)->GetByteArrayElements(env, bytes, NULL);
    if (buf) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, (const uint8_t*)buf, (size_t)len);
        (*env)->ReleaseByteArrayElements(env, bytes, buf, JNI_ABORT);
    }
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbWriteComplete(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jint bytes_written) {
    mob_deliver_vendor_usb_write_complete(pid, (int)session_id, (int)bytes_written);
}

JNIEXPORT void JNICALL
Java_com_example_kati_MobBridge_nativeDeliverVendorUsbEvent(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring tag, jstring reason) {
    const char* ct = (*env)->GetStringUTFChars(env, tag, NULL);
    const char* cr = reason ? (*env)->GetStringUTFChars(env, reason, NULL) : NULL;
    mob_deliver_vendor_usb_event(pid, (int)session_id, ct, cr);
    (*env)->ReleaseStringUTFChars(env, tag, ct);
    if (cr) (*env)->ReleaseStringUTFChars(env, reason, cr);
}

// ── Bluetooth Classic (Mob.Bt suite) — JNI thunks ───────────────────────
// Each thunk unmarshals Java args into C primitives, calls the matching
// mob_deliver_bt_* helper, then releases.

// ── Adapter-level events (no session) ──────────────────────────────────









// ── Paired-list streaming builder ──────────────────────────────────────




// ── HFP profile ────────────────────────────────────────────────────────











// ── SPP profile ────────────────────────────────────────────────────────







// ── HID profile ────────────────────────────────────────────────────────

// KATI-BEGIN(K-01 drop-plugin-stubs) mob_new=0.4.20
// mob 0.7.x moved Bluetooth Classic and Camera out of core into standalone
// plugins, but the mob_new template still emits JNI stubs calling the
// removed core symbols. They compile (mob_beam.h still declares them) and
// then fail at load:
//
//   java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol
//   "mob_deliver_camera_frame" referenced by "libkati.so"
//
// dlopen resolves eagerly, so a single missing symbol aborts the whole
// library load and the app dies in MainActivity.<clinit> before any Elixir
// runs. 33 stubs were removed here (32 Bluetooth + camera frames). Kati uses
// none of them; if any is ever needed, add the corresponding plugin, which
// supplies both the native half and the symbol.
// KATI-END(K-01 drop-plugin-stubs)
