// KATI-BEGIN(K-22 periodic-worker) mob_new=0.4.20
// KATI-VENDORED: this file is Kati's own, not generated by mob_new. It is
// fenced and ledgered because it exists to work around a gap in Mob.
//
// WHY THE WORK HAPPENS IN KOTLIN AND NOT IN THE BEAM
//
// You cannot boot a headless BEAM from a WorkManager Worker, and this is not a
// Mob limitation to be patched around — it is five independent blockers, three
// of them structural to ERTS:
//
//   1. The JNI symbol is name-bound to MainActivity. beam_jni.c.eex exports
//      Java_<pkg>_MainActivity_nativeStartBeam; a Worker declaring the same
//      external resolves to Java_<pkg>_KatiRefreshWorker_nativeStartBeam,
//      which does not exist → UnsatisfiedLinkError.
//   2. erl_start never returns and ERTS is a per-process singleton
//      (mob_beam.zig:707-712, "erl_start blocks forever in the normal case").
//      doWork() would never return, and a user opening the app meanwhile would
//      be a two-ERTS-instances crash in one process.
//   3. mob_start_beam polls Activity.hasWindowFocus() before starting ERTS —
//      a 40-line comment headed "Cold-start race condition fix — DO NOT REMOVE
//      THIS BLOCK" describes the SIGABRT it prevents. A Worker has no window.
//   4. Every plugin bridge is Activity-typed and would silently no-op.
//   5. ~25 MB of native runtime and a measured 54-143 mAh/hr for a *sleeping*
//      BEAM, against ~50 ms of CPU for the same fetch in Kotlin.
//
// So: fetch in Kotlin, hand the result to the BEAM through the filesystem,
// ingest on next foreground. That is the correct architecture, not a fallback.
//
// THE CHANNEL IS VERIFIED, NOT ASSUMED
//
// mob_beam.zig:277-278 does `setenv("MOB_DATA_DIR", files_dir)`, so Elixir's
// System.get_env("MOB_DATA_DIR") and Kotlin's context.filesDir name the SAME
// directory. What does NOT work as a channel, and why nobody should retry it:
// Mob.State is :dets (Kotlin cannot write Erlang External Term Format); there
// is no SharedPreferences accessor from Elixir; and writing the SQLite
// database from Kotlin is rejected outright — Ash/Ecto-owned tables from
// outside the schema, no migration awareness, and a WAL-lock race against a
// live BEAM.
//
// ONE FILE PER RUN, NOT ONE SHARED FILE
//
// The obvious protocol is a single kati_episode_inbox.json that the Worker
// appends to. It is wrong: the Worker and the BEAM can both be alive (the BEAM
// inside BeamForegroundService), and append means read-modify-write, which
// means a lost update or a file lock. Each run writes its own file into
// kati_inbox/ instead — temp file plus rename, so a reader never sees a
// half-written one — and the BEAM drains by listing, reading and deleting.
// No lock, no lost update, and a crash mid-write leaves a .tmp nobody reads.
//
// WHY THIS FILE IS NOT A mob_dev PLUGIN
//
// #58 proposes a tier-1 plugin, which needs `android.manifest_application_
// snippets` to declare its components. That key is undocumented, absent from
// mob 0.7.20's MOB_PLUGINS.md, and mob_dev has never had a 0.7.x release — so
// whether it splices at all against this host is an open UNKNOWN for the whole
// ecosystem, and #58 makes verifying it Phase 1 and everything else Phase 2.
// That spike needs a throwaway app and a device, neither of which exists here.
//
// The host route needs no splice: WorkManager self-initialises through the
// androidx.startup InitializationProvider merged from its own AAR manifest,
// and reschedules its own work after a reboot through its own
// RescheduleReceiver. So Kati's AndroidManifest.xml gains nothing at all for
// this feature — which is also the reason the fallback #58 names ("host
// manifest edit + host_requirement string") is not needed either. Recorded in
// native/LEDGER.md as the deliberate choice it is.
package com.example.kati

import android.content.Context
import android.util.Log
import androidx.work.BackoffPolicy
import androidx.work.Constraints
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.NetworkType
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.Worker
import androidx.work.WorkerParameters
import androidx.work.WorkManager
import java.io.File
import java.util.concurrent.TimeUnit
import org.json.JSONArray
import org.json.JSONObject

/** Enqueue / cancel the periodic refresh. Called from MobBridge. */
object KatiPeriodicWork {

    const val WORK_NAME = "kati_refresh"

    // The defaults live here rather than in MobBridge so the two numbers exist
    // in one place: Elixir sends them on every call, and the bridge falls back
    // to these only when the JSON omits them.
    const val DEFAULT_INTERVAL_MINUTES = 6L * 60
    const val DEFAULT_FLEX_MINUTES = 2L * 60

    private const val TAG = "KatiPeriodic"

    /**
     * Make sure the periodic refresh exists. Idempotent.
     *
     * The cadence is 6 h with a 2 h flex window, and three of those choices
     * are load-bearing:
     *
     *  * **KEEP, never REPLACE.** REPLACE restarts the interval clock on every
     *    call, so a user who opens Kati daily would never reach the 6 h mark
     *    and the worker would never run at all.
     *  * **Never the 15-minute floor.** 96 wakeups a day is indefensible for
     *    "did my series get a new episode", and it lands in Android Vitals'
     *    excessive-background-wakeups metric, which is a Play listing problem
     *    before it is a battery one.
     *  * **No setExpedited.** The expedited quota is 30 min per 24 h even in
     *    the Active standby bucket; spending it on a routine refresh means it
     *    is unavailable for anything that actually needs to be prompt.
     *
     * `interval_minutes` below 15 is clamped rather than rejected: WorkManager
     * silently raises it to the floor, and a caller that thinks it asked for
     * 5 minutes and got 15 has been misled by the platform.
     */
    @JvmStatic
    fun ensure(ctx: Context, intervalMinutes: Long, flexMinutes: Long): String =
        try {
            val interval = intervalMinutes.coerceAtLeast(15L)
            val flex = flexMinutes.coerceIn(5L, interval - 1)

            val constraints =
                Constraints.Builder()
                    .setRequiredNetworkType(NetworkType.CONNECTED)
                    .setRequiresBatteryNotLow(true)
                    .build()

            val request =
                PeriodicWorkRequestBuilder<KatiRefreshWorker>(
                        interval, TimeUnit.MINUTES, flex, TimeUnit.MINUTES
                    )
                    .setConstraints(constraints)
                    .setBackoffCriteria(BackoffPolicy.EXPONENTIAL, 30, TimeUnit.MINUTES)
                    .build()

            WorkManager.getInstance(ctx)
                .enqueueUniquePeriodicWork(WORK_NAME, ExistingPeriodicWorkPolicy.KEEP, request)
            "ok:$interval:$flex"
        } catch (e: Exception) {
            Log.w(TAG, "ensure failed: ${e.javaClass.simpleName}")
            "error:enqueue_failed"
        }

    @JvmStatic
    fun cancel(ctx: Context): String =
        try {
            WorkManager.getInstance(ctx).cancelUniqueWork(WORK_NAME)
            "ok"
        } catch (e: Exception) {
            Log.w(TAG, "cancel failed: ${e.javaClass.simpleName}")
            "error:cancel_failed"
        }
}

/**
 * The periodic refresh.
 *
 * ## The rule that keeps this small
 *
 * **The Worker never decides anything.** No Shamsi formatting, no "what counts
 * as watching", no per-show preferences, no budget. It reads a watchlist the
 * BEAM precomputed, does I/O, and writes what it found into the inbox. Every
 * rule stays in Elixir where it is tested; a reviewer can read all of this in
 * one sitting. The moment a domain question appears in this file, the answer
 * exists in two languages and they will disagree.
 *
 * ## What it does today, and what is deliberately missing
 *
 * Today: re-arms the alarms the OS may have dropped, and records the run so
 * the BEAM learns a refresh window elapsed while it was dead. Both are useful
 * on their own — an OEM battery saver that cancels alarms is not covered by
 * KatiBootReceiver, which only hears BOOT_COMPLETED / MY_PACKAGE_REPLACED /
 * TIME_SET / TIMEZONE_CHANGED.
 *
 * Missing: the actual metadata fetch. It is marked below rather than sketched,
 * because the shape it must take is already decided and writing a placeholder
 * that ignores it would be worse than nothing — `GET /3/tv/changes` returns
 * every show id changed in a 24 h window, so 40 followed shows cost **one**
 * request rather than forty, sent with If-None-Match and treating 304 as
 * success-with-no-change. It needs the provider credential work first.
 *
 * ## Result.retry() must not double-notify
 *
 * When the fetch lands: post notifications LAST, and record every posted id in
 * a SharedPreferences set this Worker checks first. A retry after a posted
 * notification is otherwise a second copy of the same notification, and
 * WorkManager retries are routine rather than exceptional.
 */
class KatiRefreshWorker(context: Context, params: WorkerParameters) :
    Worker(context, params) {

    override fun doWork(): Result {
        val ctx = applicationContext
        val started = System.currentTimeMillis()

        return try {
            // Cheap and idempotent: FLAG_UPDATE_CURRENT means re-arming an
            // alarm that is already armed changes nothing.
            KatiNotificationStore.rearmAll(ctx)

            // ── the fetch goes here ──────────────────────────────────────
            // Read KatiHandoff.watchlist(ctx), request TMDB /3/tv/changes
            // once for the whole list, diff on (show, season, episode) —
            // never on name or air date, TMDB revises both — and put what
            // changed into `found`.
            val found = JSONArray()

            KatiHandoff.record(
                ctx,
                JSONObject()
                    .put("at", started)
                    .put("outcome", "ok")
                    .put("checked", KatiHandoff.watchlistSize(ctx))
                    .put("items", found)
            )
            Result.success()
        } catch (e: Exception) {
            Log.w(TAG, "refresh failed: ${e.javaClass.simpleName}")
            Result.retry()
        }
    }

    private companion object {
        const val TAG = "KatiRefresh"
    }
}

/**
 * The filesystem handoff between the BEAM and the Kotlin worker.
 *
 * Two directions, both plain JSON in `MOB_DATA_DIR` — which is
 * `context.filesDir`, the same directory from both languages:
 *
 *   * **BEAM → Worker**: `kati_watchlist.json`, rewritten whole by Elixir on
 *     every follow/unfollow and on backgrounding.
 *   * **Worker → BEAM**: one file per run under `kati_inbox/`, drained and
 *     deleted by `Kati.Background.Handoff.drain/1` on next foreground.
 *
 * Kotlin only ever *reads* the watchlist and only ever *creates* inbox files.
 * Neither side edits a file the other owns, which is what removes the need for
 * a lock between two live processes-in-one-process.
 */
object KatiHandoff {

    const val WATCHLIST = "kati_watchlist.json"
    const val INBOX_DIR = "kati_inbox"

    private const val TAG = "KatiHandoff"

    /** The watchlist the BEAM last wrote, or an empty object. */
    @JvmStatic
    fun watchlist(ctx: Context): JSONObject =
        try {
            val file = File(ctx.filesDir, WATCHLIST)
            if (file.isFile) JSONObject(file.readText()) else JSONObject()
        } catch (e: Exception) {
            Log.w(TAG, "unreadable watchlist: ${e.javaClass.simpleName}")
            JSONObject()
        }

    @JvmStatic
    fun watchlistSize(ctx: Context): Int = watchlist(ctx).optJSONArray("items")?.length() ?: 0

    /**
     * Write one run record into the inbox.
     *
     * Temp file plus rename on the same filesystem, so a reader either sees
     * the whole record or no file at all. A crash between the two leaves a
     * `.tmp` the drain ignores.
     */
    @JvmStatic
    fun record(ctx: Context, run: JSONObject): Boolean =
        try {
            val dir = File(ctx.filesDir, INBOX_DIR).also { it.mkdirs() }
            val stamp = System.currentTimeMillis()
            val tmp = File(dir, "$stamp.tmp")
            val out = File(dir, "$stamp.json")
            tmp.writeText(JSONObject().put("schema", 1).put("run", run).toString())
            tmp.renameTo(out)
        } catch (e: Exception) {
            Log.w(TAG, "could not record run: ${e.javaClass.simpleName}")
            false
        }
}
// KATI-END(K-22 periodic-worker)
