// KATI-BEGIN(K-15 device-timezone) mob_new=0.4.20
// KATI-VENDORED: this file is Kati's own, not generated by mob_new. It is
// fenced and ledgered because it exists to work around a gap in Mob.
//
// Mob exposes NO timezone API — nothing in deps/mob/lib, nothing in the
// bridge. On device the BEAM sees no TZ environment variable at all
// (System.get_env("TZ") is nil, :os.getenv(~c"TZ") is false), though
// :calendar.local_time/0 is correctly offset because bionic's libc resolves
// the system property internally.
//
// An OFFSET is not a ZONE. It cannot say when DST changes, so it cannot
// expand a recurrence correctly, which is the whole reason #47 needs this.
//
// Rather than add a NIF, the zone id is written into filesDir — the channel
// research already verified as MOB_DATA_DIR (mob_beam.zig:278) — and read
// from Elixir by Kati.Time. Written on every app start and again whenever
// Android broadcasts ACTION_TIMEZONE_CHANGED, which KatiBootReceiver already
// listens for.
package com.example.kati

import android.content.Context
import android.util.Log
import java.io.File
import java.util.TimeZone

object KatiDeviceZone {
    private const val TAG = "KatiTZ"
    private const val FILE = "device_tz"

    /** Writes the current IANA zone id (e.g. "Europe/Amsterdam") into filesDir. */
    @JvmStatic
    fun publish(context: Context) {
        try {
            val id = TimeZone.getDefault().id
            File(context.filesDir, FILE).writeText(id)
            Log.i(TAG, "device timezone published: $id")
        } catch (e: Exception) {
            // Never fatal: Kati.Time falls back to Etc/UTC and the app still runs.
            Log.w(TAG, "could not publish timezone: ${e.message}")
        }
    }
}
// KATI-END(K-15 device-timezone)
