// KATI-BEGIN(K-22 host-context) mob_new=0.4.20
// KATI-VENDORED: this file is Kati's own, not generated by mob_new. It is
// fenced and ledgered because it exists to work around a gap in Mob.
//
// WHY THIS FILE EXISTS
//
// MobBridge holds `activityRef`, a WeakReference<Activity>, and every bridge
// method that needs a Context reads it — `val activity = activityRef?.get() ?:
// return`. That is correct for anything that draws, and wrong for everything
// that does not:
//
//   * arming an alarm from a background token refresh, where the BEAM is alive
//     inside BeamForegroundService and the Activity was destroyed minutes ago;
//   * enqueuing or cancelling WorkManager work at the same moment;
//   * anything running from a Worker, which never has an Activity by
//     construction.
//
// In all three the WeakReference is null and the bridge method returns having
// done nothing, silently. That is the exact failure mode `K-01 notify-persist`
// exists to prevent one layer down — an alarm the caller believes is armed and
// is not — so the context has to outlive the Activity.
//
// Holding the APPLICATION context in a static is not a leak: it is the process
// singleton, and it lives exactly as long as the process does.
//
// WHY KatiSecureStore KEEPS ITS OWN COPY OF THIS
//
// Deliberately. `KatiSecureStore.kt` names no Kati type and no Mob type, which
// is what makes extracting it into a tier-1 plugin (or upstream as
// `mob_secure_store`) a file move rather than a rewrite. Making it depend on
// this file would trade that for six saved lines.
package com.example.kati

import android.content.Context

/** The application Context, for the Kati code that outlives the Activity. */
object KatiHostContext {

    @Volatile private var appContext: Context? = null

    /** Idempotent; safe to call on every onCreate. */
    @JvmStatic
    fun attach(context: Context) {
        if (appContext == null) appContext = context.applicationContext
    }

    /**
     * The application context, or null if nothing has attached one yet.
     *
     * Null is a real answer, not a bug to assert away: a `BroadcastReceiver`
     * or `Worker` that runs before MainActivity has ever been created reaches
     * this, and the caller passes its own Context instead. Callers that have
     * no Context at all report `error:no_context` rather than throwing.
     */
    @JvmStatic
    fun get(): Context? = appContext
}
// KATI-END(K-22 host-context)
