// KATI-BEGIN(K-73 release-check-file) mob_new=0.6.3
// KATI-VENDORED: this file is Kati's own, not generated by mob_new. It is the
// fetch the background refresh was missing (#125): with Kati closed, ask each
// followed show's source for its latest aired episode, and tell the reader
// about the ones after what Kati already knew — one notification per show.
package com.example.kati

import android.Manifest
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.util.Base64
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.content.ContextCompat
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.util.Calendar

/**
 * The worker's half of new-episode notifications.
 *
 * Everything that is a decision arrives in the watchlist the BEAM wrote
 * (`Kati.Background.Watchlist`): which shows, the last episode Kati knew had
 * aired for each, whether push is on, the quiet hours, and the words. This
 * only fetches, compares two numbers, and posts.
 *
 * A show is told about once per episode: the last `(season, episode)` posted
 * for it is kept in SharedPreferences, so a WorkManager retry, or a second run
 * before the BEAM has caught up, does not post the same news twice.
 */
object KatiReleaseCheck {

    private const val TAG = "KatiReleaseCheck"
    private const val PREFS = "kati_release_check"
    const val CHANNEL = "kati_new_episodes"
    private const val GROUP = "kati_new_episodes"

    data class Episode(val season: Int, val episode: Int) : Comparable<Episode> {
        override fun compareTo(other: Episode): Int =
            compareValuesBy(this, other, { it.season }, { it.episode })
    }

    /** What one run found: one JSON object per show with news. */
    @JvmStatic
    fun run(ctx: Context, watchlist: JSONObject): JSONArray {
        val items = watchlist.optJSONArray("items") ?: JSONArray()
        val settings = watchlist.optJSONObject("settings") ?: JSONObject()
        val strings = watchlist.optJSONObject("strings") ?: JSONObject()
        val token = tmdbToken(ctx)
        val found = JSONArray()

        for (i in 0 until items.length()) {
            val item = items.optJSONObject(i) ?: continue
            if (!item.has("last_season") || !item.has("last_episode")) continue
            val known = Episode(item.optInt("last_season"), item.optInt("last_episode"))
            val latest = try {
                latestAired(item, token)
            } catch (e: Exception) {
                Log.w(TAG, "check failed: ${e.javaClass.simpleName}")
                null
            } ?: continue
            if (latest <= known) continue

            val trackedId = item.optString("tracked_id")
            if (trackedId.isEmpty() || alreadyTold(ctx, trackedId, latest)) continue

            val count = if (latest.season == known.season) latest.episode - known.episode else latest.episode
            val from = if (latest.season == known.season) known.episode + 1 else 1
            val range = if (count <= 1) "S${latest.season}E${latest.episode}"
                else "S${latest.season}E$from–${latest.episode}"
            val body = if (count <= 1) fill(strings.optString("one", "New episode · {range}"), count, range, strings)
                else fill(strings.optString("many", "{count} new episodes · {range}"), count, range, strings)

            found.put(
                JSONObject()
                    .put("tracked_id", trackedId)
                    .put("kind", item.optString("kind", "tv"))
                    .put("title", item.optString("title"))
                    .put("body", body)
                    .put("key", "S${latest.season}E${latest.episode}")
                    .put("season", latest.season)
                    .put("episode", latest.episode)
            )
        }

        val loud = settings.optBoolean("push", false) && !quiet(settings.optJSONObject("quiet"))
        if (loud && found.length() > 0 && canPost(ctx)) {
            post(ctx, found, strings)
            for (i in 0 until found.length()) {
                val f = found.getJSONObject(i)
                told(ctx, f.getString("tracked_id"), Episode(f.getInt("season"), f.getInt("episode")))
            }
        }
        return found
    }

    /** The latest aired episode at the item's source, or null. */
    fun latestAired(item: JSONObject, token: String?): Episode? {
        val id = item.optString("source_id")
        return when (item.optString("source")) {
            "tmdb" -> token?.let { tmdb(id, it) }
            "tvmaze" -> tvmaze(id)
            "anilist" -> anilist(id)
            else -> null
        }
    }

    private fun tmdb(id: String, token: String): Episode? {
        val body = get("https://api.themoviedb.org/3/tv/$id", mapOf("Authorization" to "Bearer $token"))
            ?: return null
        val last = JSONObject(body).optJSONObject("last_episode_to_air") ?: return null
        return Episode(last.optInt("season_number"), last.optInt("episode_number"))
    }

    private fun tvmaze(id: String): Episode? {
        val body = get("https://api.tvmaze.com/shows/$id?embed=previousepisode") ?: return null
        val prev = JSONObject(body).optJSONObject("_embedded")?.optJSONObject("previousepisode")
            ?: return null
        return Episode(prev.optInt("season"), prev.optInt("number"))
    }

    private fun anilist(id: String): Episode? {
        val query = JSONObject()
            .put("query", "query(\$id:Int){Media(id:\$id){episodes status nextAiringEpisode{episode}}}")
            .put("variables", JSONObject().put("id", id.toIntOrNull() ?: return null))
        val body = post("https://graphql.anilist.co", query.toString()) ?: return null
        val media = JSONObject(body).optJSONObject("data")?.optJSONObject("Media") ?: return null
        val next = media.optJSONObject("nextAiringEpisode")
        val aired = when {
            next != null -> next.optInt("episode") - 1
            media.optString("status") == "FINISHED" -> media.optInt("episodes")
            else -> 0
        }
        return if (aired > 0) Episode(1, aired) else null
    }

    private fun get(url: String, headers: Map<String, String> = emptyMap()): String? {
        val conn = URL(url).openConnection() as HttpURLConnection
        return try {
            conn.connectTimeout = 10_000
            conn.readTimeout = 10_000
            conn.setRequestProperty("Accept", "application/json")
            headers.forEach { (k, v) -> conn.setRequestProperty(k, v) }
            if (conn.responseCode == 200) conn.inputStream.bufferedReader().use { it.readText() } else null
        } finally {
            conn.disconnect()
        }
    }

    private fun post(url: String, json: String): String? {
        val conn = URL(url).openConnection() as HttpURLConnection
        return try {
            conn.connectTimeout = 10_000
            conn.readTimeout = 10_000
            conn.requestMethod = "POST"
            conn.doOutput = true
            conn.setRequestProperty("Content-Type", "application/json")
            conn.setRequestProperty("Accept", "application/json")
            conn.outputStream.use { it.write(json.toByteArray()) }
            if (conn.responseCode == 200) conn.inputStream.bufferedReader().use { it.readText() } else null
        } finally {
            conn.disconnect()
        }
    }

    /** The reader's own TMDB token, from the Keystore-backed store. */
    private fun tmdbToken(ctx: Context): String? {
        KatiSecureStore.attach(ctx)
        val reply = KatiSecureStore.get("tmdb")
        if (!reply.startsWith("ok:")) return null
        return String(Base64.decode(reply.removePrefix("ok:"), Base64.NO_WRAP)).ifEmpty { null }
    }

    /** Inside the quiet window, in minutes after local midnight. */
    fun quiet(window: JSONObject?, now: Calendar = Calendar.getInstance()): Boolean {
        if (window == null) return false
        val from = window.optInt("from", -1)
        val to = window.optInt("to", -1)
        if (from < 0 || to < 0) return false
        val minute = now.get(Calendar.HOUR_OF_DAY) * 60 + now.get(Calendar.MINUTE)
        return if (from > to) minute >= from || minute < to else minute in from until to
    }

    private fun fill(template: String, count: Int, range: String, strings: JSONObject): String =
        localDigits(template.replace("{count}", count.toString()).replace("{range}", range), strings)

    /** Write the digits the reader's language writes. */
    private fun localDigits(text: String, strings: JSONObject): String {
        val digits = strings.optString("digits", "0123456789")
        if (digits.length != 10) return text
        return text.map { c -> if (c in '0'..'9') digits[c - '0'] else c }.joinToString("")
    }

    private fun canPost(ctx: Context): Boolean =
        Build.VERSION.SDK_INT < 33 ||
            ContextCompat.checkSelfPermission(ctx, Manifest.permission.POST_NOTIFICATIONS) ==
            PackageManager.PERMISSION_GRANTED

    private fun alreadyTold(ctx: Context, trackedId: String, latest: Episode): Boolean {
        val stored = ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(trackedId, null)
            ?: return false
        val parts = stored.split(":")
        val told = Episode(parts.getOrNull(0)?.toIntOrNull() ?: 0, parts.getOrNull(1)?.toIntOrNull() ?: 0)
        return latest <= told
    }

    private fun told(ctx: Context, trackedId: String, latest: Episode) {
        ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit()
            .putString(trackedId, "${latest.season}:${latest.episode}")
            .apply()
    }

    /** One notification per show, grouped, with a summary once there are two. */
    fun post(ctx: Context, found: JSONArray, strings: JSONObject) {
        val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        if (Build.VERSION.SDK_INT >= 26) {
            nm.createNotificationChannel(
                NotificationChannel(
                    CHANNEL, strings.optString("channel", "New episodes"),
                    NotificationManager.IMPORTANCE_DEFAULT
                )
            )
        }

        val lines = mutableListOf<String>()
        for (i in 0 until found.length()) {
            val f = found.getJSONObject(i)
            val trackedId = f.getString("tracked_id")
            val title = f.optString("title")
            val body = f.optString("body")
            lines.add("$title — $body")

            val notif = NotificationCompat.Builder(ctx, CHANNEL)
                .setSmallIcon(R.drawable.kati_mark)
                .setContentTitle(title)
                .setContentText(body)
                .setGroup(GROUP)
                .setAutoCancel(true)
                .setContentIntent(tap(ctx, trackedId, title, body, f.optString("kind", "tv")))
                .build()
            nm.notify("kati_ep_$trackedId".hashCode(), notif)
        }

        if (found.length() >= 2) {
            val summary = localDigits(
                strings.optString("summary", "New episodes of {shows} shows")
                    .replace("{shows}", found.length().toString()),
                strings
            )
            val style = NotificationCompat.InboxStyle().setSummaryText(summary)
            lines.forEach { style.addLine(it) }
            val group = NotificationCompat.Builder(ctx, CHANNEL)
                .setSmallIcon(R.drawable.kati_mark)
                .setContentTitle(summary)
                .setStyle(style)
                .setGroup(GROUP)
                .setGroupSummary(true)
                .setAutoCancel(true)
                .setContentIntent(open(ctx, "kati_ep_summary", summary, JSONObject().put("kati_open", "notifications")))
                .build()
            nm.notify("kati_ep_summary".hashCode(), group)
        }
    }

    private fun tap(ctx: Context, trackedId: String, title: String, body: String, kind: String): PendingIntent =
        open(
            ctx, "kati_ep_$trackedId", title,
            JSONObject().put("kati_open", "title").put("id", trackedId).put("kind", kind),
            body
        )

    // The envelope `Mob.Router` decodes on a tap, as NotificationReceiver
    // builds it, so `Kati.Widgets.Launch.open/2` can route it.
    private fun open(ctx: Context, id: String, title: String, data: JSONObject, body: String = ""): PendingIntent {
        val envelope = JSONObject()
            .put("id", id)
            .put("title", title)
            .put("body", body)
            .put("source", "local")
            .put("presentation", "tap")
            .put("action", "default")
            .put("data", data)
            .toString()
        val intent = Intent(ctx, MainActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP
            putExtra("mob_notification_json", envelope)
        }
        return PendingIntent.getActivity(
            ctx, id.hashCode(), intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )
    }
}
// KATI-END(K-73 release-check-file)
