// Kati's own file, not generated by mob_new.
//
// Reads kati_widget.json — written by Kati.Widgets.Snapshot on the Elixir
// side — and never touches kati.db or the BEAM. See KatiRefreshWorker.kt for
// why a widget (like the periodic worker) cannot boot a headless BEAM.
package com.example.kati

import android.content.Context
import android.util.Log
import androidx.compose.ui.unit.dp
import androidx.glance.GlanceId
import androidx.glance.GlanceModifier
import androidx.glance.GlanceTheme
import androidx.glance.appwidget.GlanceAppWidget
import androidx.glance.appwidget.GlanceAppWidgetReceiver
import androidx.glance.appwidget.provideContent
import androidx.glance.background
import androidx.glance.layout.Alignment
import androidx.glance.layout.Column
import androidx.glance.layout.fillMaxSize
import androidx.glance.layout.padding
import androidx.glance.text.FontWeight
import androidx.glance.text.Text
import androidx.glance.text.TextStyle
import java.io.File
import org.json.JSONObject

/** What Kati.Widgets.Snapshot.put/2 last wrote, or null if unreadable. */
private data class ContinueHero(val title: String, val meta: String)

private fun readHero(context: Context): ContinueHero? =
    try {
        val file = File(context.filesDir, "kati_widget.json")
        if (!file.isFile) {
            null
        } else {
            val hero = JSONObject(file.readText()).optJSONObject("hero")
            hero?.let { ContinueHero(it.getString("title"), it.getString("meta")) }
        }
    } catch (e: Exception) {
        Log.w("KatiContinueWidget", "unreadable snapshot: ${e.javaClass.simpleName}")
        null
    }

class KatiContinueWidget : GlanceAppWidget() {
    override suspend fun provideGlance(context: Context, id: GlanceId) {
        val hero = readHero(context)

        provideContent {
            GlanceTheme {
                Column(
                    modifier =
                        GlanceModifier.fillMaxSize()
                            .background(GlanceTheme.colors.background)
                            .padding(16.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalAlignment = Alignment.Start
                ) {
                    if (hero == null) {
                        Text(
                            text = "Nothing queued",
                            style =
                                TextStyle(
                                    fontWeight = FontWeight.Bold,
                                    color = GlanceTheme.colors.onBackground
                                )
                        )
                    } else {
                        Text(
                            text = hero.title,
                            style =
                                TextStyle(
                                    fontWeight = FontWeight.Bold,
                                    color = GlanceTheme.colors.onBackground
                                )
                        )
                        Text(
                            text = hero.meta,
                            style = TextStyle(color = GlanceTheme.colors.onSurfaceVariant)
                        )
                    }
                }
            }
        }
    }
}

class KatiContinueWidgetReceiver : GlanceAppWidgetReceiver() {
    override val glanceAppWidget: GlanceAppWidget = KatiContinueWidget()
}
