// KATI-BEGIN(K-19 secure-store) mob_new=0.4.20
// KATI-VENDORED: this file is Kati's own, not generated by mob_new. It is
// fenced and ledgered because it exists to work around a gap in Mob.
//
// WHY THIS FILE EXISTS
//
// Mob has no secure storage of any kind. Its two storage layers are
// Mob.State (a :dets file) and the app's SQLite database, and both are
// plaintext files inside the app sandbox. Kati is about to hold credentials
// to the user's *account*, not merely to Kati: a CalDAV app-specific
// password reaches an entire calendar, and an OAuth refresh token reaches
// it for as long as the user does not revoke it. Neither belongs in a
// plaintext file next to the meal log.
//
// WHY A KEYSTORE-WRAPPED AES KEY AND NOT EncryptedSharedPreferences
//
// The obvious candidate — androidx.security:security-crypto's MasterKey +
// EncryptedSharedPreferences — is DEPRECATED. Checked against the current
// AndroidX release notes (developer.android.com/jetpack/androidx/releases/
// security) on 2026-08-21: security-crypto reached stable 1.1.0 on
// 2025-07-30, and the 1.1.0-alpha07 (2025-04-09) and 1.1.0-beta01
// (2025-06-04) notes both read "Deprecated all APIs in favour of existing
// platform APIs and direct use of Android Keystore." Google is pointing
// implementers at exactly what this file does. Adding a deprecated
// third-party dependency — plus its Tink transitive, plus a Gradle edit and
// another permanent row in the drift ledger — to get a wrapper that is
// being withdrawn is a bad trade. So: no dependency, ~150 lines, the
// platform API directly.
//
// WHAT IS STORED WHERE
//
// The AES-256-GCM key lives in the AndroidKeyStore under one alias and
// never leaves it — on a device with a TEE or StrongBox the raw key bytes
// are not readable by this process at all, only usable. The CIPHERTEXT is
// an ordinary SharedPreferences entry: iv(12) || ciphertext || tag(16),
// base64. A plaintext XML file holding ciphertext is fine; that is the
// whole point of encrypting the tokens rather than the database.
//
// THREAT MODEL
//
// Defends against: another app or a file browser reading the sandbox; an
// `adb backup`-style extraction (android:allowBackup is already "false");
// a stolen unencrypted disk image; anyone reading kati.db.
//
// Does NOT defend against: a rooted device; an attacker holding the
// unlocked device while Kati runs — setUserAuthenticationRequired(false)
// is deliberate, because a background token refresh must work without a
// biometric prompt; a repackaged build signed with the developer's key; or
// code execution inside this process, which can simply call get().
// Never claim more than that.
package com.example.kati

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.StrongBoxUnavailableException
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import java.util.Arrays
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec

/**
 * Kati's credential store: AES-256-GCM under an AndroidKeyStore key.
 *
 * ## The wire contract with Elixir
 *
 * Every method takes and returns a `String`, because that is the only shape
 * Mob's JNI bridge marshals. Values cross the boundary **base64-encoded**:
 * a token is bytes, a JNI string is UTF-16, and a refresh token is not
 * required to be valid text. Base64 makes the channel byte-exact instead of
 * lossy-on-the-unlucky-token.
 *
 * Replies are a two-word protocol, never an exception across JNI:
 *
 *   - `"ok"`                — put/delete succeeded
 *   - `"ok:<base64>"`       — get succeeded
 *   - `"ok:hardware"` / `"ok:software"` — status: where the key lives
 *   - `"error:<reason>"`    — reason is one of a closed set (see below), so
 *                             the Elixir side can map it without ever
 *                             calling String.to_atom on native input
 *
 * Reasons: `not_found`, `no_context`, `corrupt`, `write_failed`,
 * `keystore_failed`.
 *
 * ## Why a decryption failure is `not_found` and not a crash
 *
 * The Keystore key can go away underneath us — a device that loses its
 * secure hardware state, a user who wipes credentials, a restore onto a new
 * device (the ciphertext cannot travel anyway, since the key never leaves
 * the device it was generated on). Every one of those makes the stored blob
 * permanently unreadable. The honest answer is "there is no credential
 * here", which makes the caller re-authenticate; the dishonest answer is a
 * raised exception that kills a sync worker on a loop forever.
 */
object KatiSecureStore {

    private const val TAG = "KatiSecure"
    private const val PREFS = "kati_secure_store"
    private const val ALIAS = "kati_secure_store_v1"
    private const val KEYSTORE = "AndroidKeyStore"
    private const val TRANSFORM = "AES/GCM/NoPadding"
    private const val IV_BYTES = 12
    private const val TAG_BITS = 128

    // The application context, not the Activity's. A background token
    // refresh runs while the BEAM is alive inside BeamForegroundService and
    // the Activity is long destroyed — MobBridge.activityRef is a
    // WeakReference and is null by then. Holding the *application* context
    // in a static is not a leak; it is the process singleton.
    @Volatile private var appContext: Context? = null

    /** Remembers the application context. Idempotent; safe to call often. */
    @JvmStatic
    fun attach(context: Context) {
        if (appContext == null) appContext = context.applicationContext
    }

    /**
     * `"ok:hardware"` when the key is held in a TEE or StrongBox,
     * `"ok:software"` when the device has neither and the Keystore fell back
     * to a software-backed key, `"error:<reason>"` when the Keystore itself
     * is unusable.
     *
     * Software-backed is a real degradation and is reported as such — but it
     * is still a Keystore key the app cannot export, which is strictly more
     * than a plaintext file. Degrading to *plaintext* is never an option
     * here: there is no code path in this file that writes an unencrypted
     * value.
     */
    @JvmStatic
    fun status(): String =
        try {
            if (isHardwareBacked(loadOrCreateKey())) "ok:hardware" else "ok:software"
        } catch (e: Exception) {
            fail("status", e)
        }

    /** Encrypts `valueB64` (base64 of the raw secret) under `key`. */
    @JvmStatic
    fun put(key: String, valueB64: String): String {
        val ctx = appContext ?: return "error:no_context"
        var plain: ByteArray? = null
        return try {
            plain = Base64.decode(valueB64, Base64.NO_WRAP)
            val cipher = Cipher.getInstance(TRANSFORM)
            cipher.init(Cipher.ENCRYPT_MODE, loadOrCreateKey())
            // The provider generates the IV; setRandomizedEncryptionRequired
            // means we are not allowed to supply one, which is what stops a
            // future edit from reusing an IV under a GCM key.
            val iv = cipher.iv
            val ct = cipher.doFinal(plain)
            val blob = ByteArray(iv.size + ct.size)
            System.arraycopy(iv, 0, blob, 0, iv.size)
            System.arraycopy(ct, 0, blob, iv.size, ct.size)
            val ok =
                ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                    .edit()
                    .putString(key, Base64.encodeToString(blob, Base64.NO_WRAP))
                    // commit(), not apply(): the caller is told :ok only once
                    // the bytes are on disk. A token "saved" that is lost to a
                    // process kill is a silent re-auth loop later.
                    .commit()
            if (ok) "ok" else "error:write_failed"
        } catch (e: Exception) {
            fail("put", e)
        } finally {
            plain?.let { Arrays.fill(it, 0.toByte()) }
        }
    }

    /** `"ok:<base64>"`, or `"error:not_found"` when there is nothing readable. */
    @JvmStatic
    fun get(key: String): String {
        val ctx = appContext ?: return "error:no_context"
        var plain: ByteArray? = null
        return try {
            val stored =
                ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(key, null)
                    ?: return "error:not_found"
            val blob = Base64.decode(stored, Base64.NO_WRAP)
            if (blob.size <= IV_BYTES) return "error:corrupt"
            val cipher = Cipher.getInstance(TRANSFORM)
            cipher.init(
                Cipher.DECRYPT_MODE,
                loadOrCreateKey(),
                GCMParameterSpec(TAG_BITS, blob, 0, IV_BYTES),
            )
            val decrypted = cipher.doFinal(blob, IV_BYTES, blob.size - IV_BYTES)
            plain = decrypted
            "ok:" + Base64.encodeToString(decrypted, Base64.NO_WRAP)
        } catch (e: AEADBadTagException) {
            // The key that encrypted this is gone and a new one took its
            // alias. The blob can never be read again, so stop pretending it
            // is a credential.
            Log.w(TAG, "undecryptable entry dropped for $key")
            forget(ctx, key)
            "error:not_found"
        } catch (e: KeyPermanentlyInvalidatedException) {
            Log.w(TAG, "keystore key permanently invalidated; dropping $key")
            forget(ctx, key)
            "error:not_found"
        } catch (e: Exception) {
            fail("get", e)
        } finally {
            plain?.let { Arrays.fill(it, 0.toByte()) }
        }
    }

    /** Removes `key`. Removing something that is not there is `"ok"`. */
    @JvmStatic
    fun delete(key: String): String {
        val ctx = appContext ?: return "error:no_context"
        return try {
            val ok =
                ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                    .edit()
                    .remove(key)
                    .commit()
            if (ok) "ok" else "error:write_failed"
        } catch (e: Exception) {
            fail("delete", e)
        }
    }

    // ── internals ────────────────────────────────────────────────────────

    private fun forget(ctx: Context, key: String) {
        try {
            ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit().remove(key).commit()
        } catch (e: Exception) {
            Log.w(TAG, "could not drop unreadable entry: ${e.message}")
        }
    }

    private fun loadOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(KEYSTORE)
        ks.load(null)
        val entry = ks.getEntry(ALIAS, null)
        if (entry is KeyStore.SecretKeyEntry) return entry.secretKey
        return createKey()
    }

    private fun createKey(): SecretKey {
        // StrongBox is a discrete security chip and is absent on most
        // devices; asking for it and falling back is the documented pattern.
        // minSdk is 28, so both the API and the exception class exist
        // everywhere Kati runs.
        try {
            return generate(strongBox = true)
        } catch (e: StrongBoxUnavailableException) {
            Log.i(TAG, "no StrongBox on this device; using the TEE or a software key")
        } catch (e: Exception) {
            Log.i(TAG, "StrongBox key generation failed (${e.javaClass.simpleName}); retrying")
        }
        return generate(strongBox = false)
    }

    private fun generate(strongBox: Boolean): SecretKey {
        val builder =
            KeyGenParameterSpec.Builder(
                    ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setRandomizedEncryptionRequired(true)
                // Deliberate: no biometric or lock-screen gate. Kati refreshes
                // tokens from a background worker with no UI attached, and a
                // store that can only be read while the user is looking at the
                // phone cannot do that. The user-presence-required variant
                // belongs to a future "lock Kati" feature, not to this one.
                .setUserAuthenticationRequired(false)
        if (strongBox) builder.setIsStrongBoxBacked(true)
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        gen.init(builder.build())
        return gen.generateKey()
    }

    private fun isHardwareBacked(key: SecretKey): Boolean =
        try {
            val factory = SecretKeyFactory.getInstance(key.algorithm, KEYSTORE)
            val info = factory.getKeySpec(key, KeyInfo::class.java) as KeyInfo
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                info.securityLevel != KeyProperties.SECURITY_LEVEL_SOFTWARE
            } else {
                @Suppress("DEPRECATION")
                info.isInsideSecureHardware
            }
        } catch (e: Exception) {
            // Unknown is reported as software: never overstate the protection.
            Log.i(TAG, "could not read key security level: ${e.message}")
            false
        }

    /**
     * Logs the class name only. An exception message from a crypto provider
     * can carry the alias, the key size and occasionally a fragment of the
     * input; none of that belongs in logcat, which any other app with READ_LOGS
     * (or anyone with adb) can read.
     */
    private fun fail(op: String, e: Exception): String {
        Log.w(TAG, "secure store $op failed: ${e.javaClass.simpleName}")
        return "error:keystore_failed"
    }
}
// KATI-END(K-19 secure-store)
