// KATI-BEGIN(K-71 boot-screen-file) mob_new=0.6.3
// KATI-VENDORED: this file is Kati's own, not generated by mob_new. It is
// fenced and ledgered because it covers a gap in Mob: nothing draws between
// the window's first frame and the BEAM's first screen (#111).
package com.example.kati

import android.content.Context
import android.content.res.Configuration
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.Crossfade
import androidx.compose.animation.core.tween
import androidx.compose.animation.fadeOut
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import androidx.core.graphics.drawable.toBitmap
import kotlinx.coroutines.delay

/**
 * What the screen shows from the first frame until the BEAM's first screen (#111).
 *
 * Android draws the window about 300 ms after the tap, and the BEAM's first
 * screen lands a second or two later (longer on a first run, which unpacks the
 * runtime). That gap used to show Material's stock dark ground, then Mob's
 * theme before any screen, then Kati's paper with nothing on it: three colours
 * in two seconds. This draws one thing over all of it: the launch mark on
 * Kati's paper, then, if the wait goes on, a page skeleton, and the real screen
 * fades in over whichever is showing.
 *
 * It draws immediately rather than holding the window back: Mob starts the BEAM
 * only once the window has drawn (`mob_start_beam` polls `hasWindowFocus`), so
 * a splash that withholds the first frame delays the very thing it waits for.
 *
 * The paper is the one Kati last used, remembered here because the theme lives
 * in the BEAM and the BEAM is not up yet. A first run has none and follows the
 * phone, as the splash before it does.
 */
@Composable
fun KatiBoot(ready: Boolean, themeColors: Map<String, Long>?, content: @Composable () -> Unit) {
    val context = LocalContext.current
    val palette = remember { BootPalette.remembered(context) }
    val systemDark = isSystemInDarkTheme()
    val boot = palette ?: BootPalette.defaults(systemDark)

    LaunchedEffect(themeColors) {
        themeColors?.let { BootPalette.from(it)?.save(context) }
    }

    var booting by remember { mutableStateOf(!ready) }
    LaunchedEffect(ready) { if (ready) booting = false }

    Box(Modifier.fillMaxSize()) {
        content()
        AnimatedVisibility(visible = booting, enter = androidx.compose.animation.EnterTransition.None,
            exit = fadeOut(tween(220))) {
            BootScreen(boot)
        }
    }
}

@Composable
private fun BootScreen(palette: BootPalette) {
    var long by remember { mutableStateOf(false) }
    LaunchedEffect(Unit) {
        delay(SKELETON_AFTER_MS)
        long = true
    }

    Box(Modifier.fillMaxSize().background(palette.ground)) {
        Crossfade(targetState = long, animationSpec = tween(260), label = "boot") { skeleton ->
            if (skeleton) PageSkeleton(palette) else LaunchMark(palette)
        }
    }
}

// The splash's mark, at the splash's size, so the hand-over from Android's own
// splash is not a change at all when the remembered paper matches the phone's.
@Composable
private fun LaunchMark(palette: BootPalette) {
    val context = LocalContext.current
    val density = LocalDensity.current
    val sizePx = with(density) { MARK_SIZE.roundToPx() }
    val mark = remember(palette.dark, sizePx) {
        val night = Configuration(context.resources.configuration).apply {
            uiMode = (uiMode and Configuration.UI_MODE_NIGHT_MASK.inv()) or
                (if (palette.dark) Configuration.UI_MODE_NIGHT_YES else Configuration.UI_MODE_NIGHT_NO)
        }
        ContextCompat.getDrawable(context.createConfigurationContext(night), R.drawable.boot_mark)
            ?.toBitmap(sizePx, sizePx)
            ?.asImageBitmap()
    }

    Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        mark?.let { Image(bitmap = it, contentDescription = null, modifier = Modifier.size(MARK_SIZE)) }
    }
}

// A page in outline: date, title, search, two cards, the bottom bar. Generic
// enough to precede Home or a first-run step without promising either's
// content.
@Composable
private fun PageSkeleton(palette: BootPalette) {
    Column(
        Modifier.fillMaxSize().statusBarsPadding().navigationBarsPadding()
            .padding(horizontal = 20.dp, vertical = 24.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        Bar(palette, width = 130.dp, height = 12.dp)
        Bar(palette, width = 210.dp, height = 30.dp)
        Spacer(Modifier.height(4.dp))
        Bar(palette, height = 48.dp, radius = 24.dp)
        Spacer(Modifier.height(8.dp))
        Bar(palette, width = 90.dp, height = 10.dp)
        Bar(palette, height = 92.dp, radius = 20.dp)
        Bar(palette, height = 92.dp, radius = 20.dp)
        Spacer(Modifier.weight(1f))
        Row(verticalAlignment = Alignment.CenterVertically) {
            Bar(palette, width = 230.dp, height = 56.dp, radius = 28.dp)
            Spacer(Modifier.weight(1f))
            Bar(palette, width = 64.dp, height = 64.dp, radius = 32.dp)
        }
    }
}

@Composable
private fun Bar(palette: BootPalette, width: Dp? = null, height: Dp, radius: Dp = 8.dp) {
    val sized = if (width != null) Modifier.width(width) else Modifier.fillMaxWidth()
    Box(sized.height(height).background(palette.block, RoundedCornerShape(radius)))
}

private const val SKELETON_AFTER_MS = 1200L
private val MARK_SIZE = 133.dp

/** The two colours the boot screen draws with, and whether they are the dark pair. */
private data class BootPalette(val ground: Color, val block: Color, val dark: Boolean) {
    fun save(context: Context) {
        prefs(context).edit()
            .putLong(GROUND, ground.value.toLong())
            .putLong(BLOCK, block.value.toLong())
            .putBoolean(DARK, dark)
            .apply()
    }

    companion object {
        private const val PREFS = "kati_boot"
        private const val GROUND = "ground"
        private const val BLOCK = "block"
        private const val DARK = "dark"

        private fun prefs(context: Context) = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        fun remembered(context: Context): BootPalette? {
            val p = prefs(context)
            if (!p.contains(GROUND)) return null
            return BootPalette(
                Color(p.getLong(GROUND, 0L).toULong()),
                Color(p.getLong(BLOCK, 0L).toULong()),
                p.getBoolean(DARK, false),
            )
        }

        // Kati.Theme's paper and card, light and dark.
        fun defaults(dark: Boolean) =
            if (dark) BootPalette(Color(0xFF121110), Color(0xFF1E1D1B), true)
            else BootPalette(Color(0xFFEFECE7), Color(0xFFFBFAF8), false)

        // The theme the BEAM set: `background` is the paper, `surface` the card.
        fun from(theme: Map<String, Long>): BootPalette? {
            val ground = theme["background"]?.let { Color(it) } ?: return null
            val block = theme["surface"]?.let { Color(it) } ?: return null
            val luminance = 0.2126f * ground.red + 0.7152f * ground.green + 0.0722f * ground.blue
            return BootPalette(ground, block, luminance < 0.5f)
        }
    }
}
// KATI-END(K-71 boot-screen-file)
