// KATI-BEGIN(K-05 vendored-header) mob_new=0.4.20
// KATI-VENDORED: generated by mob_new 0.4.20 against mob 0.7.20 on 2026-08-18.
// Third-party code. Do not edit outside KATI-BEGIN/KATI-END fences.
// Upgrade procedure: bin/mob_bridge_diff.sh — see native/README.md.
// KATI-END(K-05 vendored-header)
package com.example.kati

import android.app.Activity
import android.content.Context
import android.content.pm.PackageManager
import android.content.res.Configuration
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.safeDrawingPadding
// KATI-BEGIN(K-09 bottom-inset-only-imports) mob_new=0.4.20
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.asPaddingValues
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawing
// KATI-END(K-09 bottom-inset-only-imports)
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
// KATI-BEGIN(K-35 semantics-imports) mob_new=0.7.24
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.testTagsAsResourceId
// KATI-END(K-35 semantics-imports)
// KATI-BEGIN(K-12 rtl-imports) mob_new=0.4.20
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.unit.LayoutDirection
// KATI-END(K-12 rtl-imports)
import androidx.compose.ui.draw.clipToBounds
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.onSizeChanged
import java.io.File

class MainActivity : ComponentActivity() {

    companion object {
        private const val TAG = "Kati"
        init { System.loadLibrary("kati") }

        // KATI-BEGIN(K-38 one-beam-per-process-flag) mob_new=0.7.24
        // Companion to `K-38 one-beam-per-process`, and IN the companion object
        // for the reason that fence exists: it has to outlive any single
        // Activity. An instance field is recreated alongside the Activity it
        // belongs to, so it would read `false` on exactly the second `onCreate`
        // the guard is there to catch — a guard that is only ever true when it
        // is not needed.
        //
        // Written after making that mistake: the field was first placed below
        // `nativeStartBeam()`, which reads as though it were in this block and
        // is not, because the companion closes two lines above it.
        @JvmStatic
        private val beamStarted = java.util.concurrent.atomic.AtomicBoolean(false)
        // KATI-END(K-38 one-beam-per-process-flag)
    }

    // KATI-BEGIN(K-15 device-timezone-publish) mob_new=0.4.20
    // Publish before the BEAM starts so Kati.Time can read a zone id on its
    // very first call rather than falling back to UTC for one boot.
    private fun publishDeviceZone() = KatiDeviceZone.publish(this)
    // KATI-END(K-15 device-timezone-publish)

    external fun nativeSetActivity(activity: Activity)
    external fun nativeStartBeam()
    external fun nativeNotifyOrientation(orient: String)
    external fun nativeNotifyConnectivity(
        online: Boolean,
        transport: String,
        expensive: Boolean,
        validated: Boolean,
    )

    // ── Network connectivity ──────────────────────────────────────────────
    // A ConnectivityManager.NetworkCallback drives Mob.Device.network_state/0
    // and the :network subscription. registerDefaultNetworkCallback fires an
    // initial onCapabilitiesChanged, so the BEAM-side cache is seeded at start.
    private var connectivityManager: ConnectivityManager? = null
    private var networkCallback: ConnectivityManager.NetworkCallback? = null

    private fun registerNetworkCallback() {
        val cm = getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager ?: return
        connectivityManager = cm
        val callback = object : ConnectivityManager.NetworkCallback() {
            override fun onCapabilitiesChanged(network: Network, caps: NetworkCapabilities) {
                pushConnectivity(caps)
            }

            override fun onLost(network: Network) {
                // Don't blindly report offline: on a wifi->cellular handoff the
                // lost default's onLost can arrive after the new default has
                // settled, which would leave us stuck offline. Re-check the
                // current active network before concluding there's no path.
                val active = connectivityManager?.activeNetwork
                val caps = active?.let { connectivityManager?.getNetworkCapabilities(it) }
                pushConnectivity(caps)
            }
        }
        networkCallback = callback
        try {
            cm.registerDefaultNetworkCallback(callback)
        } catch (_: Throwable) {
        }
    }

    private fun pushConnectivity(caps: NetworkCapabilities?) {
        if (caps == null) {
            notifyConnectivitySafe(false, "none", false, false)
            return
        }
        val transport = when {
            caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) -> "wifi"
            caps.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) -> "cellular"
            caps.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET) -> "wired"
            else -> "other"
        }
        val expensive = !caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_METERED)
        // Android actively probes for real internet reachability — false on a
        // captive portal / before validation. iOS has no equivalent (:unavailable).
        val validated = caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)
        notifyConnectivitySafe(true, transport, expensive, validated)
    }

    private fun notifyConnectivitySafe(
        online: Boolean,
        transport: String,
        expensive: Boolean,
        validated: Boolean,
    ) {
        try {
            nativeNotifyConnectivity(online, transport, expensive, validated)
        } catch (_: Throwable) {
        }
    }

    // ── File picker launcher ──────────────────────────────────────────────
    private val filePickerLauncher =
        registerForActivityResult(ActivityResultContracts.OpenMultipleDocuments()) { uris ->
            MobBridge.handleFilesResult(uris)
        }

    fun launchFilePicker() {
        filePickerLauncher.launch(arrayOf("*/*"))
    }

    // KATI-BEGIN(K-20 file-transport-launcher) mob_new=0.4.20
    // WHY: the two halves of #64's "get the backup off the device". MobBridge
    // owns the policy (see K-20 file-transport); an ActivityResultLauncher can
    // only be registered on the Activity, and only before it is STARTED —
    // which is why these are property initialisers alongside the stock
    // launchers rather than something MobBridge could create for itself.
    //
    // StartActivityForResult with an explicit Intent, not the
    // CreateDocument()/OpenDocument() contracts: the contract fixes the MIME
    // type at registration time, and Kati needs it per call (a .katibackup, an
    // .ics and a .csv are three different types through the same door). The
    // explicit Intent also keeps EXTRA_TITLE — the filename the dialog
    // pre-fills — under Elixir's control, which is what makes
    // Kati.Backup.suggested_filename/1 reach the user.
    private val katiSaveAsLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            MobBridge.handleKatiSaveAsResult(
                if (result.resultCode == Activity.RESULT_OK) result.data?.data else null
            )
        }

    fun launchKatiSaveAs(name: String, mime: String) {
        val intent = android.content.Intent(android.content.Intent.ACTION_CREATE_DOCUMENT).apply {
            addCategory(android.content.Intent.CATEGORY_OPENABLE)
            type = mime
            putExtra(android.content.Intent.EXTRA_TITLE, name)
        }
        katiSaveAsLauncher.launch(intent)
    }

    // The chooser's result code is NOT a completion signal: Android returns
    // RESULT_CANCELED whether the user dismissed the sheet or finished a
    // share, because the receiving app is what returns a result and almost
    // none do. It is forwarded anyway so the Elixir side can distinguish
    // "the sheet came back" from "the sheet never opened", and MobBridge
    // reports it as `dismissed` rather than inventing a completion.
    private val katiShareLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            MobBridge.handleKatiShareResult(result.resultCode == Activity.RESULT_OK)
        }

    fun launchKatiShare(chooser: android.content.Intent) {
        katiShareLauncher.launch(chooser)
    }
    // KATI-END(K-20 file-transport-launcher)

    // ── Permission result ─────────────────────────────────────────────────
    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == 9001) {
            val granted = grantResults.isNotEmpty() &&
                grantResults.all { it == PackageManager.PERMISSION_GRANTED }

            // KATI-BEGIN(K-37 republish-on-grant) mob_new=0.7.24
            // Re-read the calendar the moment it is granted, before Elixir is
            // told.
            //
            // `KatiCalendarReader.publish/1` runs in `onCreate` and nowhere
            // else, and it writes an empty array when the permission is
            // missing. So on the launch where someone grants access, the files
            // on disk are the empty ones written seconds earlier, and
            // `Kati.Calendars.DeviceImport.run/0` has nothing to ingest — the
            // permission is granted and the calendar stays empty until the next
            // cold start. Publishing here closes that gap; the ordering matters
            // because the Elixir side re-runs the import as soon as it hears
            // `{:permission, :calendar, :granted}`, and the files must already
            // be current when it does.
            if (granted) {
                try {
                    KatiCalendarReader.publish(this)
                } catch (e: Throwable) {
                    android.util.Log.w("Kati", "calendar re-publish after grant failed", e)
                }
            }
            // KATI-END(K-37 republish-on-grant)

            MobBridge.onPermissionResult(granted)
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        publishDeviceZone()
        // KATI-BEGIN(K-19 secure-store-attach) mob_new=0.4.20
        // Hand the credential store the APPLICATION context while there is
        // certainly an Activity to take it from. MobBridge.activityRef is a
        // WeakReference, so by the time a background token refresh runs — BEAM
        // alive inside BeamForegroundService, Activity destroyed — there is no
        // context left to derive one from, and every put/get would answer
        // "error:no_context". One line here removes that whole failure mode.
        KatiSecureStore.attach(this)
        // KATI-END(K-19 secure-store-attach)
        // KATI-BEGIN(K-22 host-context-attach) mob_new=0.4.20
        // Same reasoning as the line above, for everything that is not the
        // credential store: arming an alarm and enqueuing the periodic refresh
        // both happen while the BEAM is alive and the Activity is gone, where
        // MobBridge.activityRef is a null WeakReference. See KatiHostContext.
        KatiHostContext.attach(this)
        // KATI-END(K-22 host-context-attach)
        // KATI-BEGIN(K-26 calendar-publish) mob_new=0.4.20
        KatiCalendarReader.publish(this)
        // KATI-END(K-26 calendar-publish)
        // Edge-to-edge: lets the content draw behind the (transparent) status
        // and navigation bars instead of being letterboxed by opaque system
        // bars. Must be called BEFORE super.onCreate() per AndroidX docs.
        enableEdgeToEdge()
        super.onCreate(savedInstanceState)

        MobBridge.init(this)

        registerNetworkCallback()

        // Register activated plugins' Kotlin bridge classes (generated by
        // mob_dev at build time). Each register() caches its own jclass +
        // method IDs natively so the plugin's NIF can call into it; the
        // Activity is then handed to any bridge implementing
        // io.mob.plugin.MobActivityAware. Must run before the BEAM starts.
        io.mob.plugin.MobPluginBootstrap.registerAll(this)

        // Forward launcher-supplied env vars into the BEAM process. Set BEFORE
        // nativeStartBeam below so the BEAM (and Mob.Dist in particular) sees
        // them when it reads getenv()/System.get_env/1.
        //
        //   mob_node_suffix — appended to the configured node name
        //                     (`<app>_android` → `<app>_android_<suffix>`).
        //                     Lets multiple Android phones running the same
        //                     app coexist in Mac's shared EPMD.
        //   mob_dist_port   — Erlang dist listen port (default 9100).
        intent?.extras?.getString("mob_node_suffix")?.takeIf { it.isNotEmpty() }?.let { suffix ->
            android.system.Os.setenv("MOB_NODE_SUFFIX", suffix, true)
            Log.i(TAG, "onCreate: MOB_NODE_SUFFIX=$suffix")
        }

        intent?.extras?.getInt("mob_dist_port", -1)?.takeIf { it > 0 }?.let { port ->
            android.system.Os.setenv("MOB_DIST_PORT", port.toString(), true)
            Log.i(TAG, "onCreate: MOB_DIST_PORT=$port")
        }

        // Check if launched from a notification tap
        intent?.extras?.getString("mob_notification_json")?.let { json ->
            MobBridge.setLaunchNotification(json)
        }

        setContent {
            val state by MobBridge.rootState
            val themeColors by MobBridge.themeColors

            BackHandler(enabled = state.node != null) { MobBridge.nativeHandleBack() }

            // Material 3 chrome (NavigationBar, Button, …) pulls its colours
            // from `MaterialTheme.colorScheme`. We want those to match the
            // BEAM-side `Mob.Theme` so the system widgets don't clash with
            // mob's own primitives. `themeColors` updates via
            // `:mob_nif.set_theme/1` whenever `Mob.Theme.set(...)` runs.
            //
            // There's a brief window at launch — Compose evaluates setContent
            // before the BEAM finishes `mount/3` and pushes the first theme
            // — so the null branch falls back to Material's stock dark
            // scheme, which usually reads as a fine placeholder until the
            // real palette arrives.
            val colorScheme = themeColors?.let { tc ->
                darkColorScheme(
                    primary          = colorFromMap(tc, "primary",          0xFF6750A4),
                    onPrimary        = colorFromMap(tc, "on_primary",       0xFFFFFFFF),
                    secondary        = colorFromMap(tc, "secondary",        0xFF625B71),
                    onSecondary      = colorFromMap(tc, "on_secondary",     0xFFFFFFFF),
                    background       = colorFromMap(tc, "background",       0xFF1C1B1F),
                    onBackground     = colorFromMap(tc, "on_background",    0xFFE6E1E5),
                    surface          = colorFromMap(tc, "surface",          0xFF1C1B1F),
                    onSurface        = colorFromMap(tc, "on_surface",       0xFFE6E1E5),
                    // Mob's `surface_raised` / `muted` map onto Material 3's
                    // surfaceVariant / onSurfaceVariant — same role.
                    surfaceVariant   = colorFromMap(tc, "surface_raised",   0xFF49454F),
                    onSurfaceVariant = colorFromMap(tc, "muted",            0xFFCAC4D0),
                    outline          = colorFromMap(tc, "border",           0xFF938F99),
                    error            = colorFromMap(tc, "error",            0xFFF2B8B5),
                    onError          = colorFromMap(tc, "on_error",         0xFFFFFFFF),
                )
            } ?: darkColorScheme()

            MaterialTheme(colorScheme = colorScheme) {
                MobNavHost(state)
            }
        }

        // If the project ships embedded Python (mix mob.enable pythonx), the
        // APK contains assets/python/{stdlib,lib-dynload}/. Extract those to
        // filesDir on first launch and tell the BEAM where they landed via
        // env vars consumed by <App>.PythonPaths. Idempotent — re-launches
        // skip extraction once the marker file is present.
        extractPythonAssetsIfNeeded()

        Log.i(TAG, "onCreate — handing off to BEAM")
        nativeSetActivity(this)

        // KATI-BEGIN(K-38 one-beam-per-process) mob_new=0.7.24
        // Start the BEAM once per PROCESS, not once per Activity.
        //
        // `onCreate` runs again whenever Android recreates the Activity in a
        // live process, and this line started a second `beam-main` thread every
        // time. Two BEAMs in one process take SIGABRT in `beam-main` — no
        // Elixir exception, because it is not an Elixir error — and the process
        // dies with a `crash_dump helper` message that names nothing useful.
        //
        // `android:configChanges` in the manifest currently absorbs rotation,
        // `fontScale` and `uiMode`, which is why this has not been seen in
        // ordinary use. It does NOT absorb Android restoring a task from
        // recents, a locale change, or an Activity recreated for any reason the
        // manifest does not list — and every one of those is a real thing that
        // happens to a real phone. It was found by a device test whose two
        // methods shared a process (#96).
        //
        // `nativeSetActivity` stays OUTSIDE the guard: the new Activity is a
        // different object and the running BEAM has to be told about it, or it
        // draws into a window that is gone.
        if (beamStarted.compareAndSet(false, true)) {
            Thread({ nativeStartBeam() }, "beam-main").start()
        } else {
            Log.i(TAG, "onCreate — BEAM already running, re-attached only")
        }
        // KATI-END(K-38 one-beam-per-process)
        // KATI-BEGIN(K-51 widget-tap-relaunch) mob_new=0.4.33
        // A tap that starts a NEW Activity in a process whose BEAM is already
        // up — Android destroyed the Activity and kept the process. The stock
        // line above stored the payload for `Mob.Router`'s init, which has
        // already run and will not run again, so the tap went nowhere. When a
        // relay is registered (`notifyPid` is only non-zero once the BEAM's
        // `Kati.Native.TapRelay` has started, which is never true on a cold
        // start) take the payload back and deliver it the way `onNewIntent`
        // does. Not for a restore from saved state or from Recents: that
        // intent is the ORIGINAL one, and replaying an old tap would open a
        // title nobody just asked for.
        val relay = io.mob.plugin.MobNotifyHub.notifyPid
        val fromHistory =
            (intent?.flags ?: 0) and android.content.Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY != 0
        if (relay != 0L && savedInstanceState == null && !fromHistory) {
            intent?.extras?.getString("mob_notification_json")?.let { json ->
                MobBridge.setLaunchNotification(null)
                MobBridge.nativeDeliverNotification(relay, json)
            }
        }
        // KATI-END(K-51 widget-tap-relaunch)
    }

    private fun extractPythonAssetsIfNeeded() {
        val pythonRoot = File(filesDir, "python")
        val marker = File(pythonRoot, ".extracted")

        // libpython3.13.so is auto-extracted by the APK installer to the
        // app's nativeLibraryDir — point Pythonx.init/4 at it.
        val libPython = File(applicationInfo.nativeLibraryDir, "libpython3.13.so")

        if (libPython.exists()) {
            android.system.Os.setenv("MOB_PYTHON_DL", libPython.absolutePath, true)
        }

        // Skip extraction if no assets ship Python (project doesn't use Pythonx)
        // or if extraction has already happened.
        val assetList = try { assets.list("python") ?: emptyArray() } catch (_: Throwable) { emptyArray() }
        if (assetList.isEmpty() || marker.exists()) {
            if (pythonRoot.exists()) {
                android.system.Os.setenv("MOB_PYTHON_HOME", pythonRoot.absolutePath, true)
            }
            return
        }

        Log.i(TAG, "extractPythonAssets: extracting assets/python → ${pythonRoot.absolutePath}")
        copyAssetTree("python", pythonRoot)
        flattenLibDynload(pythonRoot)
        marker.createNewFile()
        android.system.Os.setenv("MOB_PYTHON_HOME", pythonRoot.absolutePath, true)
        Log.i(TAG, "extractPythonAssets: done")
    }

    // Chaquopy ships lib-dynload/<abi>/*.so per architecture; CPython expects
    // them flat in lib-dynload/. Move the device's primary-abi `.so` files
    // up one level and discard the rest.
    private fun flattenLibDynload(pythonRoot: File) {
        val libDynload = File(pythonRoot, "lib/python3.13/lib-dynload")
        if (!libDynload.isDirectory) return

        val deviceAbi = android.os.Build.SUPPORTED_ABIS.firstOrNull() ?: return
        val abiDir = File(libDynload, deviceAbi)
        if (!abiDir.isDirectory) return

        abiDir.listFiles()?.forEach { src ->
            val dst = File(libDynload, src.name)
            if (!dst.exists()) src.renameTo(dst)
        }
        // Drop the other-abi dirs to free space.
        libDynload.listFiles { f -> f.isDirectory }?.forEach { it.deleteRecursively() }
    }

    private fun copyAssetTree(srcPath: String, destDir: File) {
        val children = assets.list(srcPath) ?: emptyArray()

        if (children.isEmpty()) {
            // Leaf: copy the file
            destDir.parentFile?.mkdirs()
            assets.open(srcPath).use { input ->
                destDir.outputStream().use { output -> input.copyTo(output) }
            }
            return
        }

        destDir.mkdirs()
        for (child in children) {
            copyAssetTree("$srcPath/$child", File(destDir, child))
        }
    }

    // Called when a notification is tapped and the activity already exists at
    // the top of the stack (singleTop launch mode). If BEAM is running, deliver
    // the notification directly; otherwise store it for delivery on boot.
    override fun onNewIntent(intent: android.content.Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        intent.extras?.getString("mob_notification_json")?.let { json ->
            val pid = io.mob.plugin.MobNotifyHub.notifyPid
            if (pid != 0L) {
                MobBridge.nativeDeliverNotification(pid, json)
            } else {
                MobBridge.setLaunchNotification(json)
            }
        }
    }

    // Manifest declares `android:configChanges` including `uiMode`, so a
    // dark/light toggle delivers here instead of recreating the activity.
    // Forward to MobBridge so Mob.Device :appearance subscribers can react
    // (e.g. re-resolve Mob.Theme.Adaptive without an app restart).
    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        val nightMode = newConfig.uiMode and Configuration.UI_MODE_NIGHT_MASK
        val scheme = if (nightMode == Configuration.UI_MODE_NIGHT_YES) "dark" else "light"
        MobBridge.notifyColorSchemeChanged(scheme)

        // Forward the new orientation to the BEAM so Mob.Device.orientation/0 and
        // the :display subscription reflect a rotation (mob_send_orientation_changed).
        val orient = when (display?.rotation) {
            android.view.Surface.ROTATION_90 -> "landscape_left"
            android.view.Surface.ROTATION_270 -> "landscape_right"
            android.view.Surface.ROTATION_180 -> "portrait_upside_down"
            else -> "portrait"
        }
        try {
            nativeNotifyOrientation(orient)
        } catch (_: Throwable) {
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        val cm = connectivityManager
        val cb = networkCallback
        if (cm != null && cb != null) {
            try {
                cm.unregisterNetworkCallback(cb)
            } catch (_: Throwable) {
            }
        }
    }

    // Pulls an ARGB long out of the BEAM-pushed theme map, falling back to
    // a Material 3 stock dark value when the key isn't present (e.g. a
    // custom theme that doesn't define every Material 3 slot).
    private fun colorFromMap(map: Map<String, Long>, key: String, fallback: Long): Color =
        Color(map[key] ?: fallback)
}

// ── Identity-preserving screen presentation (MOB-146) ──────────────────────
//
// Navigation used to render through `AnimatedContent(contentKey = { navKey })`.
// AnimatedContent wraps each content in `key(contentKey)`, so a changing key
// disposes the outgoing composition and builds the incoming one from nothing —
// structurally the same thing `.id(currentNavVersion)` did on iOS before
// MOB-129. Measured on a 1600-node screen, physical moto g power: a push cost
// 818ms against a 221ms steady-state re-render.
//
// So navigation no longer changes identity. One mount point sits at a fixed
// structural position — that position IS its identity, and no key is used — and
// a navigation simply replaces the tree inside it. Compose then diffs the new
// tree against the one already mounted, which is what a re-render of the same
// screen has always done; the difference between a "navigation" and a
// "re-render" stops being a difference in kind and becomes a difference in how
// many nodes changed.
//
// The slide is driven by an animated offset on that mount point rather than by
// an enter/exit transition, because those only fire on insert/remove and
// insert/remove is precisely what costs the time.
//
// **Why one mount point and not two.** iOS uses two slots and keeps the
// outgoing tree parked, which buys depth-1 retention: popping back diffs
// against the screen still sitting in the other slot. That does not transfer.
// Measured here, a parked Compose subtree recomposes on every render of the
// active screen — 6 recompositions of the parked node across 6 re-renders —
// which took a steady-state re-render from 151ms to 273ms. Re-renders are far
// more frequent than navigations, so retention cost more than it saved. One
// slot keeps the whole win of identity preservation and none of that.
//
// The visible trade is that the outgoing screen does not slide out
// simultaneously; the incoming one slides in over the background. See mob's
// decisions/2026-09-04-two-slot-screen-presentation.md for the iOS original.
@Composable
private fun MobNavHost(state: RootState) {
    var containerWidth by remember { mutableIntStateOf(0) }
    val offset = remember { Animatable(0f) }

    // Keyed on navKey, NOT on `state`.
    //
    // `LaunchedEffect` cancels its coroutine when the key changes, and `state`
    // is a new RootState on every render. Keying on it meant any re-render
    // arriving during the 300ms slide — a timer, an async mount, a
    // subscription — cancelled `animateTo` and left the offset frozen wherever
    // it had reached. The screen stayed parked off-canvas and the app rendered
    // BLANK, while the BEAM went on reporting the correct screen and assigns:
    // an agent driving over dist would see nothing wrong. Reproduced on device
    // by sending one re-render 100ms after a navigation.
    //
    // navKey changes only on a real navigation, so an ordinary re-render
    // cannot cancel the slide, and a second navigation correctly interrupts
    // and restarts it.
    LaunchedEffect(state.navKey) {
        // Recovery first, before any early exit: an interrupted slide must not
        // be able to leave the screen displaced just because the width is not
        // known yet.
        if (containerWidth <= 0) {
            offset.snapTo(0f)
            return@LaunchedEffect
        }

        val width = containerWidth.toFloat()
        val from = when (state.transition) {
            "push" -> width
            "pop" -> -width
            else -> 0f
        }

        if (from == 0f) {
            // No slide for a reset or a first mount, but the offset still has
            // to be returned to rest in case a previous slide was interrupted.
            offset.snapTo(0f)
        } else {
            offset.snapTo(from)
            offset.animateTo(0f, tween(durationMillis = 300))
        }
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            // Painted, not inherited. Only one screen is mounted now, so the
            // strip the incoming screen has not covered yet shows whatever is
            // behind the composition — and that is the window background,
            // hardcoded black in styles.xml. Without this a light-themed app
            // gets a black wedge sweeping across it for the whole slide.
            .background(MaterialTheme.colorScheme.background)
            // Clips drawing AND hit-testing to the container, so a screen
            // parked off-screen mid-slide cannot be tapped.
            .clipToBounds()
            .onSizeChanged { containerWidth = it.width }
    ) {
        // `graphicsLayer`, not `offset`. Both read the animating value in a
        // lambda, so neither recomposes the tree per frame — but
        // `Modifier.offset {}` is a layout modifier, so every frame of the
        // slide re-runs the placement pass down through 1600 mounted nodes.
        // A layer translation moves the same pixels in the draw phase with no
        // layout invalidation at all, which on a performance ticket is the
        // difference worth having.
        Box(Modifier.fillMaxSize().graphicsLayer { translationX = offset.value }) {
            // Rendered straight from `state`, exactly as the AnimatedContent
            // version was. Routing it through a state variable set by a
            // LaunchedEffect would leave the first frame after every set_root
            // showing nothing, because effects run after composition.
            state.node?.let { node ->
                // navKey IS the epoch, and needs to be nothing more.
                //
                // The frame-registry gate has each tracked node remember the
                // generation current when it first composed, and refuses
                // writes stamped older than the current one. That used to work
                // for free: AnimatedContent made the incoming tree a fresh
                // composition, so it always captured the bumped value. With
                // the mount point preserved it is not free — nodes Compose
                // reuses across a navigation keep the generation they captured
                // for the PREVIOUS screen, which setRootJson has just
                // superseded, and their frame writes would be refused for
                // ever. element_frames would quietly lose those ids and tap_id
                // would stop finding them, with nothing raised.
                //
                // navKey moves on exactly the right events — every non-"none"
                // transition and nothing else — so re-keying the trackers on
                // it re-captures the generation on navigation and leaves a
                // same-screen re-render alone. Providing it through a
                // CompositionLocal is what keeps trackers from reading the
                // root state directly, which would resubscribe every tagged
                // node to every root update.
                // KATI-BEGIN(K-12 rtl-root) mob_new=0.4.33
                // Mob has no RTL support: nothing in deps/mob/lib or the
                // bridge sets LocalLayoutDirection, so Persian text renders
                // correctly shaped but always left-aligned.
                //
                // The direction comes from a `layout_direction` prop on the
                // ROOT node rather than from Locale.getDefault(), because
                // Kati's language is an in-app setting: a Persian user on an
                // English phone must still get RTL, and the two must never
                // disagree.
                //
                // mob_new 0.4.33 moved this block out of `AnimatedContent`
                // and into `MobNavHost`'s single mount point (MOB-146). The
                // wrapping is unchanged; only the place it wraps moved, and
                // it now sits INSIDE the slot-epoch provider so the frame
                // registry keeps the generation upstream gives it.
                val rtl = (node.props["layout_direction"] as? String) == "rtl"
                val direction = if (rtl) LayoutDirection.Rtl else LayoutDirection.Ltr

                // KATI-BEGIN(K-48 locale-face-root) mob_new=0.4.33
                // The app's default face, read off the same root node and for
                // the same reason as the direction above: the language is an
                // in-app setting, so a Persian reader on an English phone must
                // get Vazirmatn.
                //
                // This is the half no screen can reach. A Text a screen writes
                // can carry `font_family`; a Text a COMPONENT builds cannot,
                // and `MobBridge`'s `fontFamilyProp` resolved that missing
                // prop to Latin — so Kati's Persian was being set in Android's
                // substitute face, one component at a time, legibly enough
                // that nobody read it as a bug. `Kati.PersianFontTest`'s
                // moduledoc is where that was first written down.
                //
                // A root that names no face leaves `LocalKatiFace` null and
                // every Text behaves exactly as it did before.
                val face = node.props["font_family"] as? String
                // KATI-END(K-48 locale-face-root)

                CompositionLocalProvider(
                    MobBridge.LocalSlotEpoch provides state.navKey,
                    LocalLayoutDirection provides direction,
                    // KATI-BEGIN(K-48 locale-face-provide) mob_new=0.4.33
                    LocalKatiFace provides face,
                    // KATI-END(K-48 locale-face-provide)
                ) {
                    // KATI-BEGIN(K-09 bottom-inset-only) mob_new=0.4.33
                    // Bottom inset only, not safeDrawingPadding().
                    //
                    // The design's frames are 402x874 with `padding:64px 21px 132px`
                    // and they draw their OWN status bar inside that 64px. So the
                    // drawing measures from the physical top of the screen, and
                    // insetting the whole root pushed every screen down by the
                    // status bar's height — measured at ~42dp, which put Home's
                    // eyebrow at 106dp where the drawing has it at 64.
                    //
                    // The bottom is different and keeps its inset: the drawing is an
                    // iOS frame with a home indicator, while this device has a
                    // gesture bar the dock would otherwise sit under. Losing 30dp of
                    // paper at the bottom is invisible; a tab bar you cannot press
                    // is not.
                    RenderNode(
                        node,
                        modifier = Modifier
                            .fillMaxSize()
                            // KATI-BEGIN(K-35 test-tags-as-resource-id) mob_new=0.4.33
                            // Publishes every `testTag` under the tree as an Android
                            // `resource-id`. Compose keeps test tags to itself by
                            // default: `onNodeWithTag` sees them, a `uiautomator dump`
                            // does not. Set once at the root, it applies to the whole
                            // tree, and it is what lets a UI Automator test address a
                            // Kati control by the same name the Elixir side gave it.
                            .semantics { testTagsAsResourceId = true }
                            // KATI-END(K-35 test-tags-as-resource-id)
                            .padding(
                                bottom = WindowInsets.safeDrawing
                                    .asPaddingValues()
                                    .calculateBottomPadding()
                            )
                    )
                    // KATI-END(K-09 bottom-inset-only)
                }
                // KATI-END(K-12 rtl-root)
            }
        }
    }
}
